### ISSUE TITLE
Video size isn't saved now.

### ISSUE THREAD

**Issue by litaniast** [SourMesen/Mesen#104]
When I changed the video size setting in Mesen, It doesn't save the size and when I re-run it, it became 1x. (Even I use NTSC 2x or 4x, It became 1x when I re-start. When I press Alt-1, the size become correctly)

**Comment by cascardian** [comment]
Video size in Mesen is a real problem and deserves some more love. It also needs window position saving and saving custom sizing (not having window sizing independent of the filters just makes the window too large for the screen most of the time; see https://github.com/SourMesen/Mesen/issues/91). The custom sizing box in the video settings also just freaks out on me whenever I try to enter anything (immediately jumps to 10,00).
Moreover, Mesen doesn't immediately change the window size when changing the size via the menu oder via hotkeys. You have to restart Mesen to see the changed size. I can't be the only one this happens to and I doubt this is intentional.

These are just minor bugs. But GUI annoyances are one of those things that could keep users from this awesome emulator.

**Comment by SourMesen** [comment]
Yea - making filters & scale independent has been something I've been meaning to do for a while.  
The scale numeric field is pretty terrible too. Changing the scale via the alt-1 to 6 hotkeys should work though, but the effect won't be apparent right away if a game isn't running due to how it works internally.
Saving the position of the window is something someone else has asked for and is on my list of (endless) todos, too :)

**Comment by Cibomatto2002** [comment]
Can we see the list of things you want to do to Mesen?

**Comment by SourMesen** [comment]
I've made a few changes:
-Scale & filters are no longer linked, so 1x scale will display the same size no matter which filter is selected.  Makes it a lot better when choosing a filter, etc.
-The "scale" field in the video config should be more user-friendly than before
-The main window's position is saved
-The window should always change size when the scale setting is changed, whether or not a game is running

Hopefully that takes care of most issues - let me know what you think after the next release.

@Cibomatto2002  My todo list is 500-line text file (the majority of which I've already done), so it's not really something worth looking at - it contains anything from bugs, missing features, and some ideas.
The main things are already listed on the GitHub's main page, though - everything else is mostly just small improvements, bug fixes, etc.
