### ISSUE TITLE
Alien Syndrome (USA) (Unl). Needs Mapper: 158 to run

### ISSUE THREAD

**Issue by Cibomatto2002** [SourMesen/Mesen#112]
Loading rom: Alien Syndrome (USA) (Unl).nes
File CRC32: 0x9E8351AF
PRG+CHR CRC32: 0xCBF4366F
[iNes] Mapper: 118 Sub:0
[iNes] PRG ROM: 128 KB
[iNes] CHR ROM: 128 KB
[iNes] Mirroring: Vertical
[iNes] Battery: No
[DB] Game found in database
[DB] Mapper: 158  Sub: 0
[DB] System : NesNtsc
[DB] Board: TENGEN-800037
[DB] Chip: 337006
[DB] PRG ROM: 128 KB
[DB] CHR ROM: 128 KB
[DB] Battery: No
[DB] Database info will be used instead of file header.
[DB] Input: 2 standard controllers connected

**Comment by SourMesen** [comment]
Thanks for the report.
It looks like it's just a case of the game being classified incorrectly on NesCartDB:
http://bootgod.dyndns.org:7777/profile.php?id=325

This says 158, but the ROM is actually mapper 118 (and appears to work as expected as a mapper 118 game).  Disabling the built-in database will let you load up the rom (Preferences->Advanced) - though I don't suggest you disable the database in general (since a lot of ROMs rely on it to work properly)

**Comment by SourMesen** [comment]
Fixed by 3ccfae6e1c9a7695b18b05fea2a03632de872b3f
