### ISSUE TITLE
Request: More save states slots

### ISSUE THREAD

**Issue by Arcus87** [SourMesen/Mesen#113]
From menu "File - Save State" you can save only 5 save states, my idea is to add more save states from 5 to 9, like in Fceux or Nestopia

**Comment by SourMesen** [comment]
Thanks for the suggestion.
I added 2 more slots (b95c18b7296ecdd23510c5545dc4cd4cfb61fe61).
It's tricky to add more because I would have to change existing shortcut keys (F9, F10 and F12 are already used by other functions).
So, F1-F8 will load the save state, F1-F7 will save a state (slot 8 is reserved for the auto-save feature)
