### ISSUE TITLE
Sprites invisible when region set to Dendy

### ISSUE THREAD

**Issue by kazblox** [SourMesen/Mesen#116]
[Any explanation as for why?](https://cloud.githubusercontent.com/assets/17772724/23447336/2aa2e7ce-fe18-11e6-9caa-6bedd13a8c82.png)

I haven't tested if it happens in the latest commit, but this is taken from your debugger build which is pretty much on par with the most recent updates to the git repository.

**Comment by Cibomatto2002** [comment]
What is Dendy? What does it do?

**Comment by kazblox** [comment]
@Cibomatto2002 The Dendy option adjusts the CPU/PPU timings and refresh rate to behave like Dendy PAL-like famiclones.

**Comment by Cibomatto2002** [comment]
Thanks for telling me.

**Comment by SourMesen** [comment]
Thanks for the report!
I had accidentally broken OAM evaluation for Dendy while attempting to make the behavior more accurate on PAL consoles in a recent commit (guess I should record some automatic tests for Dendy to try and avoid this in the future!)
Fixed by e7ac6e428b417060fc01a37e44e0ec07b54413f7
