### ISSUE TITLE
Mesen do not open Magic Kid Googoo from No-Intro.

### ISSUE THREAD

**Issue by PinkLouie** [SourMesen/Mesen#119]
![image](https://cloud.githubusercontent.com/assets/24971871/23825188/f5757f5e-0663-11e7-9f45-11998581cb2f.png)

![image](https://cloud.githubusercontent.com/assets/24971871/23825215/722c0c7a-0664-11e7-944e-7382d217d4e2.png)

The same from No-Intro http://datomatic.no-intro.org/?page=show_record&s=45&n=2731

**Comment by SourMesen** [comment]
What version of Mesen are you using? This mapper is only supported on 0.7.1
You seem to have the right file, so you are probably using an older version of Mesen.
Otherwise, the iNES header in your rom may be incorrect (i.e it may be trying to use a mapper different than mapper 190) - you can check via the Log Window

**Comment by PinkLouie** [comment]
I am using 0.7.1. When I open the rom nothing shows in Log Windows. The .nes rom, came from within a file called "Magic Kid Googoo (Korea) (Unl)_headerless".

**Comment by SourMesen** [comment]
That's the problem then - "headerless" roms means they are missing vital information that is required for the emulator to load the file.  Apparently no-intro distributes these, but I do not know of any NES emulator that supports them.

**Comment by SourMesen** [comment]
For your info, I've added support for header-less rom files.
These will ONLY work when the rom is found inside Mesen's internal database.  If the game is missing, there is no way to load the game properly, so it won't load at all.
