### ISSUE TITLE
Lion King, official version unplayable

### ISSUE THREAD

**Issue by Arcus87** [SourMesen/Mesen#120]
If you try to play it, on the 1st level u can see that screen always shaking up & down.

Nestopia and Fceux doesn't have this problem

**Comment by SourMesen** [comment]
Thanks for the report.
As far as I can tell, this is working fine - you probably have the emulator set to "NTSC" or "Dendy" instead of "PAL" or "Auto".  This game is a PAL game, and it doesn't look like it works properly in NTSC/Dendy mode (the same bug is visible in NTSC/Dendy mode in FCEUX/Nestopia, too)

**Comment by Arcus87** [comment]
This is can't be fixed any way, right? Game problem itself, not emulators problem?

**Comment by SourMesen** [comment]
Yes, the game was built for PAL, and probably contains some timing code that doesn't work properly with NTSC/Dendy timings.  I've tried FCEUX, Nestopia, puNES and Nintendulator and they all behave the same - I don't think there's anything I can do about this one, you'll need to play it in PAL mode for it work.
