### ISSUE TITLE
Terminator 2 (LJN) Intro Skip?

### ISSUE THREAD

**Issue by wildgoosespeeder** [SourMesen/Mesen#121]
This is a very minor thing but I think that Mesen 0.7.1 is skipping the copyright information and "LJN PROUDLY PRESENTS" screens before the title screen displays while running Terminator 2. This doesn't occur in other emulators, such as puNES or even FCEUX. I can play the game no problem. Verified good dump ROM. My only way to verify the correct behavior is an AVGN episode.

- Windows 8.1 Pro 64-bit
- 12GB RAM
- Intel Core i5-3210M@2.5Ghz

**Comment by SourMesen** [comment]
I didn't know about this, but it looks like this is a bug in the game itself that only happens when RAM is initialized to 0s on bootup: http://wiki.nesdev.com/w/index.php/Game_bugs#Reliance_on_RAM_values

Initializing RAM to 0s on startup is the default behavior, but it's actually a setting you can change if you go to: Options->Emulation->Advanced->"Default power on state for RAM"
If you select "All 1s" or "Random Values", the copyright screen should show up as expected.

**Comment by wildgoosespeeder** [comment]
What a strange behavior. Is there any reason to have the default set to 0? Does the alternate settings affect other games negatively?

**Comment by SourMesen** [comment]
Any of the settings have their own down sides - all 1s can also cause issues in some other games.
If you look at the table I linked, you'll see that some of the bugs occur when using all 1s, because the games expect 0s, for example.
Random values are technically closer to what a real console would do (but even then from one unit to the other, the RAM might take different patterns at startup).  However, using random values means that some bugs will sometimes occur, and sometimes not - which might just make it harder for users to understand what's going on.
The games themselves are the problem - no software should ever read/use the value of uninitialized memory, but they do, which causes these bugs.

**Comment by wildgoosespeeder** [comment]
Thanks for the insight. At least I can try to play the two most elusive levels in video game history (Cheetahmen II). I'm guessing random values should do the trick and several resets. That's how you have to do it apparently. :P
