### ISSUE TITLE
MacOS version

### ISSUE THREAD

**Issue by cjoudrey** [SourMesen/Mesen#123]
:wave: -- It's great to see someone work on a cross-platform NES emulator that has a debugger. As a non-Windows user, I've always found it frustrating to have to open a Windows virtual machine to use FCEUX's debugging features.

I tried compiling Mesen on MacOS to see what breaks and unsurprisingly ran into a few issues.

My knowledge of C++ is extremely limited, but hopefully this helps with potentially supporting MacOS in the future:

- `fatal error: 'experimental/filesystem' file not found` on [Utilities/FolderUtilities.cpp#L4](https://github.com/SourMesen/Mesen/blob/1f34eeded6bf3fdf8e1e5fbb8c824ad519ac672e/Utilities/FolderUtilities.cpp#L4) - From what I understand this is because Xcode ships with an older version of Clang that Mesen requires.

- `fatal error: 'malloc.h' file not found` on [Utilities/Scale2x/scalebit.cpp#L41](https://github.com/SourMesen/Mesen/blob/1f34eeded6bf3fdf8e1e5fbb8c824ad519ac672e/Utilities/Scale2x/scalebit.cpp#L41) - I searched a bit and I've seen people suggest using `#include <cstdlib>` and `std::malloc` instead. Again, my knowledge of C++ is limited, so this might be an incorrect suggestion.

- `fatal error: 'linux/input.h' file not found` on [Linux/libevdev/libevdev.h#L30](https://github.com/SourMesen/Mesen/blob/1f34eeded6bf3fdf8e1e5fbb8c824ad519ac672e/Linux/libevdev/libevdev.h#L30).

I'm not sure if a MacOS version is high on your list of priorities, but in any case thanks for making this emulator. :+1: 😀

**Comment by SourMesen** [comment]
Thanks for the report!

Like you said, the filesystem thing is due to using an older compiler - it's a fairly recent addition to the C++ standard (and hasn't actually been formally released yet, I believe).  It'd probably be relatively simple to implement an macOS-specific solution for this - just need to reimplement the functions in FolderUtilities.cpp with whatever API is used on macOS.

The malloc issue is probably a case of trying to compile C code with a C++ compiler - though I'd normally expect malloc.h to be available either way. This is probably a very easy fix.

The libevdev bit is what is used for gamepad support in Linux - I would have expected this to compile, but clearly it doesn't.  I'm unsure how easy this would be to fix, though (although gamepad support could just be disabled until a solution is found)

Fixing these, or at least working around the issues, would probably only take a few hours, but the main problem is that I don't own a Mac (and never have..), which makes it hard for me to test this.  Taking a quick look, however, it looks like it's possible to run macOS in a VM nowadays?  If so, I might be able to fix this eventually, but it's probably not something I can get done anytime soon, unfortunately.

Beyond all this, there is also the fact that I've read that Mono's implementation of WinForms for macOS is relatively buggy - this means even if I were to solve all the C++ side issues, it might still not work properly due to Mono bugs.

**Comment by PinkLouie** [comment]
If Mesen will have a dmg file for MacOS in the future, why not .deb and .rpm for linux distribution? Or Snap Packages.

**Comment by SourMesen** [comment]
Since there isn't much I can do for this on my own, I'm closing the issue for now.
If possible, it'd be nice to support MacOS eventually, but like I said before, I don't have access to a Mac to develop/debug/test on.
