### ISSUE TITLE
Bug report Mesen 0.8.0

### ISSUE THREAD

**Issue by Ramon-Zarat** [SourMesen/Mesen#124]
Hi,

Thanks for the fantastic emulator! This is what I've found:

1- Pirate game "Mortal Kombat 3 (18p) (YH2001) [p1][U][!]" does not work
2- Pirate game " Mortal Kombat 4 (8p) [p1][U][!]" does not work
3- Multicart "2-in-1 - Aladdin + Lion King, The (Unl) [p1][!]" Only a green screen
4- Multicart "2-in-1 - Boogerman + Flintstones, The (Unl) [p1][!]" Crash CPU
5- Demo "Quantum disco brothers by wAMMA" Auto detect NTSC, but it's PAL. Glitches in first scrolling scene, even in PAL
6- Demo "Mind Control Trilogy Preview" CPU crash
7- Demo "ShortNes" Glitch in first scene ass wiggling
8- Demo intro "Fullscreen Madness" CPU crash
9- Demo invite "Deadline Console Invitro" Glitches
10- Demo invite "Turpasauna 2006 invitation" Grey screen
11- Demo wild game "Gradius_Existential_Remix" missing sprite in menu and space ship
12- Demo "High Hopes" minor glitches 
13- Demo "Retrocoders Demo for Y2Kode (PD)" boots up with message "You are using an emulator...". Don't know if there is a detection routine or if this message is hard coded, but EVERY emulators gets detected. Would be nice if Mesen was the first emulator to avoid detection!   
14- Keyboard shortcut "1" and "2" to insert coin in VS system games do not work. Must use emulator menu 

Many demos can't detect PAL and run in NTSC instead, "High hopes" for example. You can get most NES demo here: http://www.pouet.net/prodlist.php?platform%5B%5D=NES%2FFamicom&page=1 . Many multicarts do not work, but Mesen is the one that run the most!  I have 3 monitors setup and Mesen open on the monitor where I click the Mesen icon instead of opening on its last location.  Everything else works  perfectly!

**Comment by SourMesen** [comment]
Thanks for the report.

I'll take a look at them, but keep in mind that most demos that don't work in Mesen probably also do not work on actual hardware (e.g the Retrocoders Y2Kode demo is over 15 years old - it's very likely it actually doesn't work properly on hardware, either).  Unfortunately, I don't own any flash cart, so I'm unable to test their behavior on real hardware.

As for NTSC vs PAL, there is no way to detect this properly if the ROM does not set the proper values in the header. Mesen relies on a built-in database of games to correctly select this most of the time (because most ROM headers are not correct), but demos & the like are not in the database.

To insert coins, there is no predefined shortcut key.  But you can assign any key you want if you go in Options->Preferences->Shortcut Keys and assign keys to "VS Insert Coin 1/2".  I just tried assigning the keys "1" and "2" and it seems to be working fine?

**Comment by Ramon-Zarat** [comment]
Thanks for the reply,

All listed demos work one way or another in Punes and other emulators, but I understand what you are saying. In my opinion, demos in general are great to test emulators as they often use obscure coding that break emulators, but still work on real hardware  

"Retrocoders Y2Kode demo" is the only one not on Pouet, and it work perfectly fine in Mesen, except the emulator detection message. Also, most if not all demos on Pouet have been shown at Demo party using, AFAIK, actual hardware as using original hardware, as opposed to emulator, is required at most/all party. It's a shame you do not have something like an Everdrive NES cart! Available for ~$100.00 on e-bay. If 100 Mesen users would give $1 on a gofundme campaign, you'll get that cart for free! I certainly would contribute!  

I suspected the PAL/NTSC detection rely on ROM headers information. The same happen with every other emulator anyway.

Shortcut keys works great, thanks! I simply assumed the "1" and "2" in the menu was referring to keyboard key 1 and 2.

**Comment by SourMesen** [comment]
For your info, I've taken a look at some of these, and in all cases so far, it feels like the demo is the problem.

**6- Demo "Mind Control Trilogy Preview" CPU crash**
This demo (VRC6) expects the PRG/CHR banking to be set at bootup - typically there is no guarantee as to what banks are selected at startup, except for "fixed" banks. Mesen only maps the strict minimum (which allows all commercial games to boot).  It's not impossible that the banks may end up this way on a real cartridge, but that would be hard to test (it would require a real VRC6 board, a flash cart would not be good enough)

**8- Demo intro "Fullscreen Madness" CPU crash**
**10- Demo invite "Turpasauna 2006 invitation" Grey screen**
This is much like the mind control demo - they expect the mapper (MMC3 in this case) to have certain banks selected at bootup, but the mapper offers no such guarantee (the demos doesn't properly initialize the bootup state).  Again, testing this would be hard because you would need to run the ROM on a real MMC3 board.

**13- Demo "Retrocoders Demo for Y2Kode (PD)"**
This one is odd - but I don't believe Mesen is wrong.  The demo attempts to write values to CHR ROM, and it seems to expect it to work.  If I remove validations in Mesen that prevent games from writing to memory that is mapped to ROM chips, the demo boots without the "You are using an emulator" message.  Unless this was running on a custom-built cart that contained some weird kind of custom CHR RAM chip that allowed writes AND was somehow preinitialized at startup, this should not work on a real NES.

I could definitely modify Mesen to make these work (except the retrocoders demo) by ensuring the state of the bank selection the startup - but then that's the kind of thing that makes people develop games using emulators only to find out they don't work as you'd expect on real hardware.  Keeping Mesen the way it is now arguably forces developers into making sure they are properly initializing the mapper, instead of relying on arbitrary emulator bootup states that real hardware may or may not respect.

An Everdrive would be really nice for some things - but anything other than mapper 0 roms cannot reliably tested on flash carts, either (since they emulate mapper logic, much like an emulator does).
There is a paypal donate button available, but I've only received roughly 30$ since I added it, ~4 months ago. It will probably be enough to pay the yearly hosting costs on mesen.ca, which was the main goal, but it's not really enough to pay for anything else.  I could buy these things myself, but I already spend so much time on Mesen (probably literally a thousand hours by now!) that I'd prefer to not spend money on it, too!

**Comment by PinkLouie** [comment]
Hi Sour, do you know Patreon? (https://www.patreon.com/) It would be nice to have. You could use a bot to publish every new mesen release on Twitter,  maybe Tacebook too, to notify the users. The project's twitter page, is empty by now (is it official?) (https://twitter.com/MesenEmulator). I think social media can help you get some money.

**Comment by SourMesen** [comment]
I'm aware of Patreon, but Patreon is a system where you are supposed to have rewards for the money people give.  I don't want to have the additional responsibility of meeting goals in exchange for the money - I already have a day job, and I don't need a second one :)

That Twitter account is mine - but I only created it to avoid having someone else use it.  I don't really have any plans to use Facebook/Twitter.  At the end of the day, Mesen is just a hobby for me, I'm not trying to sell a product.

**Comment by SourMesen** [comment]
I've merged all unlicensed games issues into #128 to keep track of them more easily.
Thanks a lot for taking the time to test these - if you find any more, please report them in #128 
I've also taken a note about the multi-monitor issue you mentioned, I'll see what I can do about it for the next release.
