### ISSUE TITLE
Speed up fix for pal games

### ISSUE THREAD

**Issue by PinkLouie** [SourMesen/Mesen#127]
Cause PAL games are slower, is it possible to add a fix to make they run at the same speed as NTSC games?

**Comment by SourMesen** [comment]
If the gameplay feels slow because of a bad PAL port, I'd suggest playing the NTSC version.
If the game only exists in the PAL region, then its controls/sound are tuned for the PAL speeds, and I don't really see why you would want to play them any faster?

**Comment by PinkLouie** [comment]
There are games launched in Japan and Europe, but not in the USA. Play a game in japanese or korean is not for everyone... You can't read too much. Other thing is... A lot of people do not speak english, and europen games usually have languages other than english, like spanish, freanch, germany, portuguese, and even dutch. Play a game in the right speed with a language you understand, seems nice, maybe a question of accessibility.

**Comment by SourMesen** [comment]
The only thing I could do would be to run the emulation at 60fps instead of 50fps.
But if I do that, the music's tempo will be 20% faster than normal (but it's possible to keep the same pitch)  In-game stuff like timers to finish a level would also go 20% faster, too.
Is that worth it?  I feel like having 20% faster music might be annoying?

**Comment by PinkLouie** [comment]
You have a good point.

**Comment by SourMesen** [comment]
Closing this since there isn't really any good solution.
