### ISSUE TITLE
Adventures of Lex & Grim, The (PD)

### ISSUE THREAD

**Issue by Cibomatto2002** [SourMesen/Mesen#137]
Game will not load in Mesen but will load in other emulators. 
[Adventures of Lex & Grim, The (PD).zip](https://github.com/SourMesen/Mesen/files/923413/Adventures.of.Lex.Grim.The.PD.zip)

Loading rom: Adventures of Lex & Grim, The (PD).nes
File CRC32: 0x01397C5D
PRG+CHR CRC32: 0x5D4CAC4B
[iNes] Mapper: 4 Sub:0
[iNes] PRG ROM: 32 KB
[iNes] CHR ROM: 16 KB
[iNes] Mirroring: Horizontal
[iNes] Battery: No

**Comment by SourMesen** [comment]
This looks like it was never tested on real hardware.  It doesn't properly initialize a lot of things, and even if I change a lot of code to make it "work", it still looks extremely broken.  On other emulators, it does display the start screen, but the game freezes right away once gameplay begins (because of another bug in the game's code).  I added it to the list of broken demos/homebrew games in #128.

**Comment by Cibomatto2002** [comment]
I never did try playing it on other emulators I jut seen that it had a title screen. I'm not into PD roms really but I did find one game that was good Twin-Dragons. http://nintendoage.com/forum/messageview.cfm?catid=22&threadid=169653
