### ISSUE TITLE
Feature Request: Stream Friendly options

### ISSUE THREAD

**Issue by Koh1fds** [SourMesen/Mesen#142]
1. It would be great to have an option to hide menu (File, Game, ... etc) for easier window capture.
http://i.imgur.com/GSjgPlF.png

2. It would be great to see what resolution drawing area have with current settings. Like when you choose some crazy aspect ratio - it's hard to calculate drawing area of the window for proper capture.

3. Is it possible to make special exact 60 fps mode? Like when you select that "60 fps" mode - emulator starts running at exact 60 fps instead of 60.1 And so you don't have to deal with frame drops or giant vsync lag.

I'm sorry if some of those options already implemented. I can't find them.

**Comment by SourMesen** [comment]
There should all be fairly easy to implement - I'll try to get them into the next release.

**Comment by SourMesen** [comment]
I added an option to auto-hide the menu in windowed mode like it always does in fullscreen mode and an option to display more info in the title bar (exact size, scale, aspect ratio, filter) (c9c7c626efeea77e5503e3e6fc8c1717ca1939e6)
Also added a shortcut key to run a single frame (what you asked on TasVideos) - you can bind it in Preferences->Shortcut Keys (99ce88a193b1464d2fb1bba1ff110f030c095da1)

A 60.0/50.0fps more is a bit more complex than I initially thought, though.  It involves altering the sound resampling code to compensate for the missing 0.1 fps + has interactions with the overclocking options, etc, so I haven't done anything for this yet (and might have to give up on doing it at all if it turns out to be too troublesome to implement)

**Comment by SourMesen** [comment]
Closing this for now since most of it was implemented - I added the 60 FPS request to my (endless) todo list, so I might try to implement it later on.

**Comment by SourMesen** [comment]
For your info, ef63dfa8163bd41a195f06d9de31ed44164bbbdb adds a 60.0/50.0 fps mode
