### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by daan1575** [SourMesen/Mesen#143]
every time i open Mesen I have to configure the input for the controlls again
but it depents sometimes it will just work for days en then sudenly i have to reconfigure the input for the controlls

**Comment by SourMesen** [comment]
Do you mean that the input settings are lost after you get a crash? (Since your bug's title is "crash")
Are you getting any crashes at all?

Do the settings inside Mesen change? (I mean the text values displayed in the key bindings) Or do they stay the same as you had configured them, and they just don't work anymore?
Are you using a gamepad?  Do you have multiple gamepads that you tend to plug/unplug?

**Comment by SourMesen** [comment]
Would need more information to be able to investigate this - closing for now.
