### ISSUE TITLE
Feature Request: Wav Recording icon or message "Wav recording stop"

### ISSUE THREAD

**Issue by Koh1fds** [SourMesen/Mesen#150]
When you play nsf and try to record wav it still likes to stop wav recording without any reason. So it would be pretty cool to have something to easily know that recording still going. What i did:
1. Opened nsf that contains only one track.
2. Pressed pause button.
3. Pressed back button to start from begging of the track
4. Pressed Tools -> Sound recorder -> Record...
5. Pressed play button.
6. Waited 10 minutes to have 10 minutes wav without checking recording status. NOTHING WAS RECORDED!!! When i go to menu "Sound recorder" after 10 minutes there is no "Stop" button, only Record.... Pretty annoying :C

**Comment by SourMesen** [comment]
Is this something you can actually reproduce? I can't get it to stop the recording, even using the exact same steps you gave, with a single-track NSF file.  The only way I'm able to make the sound recording stop is by using the Reset button or switching NSF file.

Also, you can record NSF files to WAV much faster than real time if you set the emulator to max speed (Options->Speed->Maximum Speed - pressing F9 in the NSF player doesn't work due to a small bug I just noticed).  This should let you record 10 mins worth of audio much faster (e.g probably in 2-3 mins, depending on your computer), and the recorded WAV file will still play at normal speed.

**Comment by Koh1fds** [comment]
This is the problem that this happens randomly and i didn't managed to catch exact cause of it. Maybe because i opened some roms before loading nsf. Also one time i try to record video and both Sound and Video recorder options was unclickable (gray). After restart of emulator everything was fine. And i can't reproduce that.
Everything i can certainly say that i didn't hit reset or something else than "Pause/Play" button after starting Wav recording.

**Comment by SourMesen** [comment]
I added a "REC" icon to the NSF player (along with Fast Forward/Slow Motion icons) + a couple of UI bug fixes (4e6a063c65623c9261019b5c0b2f90678d09a62c). I haven't been able to find any way to reproduce the bugs you found, though.
