### ISSUE TITLE
Problem with source code in Visual Studio 2015 on GitHub

### ISSUE THREAD

**Issue by owomomo** [SourMesen/Mesen#163]
I compiled the source code of version 0.9.0 on Github, the generated mesen.exe can execute on Windows 10, but can't run in Windows 7 which never runs Mesen before, it shows error "Mesen could not launch because it was unable to load MesenCore.dll due to missing dependencies." But if you open the mesen folder, you can see the file is already there.

However, I downloaded the emulator from official site, and it can successfully execute on Windows 7, which behaves different from the source code.

Is there any differences between the code on Github, or I have some mistake on my project settings?

**Comment by SourMesen** [comment]
This is because the Debug/Release build configurations are set to dynamically link the C++ runtime (mostly because it's not a problem on my end and I haven't taken the time to change it).
Your Windows 7 computer most likely does not have the VS2015 C++ runtime installed, which is why it fails and says there are missing dependencies.

The official releases are not built using the Release config (they use the PGO Profile/Optimize configurations) - the simplest solution on your end would probably be to change the Release build to statically link the C++ runtime instead.

**Comment by SourMesen** [comment]
I've changed it so that all build configs statically link the C++ runtime (301fa31c44c007b2e40e741616e223c35880c786).
This should fix the problem you were getting on the Win7 computer.
