### ISSUE TITLE
ASO - Armored Scrum Object (Japan)

### ISSUE THREAD

**Issue by Cibomatto2002** [SourMesen/Mesen#164]
When playing ASO - Armored Scrum Object (Japan) the score flickers it also does this in FCEUX so i'm not sure if it's a bug or not I found a video where it's not doing it.

https://www.youtube.com/watch?v=kBMhDFOYerk&spfreload=10

Then i found another video of it flickering.

https://www.youtube.com/watch?v=FIVvX6hyF4k&spfreload=10

**Comment by Koh1fds** [comment]
NES outputs video at 60.1 fps per second (for simplicity). That score flickers every frame. So it's like this:
Frame 1 - score
Frame 2 - no score
Frame 3 - score
Frame 4 - no score
Back in the days youtube support only 30 fps videos at max. So first video have exact 30 fps. So it trows away ~half of the frames. So it looks like this:
Frame 1 - score
Frame 2 - no score  - this frame skipped
Frame 3 - score
Frame 4 - no score - this frame skipped
So it looks like score doesn't flick. But nes have not exact 60 fps, so actually score appears and reapers because, frames get's shifted by the time. Also lag can shift frames.
And the second video have like 25 fps or something.

**Comment by Cibomatto2002** [comment]
Thanks for clearing that up I had no idea it is was a bug or not. That was the first game I seen to do that.
