### ISSUE TITLE
Some PAL games are being opened by Mesen as NTSC

### ISSUE THREAD

**Issue by PinkLouie** [SourMesen/Mesen#170]
The following games are PAL but, Mesen open as NTSC, and this cause problems.

Pirates! (Germany)
25th Anniversary Super Mario Bros. (Europe) (Promo, Virtual Console)
Noah's Ark (Europe)
Super Mario Bros. 3 (Europe) (Wii Virtual Console)
Tiger-Heli (Europe) (Rev A)
Captain America and the Avengers (Australia)
Miracle Piano Teaching System, The (Germany)
Predator (Australia)
Star Trek - 25th Anniversary (Germany)
Snowboard Challenge (Europe) - also have a white upper bar. From console, the white bar does not exist. https://www.youtube.com/watch?v=ddZtrFOMTz8 . Same happens with it's USA version, Heavy Shreddin'

Gremlins 2 - The New Batch (Europe) (Beta)
Parodius (Europe) (Beta)
Ultimate Air Combat (Europe) (En,Fr,De) (Beta)

Alfombra Magica, La (Spain) (Rev 1) (Gluk Video)
Alfombra Magica, La (Spain) (Gluk Video) (Unl)
Bloque Magico, El (Spain) (Gluk Video) (Unl)
Creatom (Spain) (Gluk Video) (Unl)
Duck Maze (Australia) (Unl)
F15 City War (Spain) (Gluk Video) (Unl)
Gran Aventura Submarina, La (Spain) (Gluk Video) (Unl)
Jackpot (Australia) (Unl)
Little Red Hood (Australia) (Unl)
Monstruo de los Globos, El (Spain) (Rev 1) (Gluk Video) (Unl)
Pipemania (Australia) (HES) (Unl)
Policeman (Spain) (Gluk Video) (Unl)
Puzzle (Spain) (Gluk Video) (Unl)
Sidewinder (Australia) (Unl)
Tanque (Spain) (Gluk Video) (Unl)
Micro Machines (Europe) (Unl) - Race do not starts neither in Pal Nor NTSC

Most games tagged as (Asia) and (Pal) at the same time, are opened as NTSC, but as (Asia) is not a official region, and the tags from No-Intro can ben wrong, who knows. If you need, I can post them.

**Comment by SourMesen** [comment]
The majority of PAL games are not set as PAL in their header - so any PAL game that is not in the database will load up as NTSC by default. There are most likely a ton more of roms that have the same issue. There is no real way to detect a PAL rom if the header is incorrect (some emulators check the filename for (E), etc.). So the only way to fix these is adding them to the database manually, which is very time consuming on my end, and prevents me from working on more useful features/bug fixes.  Since it can easily be fixed by the user manually selecting the region (which is why the region options exists in the first place), I don't really consider this a bug.

Snowboard Challenge (Europe) keeps the "intensify blue color" option enabled at the top of the screen, so this is "normal".  The "intensify color" emulation isn't very accurate (having an accurate representation of it is complex) - if you look at other emulators, you'll see that all of them have the same bar, too.  It's very hard to see, but visible in this video too: https://www.youtube.com/watch?v=5IOJESmOy40

Micro Machines (Europe) (Unl) appears to freeze on every single emulator I have tried.  It's unclear whether there is even a Europe version of this game? I can't find any information on it, and NesCartDB only lists 2 versions of the game, neither of which match this ROM: http://bootgod.dyndns.org:7777/search.php?keywords=micro&kwtype=game

**Comment by PinkLouie** [comment]
I tried all No-Intro PAL roms, which are about 400, and these are the only ones with problems. There is no missing rom in the list. But I really understand you. It should take time, so, it's not a priority.

**Comment by SourMesen** [comment]
I've set all games that contain (Australia), (Europe), (Germany) or (Spain) (in addition to (E) which was already used) to load up as PAL automatically (even if they are not in the DB) (69c2b784a45061e61dd67ad4ce2e5ae70ef79865)
This should fix all the games you listed above.

**Comment by PinkLouie** [comment]
If you want to go further you can also add the following tags: (France), (Italy), (Russia), (Sweden), and (Pal). Except for (Pal) I haven't found problem in any game with this tags, but, who knows in the future, or other people/roms.

**Comment by SourMesen** [comment]
I'll keep it as-is for now - there are a lot of GoodTools abbreviations and they're all short, so they could end up running games as PAL by mistake, which isn't any better, too.
