### ISSUE TITLE
Archlinux AUR package

### ISSUE THREAD

**Issue by shaggytwodope** [SourMesen/Mesen#172]
Hello, I've added mesen to Archlinux's AUR [here](https://aur.archlinux.org/packages/mesen). Not sure if you'd welcome adding it to the readme. But you are most welcome if you choose to. 

Side note, see anything you'd like modified in the packaging let me know. Feel free to close this as it is not actually an issue. But I find PR's for this to be a bit silly if it is not welcomed by the author.

**Comment by SourMesen** [comment]
Hey, thanks for that - I've been meaning to look into what is needed to create packages for Linux distros, but hadn't had the chance to do so yet.
I'm not familiar with Archlinux (or anything other than Ubuntu really - I don't use Linux much), though I've heard the name a lot.
As far as I can tell, this seems to download the source code, compile it using the makefile, and copy the binary to /opt/Mesen?
Is /opt/ writable for all users, or just admins, typically?
If just admins, I'm assuming that's why you're manually copying libMesenCore there?
In that case, Mesen's auto-update will probably fail - but that's probably a lot better than downloading the official Windows/Linux build (which most likely doesn't run on ArchLinux at all) and breaking the installation completely.

Other than that, would mentioning ArchLinux & linking to https://aur.archlinux.org/packages/mesen be good enough for the readme?

**Comment by shaggytwodope** [comment]
So with mono packages it's a bit tricky. As far as I can tell packaging to /opt is the ideal means. Not sure if anything else can be done for auto update feature. Some software solves this by makes it a feature that can be disabled at compile time for example firefox (or it used to, but you get the idea lol).

The PKGBUILD for the AUR is a standardized bash file of sorts. Grabs the source for the tagged release file and compiles and places the files in `/opt/Mesen` and a simple bash file that runs it goes in `/bin` along with a simple `.desktop` file I made so it's available in menu's for xfce, gnome etc. `/opt` can be made writable via permissions... but really best left to package managers cause it can get messy.

I've been able to install and run on all my arch boxes with no issue. And would love to create a ppa package should you wish.  As far as readme, you can say something like "Packages are available on" and link to the aur. Most users should be able to catch on and install no worries.

If there are ever any major changes to paths or names when a release is tagged let me know. I'll see what can be done with regards to auto update feature when I get time later this week. And come thursday or so I'll have time to begin a ppa/debian pacakge if you'd like.

**Comment by SourMesen** [comment]
I've added a constant to disable auto updates, DISABLEAUTOUPDATE - it's enabled by default in the Linux makefile - so that should take care of that.

A PPA is a precompiled binary package for Ubuntu, right? (i.e installed via apt-get)
Debian packages can be installed on a few different distros, but wouldn't they potentially need to be recompiled for each different distribution?

**Comment by shaggytwodope** [comment]
The feature to disable autoupdates is great, when you can tag a new release I'll update asap. (It's idea to use releases and not patch manually)

So a ppa would be precompiled .deb packages that a user can add with some simple commands. In the process it adds a "debian repo" using launchpad/ubuntu's services. And provide automatic updates from then on. Packaging for debian... that gets a bit trickier. What some people do is provide a .deb file targeting a specific debian version. Normally sid the unstable branch. Creating your own debian repo is easy and tricky. For now however I'd like to work on a ppa later this week.  

If you want you can take a look at an example for one project I package a for a few distros on.
https://github.com/odeke-em/drive/blob/master/platform_packages.md

**Comment by PinkLouie** [comment]
Instead of deb, and rpm, and other packages why no create a snap package? As far as I know snap packages can be installed in various and main distributions and are easy to use. Can be used in Ubuntu, Arch, Fedora, OpenSuse, etc. Seems good. 

https://snapcraft.io/

**Comment by SourMesen** [comment]
Closing this - the link to the archlinux packages has been in the readme. Let me know if you need anything else.
