### ISSUE TITLE
VS. System bugs

### ISSUE THREAD

**Issue by PinkLouie** [SourMesen/Mesen#173]
First, I would like to suggest that Mesen opens "game configuration" pop up automatically when you open a VS rom.

I like to use Sony CXA palette, because the colours are really better. But, the palette colours are not affecting VS roms. I also think it's a good idea to have Virtual Console colour palette available. I would like to add coins using a physical button. When I click "Power Off" I get a green lower bar. Some game are slow to load. Some games do not work in Mesen, but they work in other emulator. I tried them in Nintaco, a nes emulator, developed in java, that supports VS. 

Balloon Fight (VS) [!] - Green Screen
Baseball (VS) [b1] - Blue Screen
Mahjong (VS) [!] - Green Screen
Super Xevious - Gump no Nazo (VS) - Grey Screen - Works in Nintaco
Tennis (VS) [!] - Green Screen
VS. TKO Boxing (VS) [!] - Black Scren - Works in Nintaco
Wrecking Crew (VS) [!]

![2017-05-22 1](https://cloud.githubusercontent.com/assets/24971871/26294460/43862540-3e9a-11e7-8152-844785a5c00c.png)
![2017-05-22 3](https://cloud.githubusercontent.com/assets/24971871/26294456/3db4d27e-3e9a-11e7-9fee-7145842b8340.png)
![2017-05-22](https://cloud.githubusercontent.com/assets/24971871/26294457/3f4a3e4e-3e9a-11e7-9b9a-6a8c24a2fba0.png)

**Comment by SourMesen** [comment]
>I would like to add coins using a physical button

You can do this already in the shortcut keys tab.

>Balloon Fight (VS) [!] - Green Screen
Baseball (VS) [b1] - Blue Screen
Mahjong (VS) [!] - Green Screen
Tennis (VS) [!] - Green Screen
Wrecking Crew (VS) [!]

These are VS Dualsystem games, which are not supported (and will most likely never be supported)
(Also, roms with [b] or [b1], etc. in their name are known bad roms)

>Super Xevious - Gump no Nazo (VS) - Grey Screen - Works in Nintaco
VS. TKO Boxing (VS) [!] - Black Scren - Works in Nintaco

These both work on my end, you're either using a different ROM, or you changed the configuration in such a way that would cause them to freeze?

>Some game are slow to load. 

This is because the games do self-checks before starting up - this is part of their code and will happen on any emulator or hardware.

**Comment by PinkLouie** [comment]
When you try to open a game with an unsupported mapper you receive a message in Mesen about it. Mesen could do the same with Vs Dualsystem. The CRC32s for the roms are A06E381F for VS. TKO Boxing (VS) [!] and D1ADD836 for Super Xevious. They are from Goodset. I deleted all Mesen files, and the games still do not work. But if it work on your end, shouldn't be a problem in Mesen. Thank you for the explanations.

**Comment by SourMesen** [comment]
You had alternate versions of TKO Boxing/Xevious (different CRC), which is why they did not work (fixed by 2f3f698fd140eb4dffb9692ceed0c9c690d7a0c5)
0e5e39dc38237b132cd77d7b78241e1d1562dfc6 fixes the color visible at the bottom of the window after stopping a VS system rom
ec63fb6f04e90ff592ea2f3804f763015eecef5f adds an option to use the custom palette for VS System games.  Otherwise, it will use the built-in original RGB palettes for those systems (specific games have specific palettes based on the PPU model they use)
ec244e7f4185770026809a035b7448af399a3a03 adds an option to popup the configuration dialog on load & hard reset.
