### ISSUE TITLE
Mesen new options / settings suggestion

### ISSUE THREAD

**Issue by RetroGameIntros** [SourMesen/Mesen#174]
Add "Timing options" with choosable options or their alternatives:

Synchronize to refresh rate / Auto frame skip

VSync / triple buffering

Use high-precision timer

----------------

Add option to allow multiple application instances and confirm reset (power off)

**Comment by SourMesen** [comment]
Is there any particular reason you are requesting these features? I'm asking because I don't exactly want to add features just for the sake of features, if they don't bring some tangible benefit to users (otherwise I'll end up bloating the UI with a bunch of technical options that most people don't really have a use for)

>Use high-precision timer

Mesen always uses this, and I don't really see any reason not to do so?

>Synchronize to refresh rate / Auto frame skip

The synchronization is based on the timers Mesen uses - it is not based on nor affected by the display's refresh rate - the NES is 60.1hz, most PC monitors are not, so the emulation can't be based on the display's arbitrary refresh rate.
Frame skipping isn't really feasible on a NES - rendering each frame is necessary to have accurate emulation.  The display thread will automatically drop the extra frames that the NES generates, assuming your display has a refresh rate lower than 60.1hz

>VSync / triple buffering

There is a vertical sync option.  There isn't a triple buffering option, but I don't really see what having one would offer?

>Add option to allow multiple application instances

This is already available, in the preferences

>and confirm reset (power off)

Do you want to confirm reset, or power off, or both?
Confirming power off or closing the emulator doesn't really offer anything since the game selection screen I added in 0.9.0 will allow you to resume where you left off, if you did it by mistake.

**Comment by RetroGameIntros** [comment]
Thanks for explanations, well actual option for me is to add only "confirm reset". Other no need, after you all explained to me about those options (they all from Nestopia)

**Comment by Cibomatto2002** [comment]
I was looking at bsnes-plus and it has Sync Video, Sync Audio is that any better than vertical sync?

**Comment by SourMesen** [comment]
I'm fairly sure those aren't related (nor similar) to vertical sync.
They're probably to choose whether you want to sync the audio to the video, or vice versa.

**Comment by SourMesen** [comment]
This is resolved by 97c9fb88dd3750b6edf48b2c13a82c9628f20704 which adds an option to force a confirmation dialog to display before reset/power off/exit.
