### ISSUE TITLE
Famicom Jump II - Saikyou no 7 Nin (Japan) crashs, but only in the first time.

### ISSUE THREAD

**Issue by PinkLouie** [SourMesen/Mesen#181]
This game crashes, but when you try to open it again, it just works. I deleted Mesen temporary files, saves, saves states, this kind of things, and then, it happened again, so it's reproducible.

Also noticed, in Mesen black screen, after deleted temporary game files, a square flashing. It's quiet weird. I'm sending you a video showing it.

[Mesen 26_05_2017 01_33_29.zip](https://github.com/SourMesen/Mesen/files/1030829/Mesen.26_05_2017.01_33_29.zip)

**Comment by SourMesen** [comment]
The game crashing is a game bug - it's related to the RAM initialization value again.  If you set it to All 1s before running the game, it won't crash.

The flashing square is the empty game selection screen (since you didn't load any game since deleting your config, it's supposed to be invisible) - it should be fixed.
