### ISSUE TITLE
Just Breed - Incorrect NSF output

### ISSUE THREAD

**Issue by QuantumSoundings** [SourMesen/Mesen#182]
Hello SourMesen! I'm a big fan of your work and often use mesen as a reference for correct behavior in my own emulator. But today I came across incorrect sound output in the nsf of Just Breed. I'm attaching audio samples from my emulator, [nsfplay](http://rainwarrior.ca/projects/nsfplay/index.html) and mesen 0.9.0. Just Breed is MMC5 btw.

[Mesen](https://filebin.ca/3NpBipqemvCd/mesen-justbreed.wav)
[My Nes](https://filebin.ca/3NpC3RRcjkdn/mynes-justbreed.wav)
[nsfplay](https://filebin.ca/3NpCIQbbFDYB/nsfplay-justbreed.wav)

**Comment by SourMesen** [comment]
Hey, happy to hear the code is useful to you!  And thanks for letting me know about the bug.
Turned out to be a silly mistake in the emulation of the MMC5 multiplication register (only for NSFs, which is probably why the actual game's audio worked correctly).
This is fixed by c15a07476fd69b6dbcb98bf8964fd857f1e2a01c
