### ISSUE TITLE
Suggestion: Better Default Sound Mixing

### ISSUE THREAD

**Issue by Koh1fds** [SourMesen/Mesen#186]
I know - mesen have insane tools and tweaks for sound and it will be pretty rude to ask, but can you please improve default sound channel mixing? I recorded one of the tracks from that game called Recca from my av famicom. I also used old, but decent Infrasonic Quartet sound card for record - not simple mother board line input. No equalizer tweaks or anything. So it should be pretty decent. If you compare closely to the record from Mesen - you can hear that record from av famicom are much more "cleaner" and "sharp". I also think that Mesen has to loud triangle channel at default settings. I also put records from other emulators for comparison. I think it would be cool to have default mixing close "to real console". Sorry

https://www.dropbox.com/s/mio1k6v689z2lkg/Recca%20Sound%20Comparison.zip?dl=0

**Comment by SourMesen** [comment]
The relative volume of channels should be pretty accurate - it follows the information shown here: http://wiki.nesdev.com/w/index.php/APU_Mixer and passes blargg's apu_mixer tests that use 1 channel to cancel out another channel, which requires relatively accurate mixing (on top of timing).
Although, Mesen uses the lookup table method, I guess I could try using the longer formula itself, but it's unlikely to result in any big difference, I think.

For the AV Famicom vs Mesen - each different NES/Famicom model sounds a bit different.
I had a long discussion about this with nothingtosay in the NesDev thread: http://forums.nesdev.com/viewtopic.php?p=191907#p191907
I'm still waiting for nothingtosay to send me some EQ numbers so that I can add presets to Mesen (e.g AV Famicom preset, Famicom preset, NTSC NES preset, etc.).  The default will still stay as it is right now though - the current output is directly what blargg's blip_buf resampling library outputs, without any filtering done.
