### ISSUE TITLE
"Remove sprite limit" causes bug in Felix the Cat

### ISSUE THREAD

**Issue by anewuser** [SourMesen/Mesen#188]
Felix's sprite is on the top of the magic bag sprite when he enters it if the `Remove sprite limit` option is on. If such bugs are expected, you should add a warning next to the option.

[mmo](https://github.com/SourMesen/Mesen/files/1056332/mmo.video.Felix.the.Cat.Europe.zip)
[rgd](https://github.com/SourMesen/Mesen/files/1056405/Felix.the.Cat.USA.zip)

Felix the Cat (Europe)
Felix the Cat (USA)
Mesen 0.9.0
Windows 10

**Comment by SourMesen** [comment]
Thanks for the report.
In general, all options that are in "Advanced" tabs can have side-effects on the emulation and may or may not cause problems (that's why they are "advanced" options).  You should get a similar result in other emulators that have a similar option if you enable it.
The options that can cause problems and have little or no benefit do have a "(not recommended)" tag next to them.
Some of the more useful ones and/or with few side-effects do not.  In "Remove sprite limit"'s case, it can't break any games, but it can cause temporary graphical glitches such as the one you described in a small portion of games because of how they work.

**Comment by anewuser** [comment]
I just tested it on FCEUX with the equivalent option turned on, and it does have the same effect. I did test it on another emulator (Nestopia) to make sure it wasn't like that by design, but before using a clean copy of Mesen to figure out what option was causing the problem.

Since it only affects a small portions of games, do you plan on creating workarounds for problems caused by that option?

**Comment by SourMesen** [comment]
Basically, what's happening in these games is that the game is voluntarily adding a bunch of empty sprites on the screen, to make it go over the sprite limit and hide other sprites.  e.g if you add a bunch of sprites before the felix sprite (on the same line), then you go over the 8-sprites-per-line limit and felix becomes hidden.  I'm unsure why games do this instead of just.. hiding the actual sprites. :)

It might be possible to try and detect some very obvious cases (for example, both Felix and Zelda 1 appear to stack 8 empty sprites at the exact same x,y position - so this is relatively easy to detect), but it would probably be impossible to reliably detect every game that abuses something like this to hide sprites on purpose.

**Comment by anewuser** [comment]
By "workarounds" I actually just meant to hardcode a list of games for which the sprite limiter would be disabled even if that option is checked,  but since you even thought of a way to do that programmatically, I'll leave it to you to decide what to do about this issue.

**Comment by SourMesen** [comment]
Added a new option to detect this behavior in my (most) games (d05d66507c0607c105a23403ce9f161ae818464c) - it's most likely not perfect but should work in the majority of cases.
