### ISSUE TITLE
Zapper's pointer stuck in Mesen's screen.

### ISSUE THREAD

**Issue by PinkLouie** [SourMesen/Mesen#191]
First open some games that use the zapper; the cross will show automatically in screen. Then drag and drop some game that do not use the zapper. You will see, the zapper pointer/cross do not disappear, it got "stuck" in the screen.

**Comment by SourMesen** [comment]
The last game that you are dragging into the window is probably not a game in the game database, and because of that, the input devices are left unchanged (since Mesen can't know what the game needs).  Since you were just playing a game that used the zapper, it keeps using the zapper - if you open the input settings, you most likely have a zapper connected.

**Comment by SourMesen** [comment]
Closing this for now, if what I said was correct, this is working as expected.
