### ISSUE TITLE
Debugger: Frame Advance behaves erratically

### ISSUE THREAD

**Issue by alyosha-tas** [SourMesen/Mesen#194]
I'm not really sure what it's doing, but it seems to be stopping at random points in a frame occasionally. I've seen it advance barely a single scanline, and sometimes it takes several 'frame advances' to actually advance a frame.

Tested with Streemerz.

**Comment by SourMesen** [comment]
Are you talking about the shortcut key mapping?  If so, that might not actually work properly with the debugger (the debugger prevents pausing the game, which the frame advance shortcut relies on), I'll have to take a look.  If you have the debugger opened, you'd be better off using the "Run one frame" (F8) option in the debugger itself

**Comment by alyosha-tas** [comment]
I am talking about the 'run one frame' option in the debugger. 

Initially it seems to work fine, but watch 'cycle' in the middle of the debugger window, you will see it slowly decrement by 1 every time you hit F8. When it gets around 0, it goes haywire.

**Comment by SourMesen** [comment]
Do you have the "Break on unofficial opcodes" option enabled? If so, that would explain it since Streemerz does make use of them, so it'll break on unofficial opcodes, whether or not a full frame was run

**Comment by alyosha-tas** [comment]
I did have the option on, but I just tried it with it off and nothing changed. This happens within the first 100 frames of powering on the game, and it stops at random, normal instructions (like STA $54)

**Comment by SourMesen** [comment]
From power on, it first breaks at cycle 30, scanline 0, then keeps going back 0 or 1 cycle per frame executed. Doing this, I was able to go through those 30 cycles, back to scanline -1, and then all the way back to scanline 260 (so ~750 frames or so) one frame at a time by holding down the F8 key..
Just to be sure, you don't have any breakpoint active at all?  If this isn't it either, could you attach you settings.xml & Debugger\streemerz.Workspace.xml files from Mesen's folder, they might help me reproduce the issue.

As is, from a code perspective, the only thing I can see would be that it would be possible for the debugger to not break properly if the keyboard's key repeat rate was faster than the time it took for a frame to run (unless you have the emulation speed set to like < 10%, making each frame 150+ms, this is unlikely to happen, though)

**Comment by alyosha-tas** [comment]
https://www.dropbox.com/s/xw7695xpzehsa84/settings.xml?dl=0

https://www.dropbox.com/s/cdunngfoz96y3gy/streemerz-v02.Workspace.xml?dl=0

The breakpoints window is empty, and I'm pretty sure I haven't changed any settings, hope it's something minor.

**Comment by SourMesen** [comment]
Seems to be working properly on my end with your settings..  One more thing I thought about is that it will only work properly for NTSC mode (because the frame skip is implemented as a hardcoded number of PPU cycles to wait before breaking, chosen based on NTSC timings).  Also, adding scanlines before/after NMI via the overclocking options would also cause the same kind of problem.
I'm guessing neither of these are true in your case though?

**Comment by alyosha-tas** [comment]
I tried deleting everything Mesen related and re-installed, now it at least doesn't jump all over the place.
I'll try to keep track of anything I change to see if it happens again.

The 'scanline' that a frame breaks on still seems to drift though, is there a way to always make it break at a frame boundary? Like on VBlank set or clear?

**Comment by SourMesen** [comment]
Weird that deleting everything solved the issue - let me know if you figure out what was causing it.

The scanline/cycle drift because the option causes a break after 89341 ppu cycles (e.g the number of cycles in an odd frame), so it drifts 1 cycle back every 2 frames.  I'll see about changing that so that it always breaks on the same cycle/scanline every time.

To break on vblank set, you could always use conditional breakpoints - set it to break on Read/Write/Exec cycles for the CPU, "Any" memory address, and then use a condition like "scanline == 240 && cycle <= 2" to break at the start of the specified scanline.  You can do the same to break when the flag is cleared.  This only gives you CPU-cycle level precision, though.  e.g, something like this:
![image](https://user-images.githubusercontent.com/21093973/27357861-ef67662c-55e1-11e7-8cbb-2182b6baa773.png)

**Comment by alyosha-tas** [comment]
Thanks that is quite helpful.

I guess I'll close this issue since I cannot reproduce it. The only thing I know is that when it was having problems, the cycle decremented every frame instead of every other frame. Beyond that I have no idea.
