### ISSUE TITLE
Extended game colour to letterbox

### ISSUE THREAD

**Issue by ghost** [SourMesen/Mesen#195]
I've noticed SMSHawk, from BizHawk, do not use simple black bar at the sides. I think it's nice because it makes a better use of wide screens, and improves the sensation of immersion. The color of letterbox should be based, I think, in the most used colour in the actual image, and should also be affected by scan lines.

Some example below:

![2017-06-24 2](https://user-images.githubusercontent.com/24971871/27510926-27eefe1c-58f1-11e7-8041-c8adecdbe539.png)
![2017-06-24 4](https://user-images.githubusercontent.com/24971871/27510928-28020066-58f1-11e7-9c42-5069561f1a34.png)
![2017-06-24 5](https://user-images.githubusercontent.com/24971871/27510927-2800645e-58f1-11e7-97b6-01c684b4c0c4.png)
![2017-06-24](https://user-images.githubusercontent.com/24971871/27510930-28033eb8-58f1-11e7-9e7f-c86d101d87d0.png)
![2017-06-24 3](https://user-images.githubusercontent.com/24971871/27510929-2802e8e6-58f1-11e7-9dfe-7e19db79e16e.png)
![image](https://user-images.githubusercontent.com/24971871/27510953-a9a11328-58f1-11e7-96d5-8d642f94f3b0.png)

As you can see, SMSHawk do not affects letterbox by scanlines, but if it does, would be... perfect.

**Comment by Cibomatto2002** [comment]
If I was going to look at black bars on my screen I would rather look at something like this
![puckman](https://user-images.githubusercontent.com/21169038/28779064-70aac738-75c7-11e7-8e46-69f57e21ae31.png)


It would be a nice feature if we could load a wallpaper to fill in the black bars.

**Comment by SourMesen** [comment]
It's not a bad idea, but the amount of effort required to get this done properly would be relatively high and the result would be a small performance loss (because the amount of pixels to draw/process would be larger).  Since I try to avoid changes that hinder performance when I can, I'd end up having to make this an option and keep both the current behavior and this new one in the code, which could get pretty messy & hard to maintain.

I'll keep the idea in mind, but for now, I'm not planning on implementing it.
