### ISSUE TITLE
Tracelogs showing CYC (and sometimes SL) off-by-one?

### ISSUE THREAD

**Issue by Eicar** [SourMesen/Mesen#196]
After looking at the code I'm not sure if the output in the tracelogs are correct.

First of all... the _cycle and _scanline variables are initialized to -1 on reset.
This is due to the fact that _cycle is pre-incremented in PPU::Exec() so the actual
execution starts at _scanline:0 and _cycle:0.

In CPU::Reset() it will pre-run 28 PPU cycles for NTSC (or 30 for PAL) However,
the tracelog will then start at CYC:27... but should have been CYC:28 ???

Have I missed something here or is the CYC value off by one (one lower than it should be)?

**Comment by SourMesen** [comment]
The trace log will essentially show the value of the cycle/scanline counters before the instruction started executing.  Since the first cycle is 0, and it runs 28 times, the cycle counter ends up being 27 (after the first cycle, the cycle is 0, after the 28th, it's 27).  Technically it's at 30 because the PPU is run for 3 cycles before the trace logger can log the current instruction, so the trace logger's code subtracts 3 from the cycle counter to adjust.
I guess it's really more of a question of how you interpret the log - at the moment it's telling you "at this point, cycle 27 is done", rather than "cycle 28 is about to execute"

**Comment by Eicar** [comment]
Ok, good to know.
I guess I'll just have to do a +1 to keep my brain aligned with your numbers then  :)

**Comment by Eicar** [comment]
I still don't think the CYC numbers are correct. The "subtract 3" code in the logger doesn't handle the shorter odd frames on NTSC. Here's one example:

E460  $69 $FF      ADC #$FF       A:01 X:00 Y:00 P:24 SP:F5 CYC:331 SL: -1 FC:169 CPU Cycle:5003138
E462  $D0 $F4      BNE $E458      A:00 X:00 Y:00 P:27 SP:F5 CYC:338 SL: -1 FC:169 CPU Cycle:5003140
E464  $60          RTS                     A:00 X:00 Y:00 P:27 SP:F5 CYC:  3 SL:  0 FC:169 CPU Cycle:5003142

The middle line should be 337. (5003140-5003138=2 CPU cycles=6 PPU cycles) 331+6=337..
This will probably generate some issues with PAL as well for the extra periodically PPU cycles.....

Wouldn't it be easier to do the logging before the instruction execution and not in the middle? I guess you don't want to do this because it will require some opcode pre-fetching for the disass...

What about storing the CYC and SL numbers right before the Exec() ? Then you can use these numbers in the logging instead or trying to re-adjust in the logger?

**Comment by SourMesen** [comment]
I'm aware this isn't perfect in any way - that's why the code says "roughly adjust".

Most ways of fixing this would involve a small performance penalty and extra code outside of the debugger's code to deal with it, which is why I have avoided fixing it.  Saving the counters before running the instruction would also be problematic in some edge cases due to sprite & DMC DMA (I would have to check if they are about to happen, and also adjust the logic based on this).

**Comment by SourMesen** [comment]
After giving it some thought, I've decided to completely remove the cycle/scanline adjustment (2cc0edb76a6bf4403399f7fb016602b4eaafcd7a).
This used to be useful for me when I was comparing trace logs with other emulators, but it does not represent the real state of the emulation at the start of the instruction (and no longer really serves any purpose since the CPU's execution no longer starts with the PPU on cycle 0 like it used to in older versions)

At least this way, the scanline/cycle counters will always make sense in all scenarios, and always represent the emulator's state right before it starts decoding the next instruction.
