### ISSUE TITLE
Shortcuts: Toggle fast forward, save states

### ISSUE THREAD

**Issue by Razor-13** [SourMesen/Mesen#211]
-Toggle shortcut for fast forward would be useful
-Being able to customize the save/load save state shortcuts, ie instead of Shift+F1 and F1 to save and load respectively, use Shift+1 and 1 or Ctrl+1 and 1
-Option for save state shortcut to retain a permanent slot. This can be useful e.g. in Super Mario Bros, I save in the start of a level on slot 4 with Shift+F4 as a fallback to slot 4 in case I save mid-level in a place where I die. If the save state shortcut follows the Shift+Fx slots, it would be overwritten and in order to avoid it I would have to save to slot 4 + slot 1 in the start of a level

**Comment by SourMesen** [comment]
Thanks for the suggestions.
I've added customizable shortcut keys all UI shortcuts in a4d06f683a2e3e32f19f174b4df9ef2df820b028 and added toggle fast forward & toggle rewind shortcuts in 3a2897d53478ac3cb39885182418945c125f6e0c, which should take take of your first 2 points.

For the 3rd, you can also save/load to/from specific non-numbered files of your choosing since 0.9.2.  Also, I changed the behavior of the save/load to a specific slot keys (eg. Shift-F1 and F1) so that they do not alter the current slot used by the move to next/previous slot shortcuts in e64e4731f25bfbc3e6f80035e5c3e4554ad7d4bc.
