### ISSUE TITLE
Crash while powering off and recording an HD pack

### ISSUE THREAD

**Issue by PhoenixBound** [SourMesen/Mesen#217]
Tested on 0.9.1 (couldn't get master to work, but it probably occurs there too).

Normally, using the Power Off option closes the HD pack window if it's open. But if an HD pack is still being recorded when choosing Power Off, Mesen displays this message and all windows close:

![image](https://user-images.githubusercontent.com/13182187/29141985-06912030-7d16-11e7-80a6-29b04d2b0e6a.png)

**Comment by SourMesen** [comment]
Thanks for the report! This should be fixed by ef6e6c74cf906cdae262bf2516d993e802e8b370.

The first time you open the solution (or each time you do "Clean Solution"), you need compile 2x in a row for it to work as expected. Otherwise some files end up being missing from the embedded zip file and it crashes at launch - that might be the problem you were getting?
