### ISSUE TITLE
Some problems with video filters.

### ISSUE THREAD

**Issue by PinkLouie** [SourMesen/Mesen#222]
The Filter NTSC (Bisqwit) ignores the color palettes. It also adds a color column to the left. Maybe it is normal, I do not know.
Can't preview the filter in option menu - video filter, without using it . It something nice to have, preview de filter by just passing the pointer in it,
I Think Wii U/3DS Virtual Console color palette is an interesting option to have.
When you select the NTSC filter (composite, rgb, etc) from Picture in video settings windows, it enables scanlines. But When you choose another filter, the scanlines remain enabled. Better if scanlines were disabled when XBRz for example. I do not see so many sense in using scanlines + XBRz.
Can't move Mesen Window with open settings . Personally, I think the opposite is better. I would like to move the windows to see the effect of what I am doing without closing settings and opening again

Thank you.

**Comment by SourMesen** [comment]
It's normal for the NTSC (Bisqwit) filter to ignore custom palettes (that's just the way it works).  I don't see a color on the left - if you mean a black bar, this is normal.  Otherwise, please show me a screenshot of what you mean.

Scanlines only get enabled if you use the "Select Preset" button - this is normal, it's up to the user to revert the changes if they want to revert them. Disabling them automatically when the filter changes would cause the opposite issue: what about users who do want scanlines with other filters?

You can preview filters by going in the video options' filter tab - I don't really see the point in previewing them from the main menu because a large portion of the screen is hidden by the menu.

The main window is inaccessible while option windows are opened to prevent a number of issues that would occur otherwise (and it is not worth the effort to change this) - you can just move the settings window out of the way instead.
