### ISSUE TITLE
Feature: Turbo Mode, speeds beyond 500%? 

### ISSUE THREAD

**Issue by ImSpecial** [SourMesen/Mesen#231]
So edge case here, but it looks like Mesens Turbo caps at 500%, fine for plebs, but what about those of us that need more power? /Timallengrunt

It'd be cool if you can just let it go to whatever, some games are slow as sin like Final Fantasy, I still go back to [NNNesterJ](https://www.zophar.net/nes/nnnesterj.html) when playing that game because that emulator lets you set the [FPS to anything up to 1000](https://i.imgur.com/lsTxNSP.png), for Final Fantasy for example I use 800FPS which is a lot higher then Mesens 500%.

**Comment by SourMesen** [comment]
Technically, you can set Turbo to 0 to make the emulator run as fast as possible - depending on your CPU, I imagine that might get you up to 700-800 fps (I do not get anything above 450fps on mine).
I'll change the field's limit though, since there is no technical reason for it.

**Comment by ImSpecial** [comment]
Oh I didn't think of setting it to 0, yeah that gets me 500/500 FPS which is pretty good for Final Fantasy :P

**Comment by SourMesen** [comment]
500 fps is pretty good!  I only get about 350 in FF1.
I've changed the field's maximum to 5000% (3000fps) (d44b6904641274c79c5a3e6d4e54eb85a4b19055), which I imagine should be enough for just about anything (not that any current CPU can even get that much FPS out of Mesen anyway).
I also changed the speed progression when using the +/- shortcuts to use a broader range (instead of stopping at 25% and skipping to max speed after 450%)
