### ISSUE TITLE
Support for Somari

### ISSUE THREAD

**Issue by Zenforso** [SourMesen/Mesen#240]
On most emulators you can play this game, only Mesen can't launch it [ Somari (SOMARI-W) (Unl) [!].nes ]

**Comment by SourMesen** [comment]
Thanks for the report - this game is actually a mapper 116 game, which is one of the mappers that is still not implemented in Mesen. It will be implemented eventually, though.

See #136 for a list of mappers that still need to be added.

**Comment by Zenforso** [comment]
I was see already that issue, but from April month there still no added any UNIF-mappers, i think this can be very long waiting to get them in Mesen

**Comment by SourMesen** [comment]
I understand that some people would like to see all mappers supported, but sometimes it's just not a priority.  I've already implemented over 250 different mappers - that's a lot of mappers in less than 2 years.  Most of the ones that remain are for a very small number of unlicensed games or multicarts.

Implementing mappers isn't really fun to do - I code Mesen as a hobby, and prioritize what is interesting, challenging or fun to code.  And I would rather prioritize features that can be useful for all users, in all games, rather than spend hours focusing on mapper support (that the vast majority of people will never use).

The missing mappers will most likely be implemented eventually - all I can say for now is to wait.  I'm not getting paid for this, so I think I at least have the right to decide what I'm working on :)
