### ISSUE TITLE
Developer build

### ISSUE THREAD

**Issue by TheMotherBrain86** [SourMesen/Mesen#241]
Hello, i very enjoyed your emulator but can you do something like this for Mesen? So we can download "fresh" build / version, with recent commit?

Example below:

https://ci.appveyor.com/project/sourmesen/mesen/build/artifacts

**Comment by shaggytwodope** [comment]
Builds per commit can be problematic. Non-stable releases could lead to undesired breakage for users. If you require a feature that is not yet released.... chances are you are knowledgeable enough to follow the nice build instructions on the readme.

**Comment by SourMesen** [comment]
I pretty much agree with @shaggytwodope here.
Offering a build for any new commit would mean I have to worry about configuration upgrade issues, etc. on every single commit I make.

Additionally, Mesen is actually pretty complex to fully build (e.g for a release) because the executable file contains 4 versions of the core (32-bits Windows, 64-bits Windows, 32-bits Linux, 64-bits Linux). It requires compiling the core on both Windows & Linux and then putting it together and compiling the UI+the cores.  So it would most likely be pretty tricky to setup, and may outright not be supported by most online build services (as very little applications do this, that I am aware of).  There are also a number of other reasons that make this more complex (e.g the Windows builds are optimized via PGO, etc.)

In the end, I'd like to think that I release new versions frequently enough that users don't need the very latest commit all the time - Mesen is pretty complete as it stands, everything else I am adding is usually just bells and whistles, at this point. :)   And manually building Mesen is meant to be pretty user-friendly, as well.
