### ISSUE TITLE
Feature request: Favorites game list.

### ISSUE THREAD

**Issue by Cibomatto2002** [SourMesen/Mesen#249]
It would be nice if we had a Favorites game list I have so many that I like that sometimes I forget what the name of them are A Favorite list would help me remember them i got the idea from ARCADE32 0.189 

http://arcade.mameworld.info/

**Comment by SourMesen** [comment]
I think this is beyond what I want to implement in Mesen - at some point, I have to limit the number of features/option I add to the UI, otherwise it becomes hard to use (and I would like to keep it as user friendly as I can)

If you need a "favorite list", I would suggest simply creating a "Favorite Games" folder and moving/copying games that you play often into it.
