### ISSUE TITLE
Rom Hacks?

### ISSUE THREAD

**Issue by ImSpecial** [SourMesen/Mesen#250]
I know you have a dedicated thread for "Unlicensed games, Multicarts & Demos" but do you try and make rom hacks work as well? If not I don't blame you, it should be up to the rom hack author to make sure these sort of things work, especially if they are put together in a "hacky" way to begin with, anyway...

These mods seems to require FCEUX to run without graphical glitches/crashes, I don't know why FCEUX works and literally every other emulator I've tired does not, maybe it's a niche mapper thing... I dunno, I only wanted to bring this issue up because it would be nice to have Mesen be the one and only emulator one would ever need to run anything NES related, keeping FCEUX around specifically for a niche rom hack like this is not ideal.

[Destiny of an Emperor - Ludmeister's Remix](https://www.romhacking.net/hacks/885/)
[Destiny of an Emperor - Rise of Ieyasu 2.0](https://www.romhacking.net/hacks/994/)
[Destiny of an Emperor - Rise of Lu Bu](https://www.romhacking.net/hacks/966/)
[Destiny of an Emperor - Yuan Shao's Revenge](http://www.romhacking.net/hacks/965/)

**Comment by SourMesen** [comment]
What version of FCEUX are you using to run these?  The (recent) one I have causes the same glitches as Mesen for the 2 patches I tried (Ludmeister & Ieyasu).

In general, though, odds are I can't do much about this - a lot of rom hacks are developped/tested only using emulators and often actually don't work on a NES.  These rom hacks suggest using FCE/FCEU, which are even older emulators (and probably less accurate than FCEUX, which is already not terribly accurate in some aspects). The hacks may rely on some bug/inaccuracy in the emulator they were developed with, which likely differs from the actual hardware.

**Comment by ImSpecial** [comment]
Honestly it's been a long time since I played them, maybe 2 years ago, and when I did I had to download FCEUX... which was probably around 2.2.2 at the time, some digging and the only hints from the author about this;

[Use an emulator that supports 512k ROMs! I know FCE Ultra 2.0 works.](http://www.lordyuanshu.com/forums/topic/yuan-shaos-revenge-mod)

[(Note that FCE Ultra is the most tested emulator with DoaE expanded ROMs – any other emulator must support mapper 245).](http://doaerhguide.wikidot.com/)

[Use FCE Ultra 2.2.1 Emulator for BEST compatibility.](http://www.lordyuanshu.com/forums/topic/mod-rise-of-lu-bu-3-0-beta-downloadable) (Page22 "[FCE Ultra Emulator 2.1.5](http://www.lordyuanshu.com/forums/topic/mod-rise-of-lu-bu-3-0-beta-downloadable/page/22)")

> The hacks may rely on some bug/inaccuracy in the emulator they were developed with, which likely differs from the actual hardware.

I agree, it's not worth the effort on this if that is the case here, was hoping it might've been a simple behind the scene switch flip, oh well.

**Comment by SourMesen** [comment]
Thanks for the info.  It does work in 2.2.2, but not in 2.2.3 - it looks like support for this "hack" got removed by this commit: https://sourceforge.net/p/fceultra/code/3182/

Essentially, the rom hacks try to use more than 256kb of PRG ROM using the 5th bit of register $E000.  In FCEUX, this used to work, but on hardware, this actually doesn't work - that bit is actually a flag to enable/disable the save ram.  There is a way to use up to 512kb of PRG ROM on some MMC1 carts, but that works differently than what this hack is trying to do.

Basically, the hack is broken and would never work on a real MMC1 cartridge - there is unfortunately not much I can do here, any solution would require me adding hacks to Mesen's code to support this and then add the rom hacks to the built-in game database to try to detect them and enable the behavior the hack expects.  Doing this for every rom hack that doesn't work would result in tons of new DB entries, and probably tons of hacks in Mesen's code, so it's not really something I want to do - at that point it'd be more about emulating FCEUX's behavior (and in even older hacks, maybe even Nesticle's!), rather than emulating the NES' behavior.

**Comment by ImSpecial** [comment]
Agreed, not worth the effort, thanks for looking into it at least and well, at least you learned something new :)

**Comment by kurrono** [comment]
Boss SourMesen..cancu give me an idea routine for hacking nes music ... Nes is totally different from snes msu1 ..not even the command ORG works for origin address... Give me a little hint..I want to hack nes music..I'm not into the hdpacks..just music
