### ISSUE TITLE
Black Border Bug?

### ISSUE THREAD

**Issue by ImSpecial** [SourMesen/Mesen#251]
Me again, your favorite complainer. :P 

So I've noticed that I get this black border on first launch of the emulator, it goes away if you touch the screen size in any way such as min/maxing it, touch a corner of the window and drag it a little, press one of the presets sizes x3, x4, etc. or enter/exit fullscreen mode. My settings are pretty stock, No streching / x4 size / Windowed / Filter=SuperEagle

Actually as I type this, and double checking, it seems the x4 size isn't being saved properly? Because when I check the video options its an odd 3.73 custom size instead of being x4.

[Black border on the top and bottom](https://i.imgur.com/e8qE1lq.png)
[Fixed by just pressing the x4 preset](https://i.imgur.com/ohHAQ3O.png)
[Launched Mesen a second time, border all around.](https://i.imgur.com/LsqZWOp.png)
[Weird ratio being saved...](https://i.imgur.com/3aVKAMo.png)

**Comment by SourMesen** [comment]
This is another DPI-related bug and was reported by someone else too, actually, so it should already be fixed.

You can try this build to see if it's fixed on your end as well (also contains the DPI fixes): https://www.mesen.ca/MesenSizeFixes.zip

**Comment by ImSpecial** [comment]
Looks good, I checked all the windows for cut offs too, [and only noticed just this one...](https://i.imgur.com/FGjx6rx.png)

**Comment by PinkLouie** [comment]
Hi, as you can see in the last ImSpecial screenshot, the down arrows in "Filter" and "Select Preset" are different. It seems inconsistent. I think the system design is a better standard.

![2017-09-18](https://user-images.githubusercontent.com/30609937/30566728-99b0ef24-9ca3-11e7-9120-5d4481d93ee5.png)
 to follow.

**Comment by SourMesen** [comment]
Thanks - I fixed that cut off line (was actually getting cut off at 100% DPI, too).

@PinkLouie Those aren't actually dropdowns, they're just buttons w/ an image on them to make them look similar to dropdowns.  The image is made to match Win7's style - I added another icon and updated the code so that it shows the new icon in Win8+.  This isn't perfect though, but it's the best I can do in a short amount of time, and it's not really worth putting any more time into.
