### ISSUE TITLE
chinese rom name in zip file show "could not load file: ?????? "

### ISSUE THREAD

**Issue by kokutoukiritsugu** [SourMesen/Mesen#252]
![snipaste20170919_192012](https://user-images.githubusercontent.com/5471433/30590043-944a8032-9d6f-11e7-81e8-690070f274b7.png)

here the some  chinese words for test：
中文名
汉字

**Comment by SourMesen** [comment]
Thanks for the report - this is a limitation that I am aware of and that I do not plan on fixing at the moment.

Mesen relies on a pre-generated font to display messages on the screen.  This font contains the strict minimum necessary to display all built-in messages for the languages Mesen currently supports. When characters that are not present in this pre-generated font are found (e.g because they are present in a file's name), the characters are replaced with a '?'. Fixing this with the way things currently are would require adding 5000+ chinese/japanese characters into the font, which would probably make it 10 times larger than it currently is, which is not really a compromise I am willing to make right now.

**Comment by kokutoukiritsugu** [comment]
no, no, no ...

I mean ,it really cant load... not the display problem.
display chinese word is not big deal.

maybe the zip decompress cant handle chinese words.


![snipaste20170927_201043](https://user-images.githubusercontent.com/5471433/30912666-0efc4da0-a3c0-11e7-8245-1d45dacab2a6.png)
LEFT -----> not in the zip file, just [SomeChineseWords].nes -----> OK
RIGHT  ----->  int the zip file with chinese words -----> cant load.

**Comment by SourMesen** [comment]
Ah, ok, I misunderstood what you meant.
It seems to work fine with .7z files, so it looks like this is specific to .zip files - I'll take a look.

**Comment by SourMesen** [comment]
Thanks for the report - this should be fixed by 0d1e9bbcb381782664dc38afe54e34109dabbc50 (it will still display ???s on the screen, but it should load the files correctly)
