### ISSUE TITLE
Impossible to play in full screen

### ISSUE THREAD

**Issue by ghost** [SourMesen/Mesen#255]
Actually there is no way (almost) to play a game in full screen. My monitor is 16:9, so I selected 16:9 in Aspect Ratio. But the AP ratio stretches before the overscan crop, so I get black bars, as you can see in the screen shot.  No Full Screen. Besides that, this way, the aspect ratio will never match the described value, if the overscan in enabled, which is needed in some games. If you follow the trends, you may know new laptops are coming with 3:2 AR monitor (Surface Laptops for exemple), which, personally I think is good.  There are still 16:10 laptops on the market, the Macbooks for example. The overscan screen also do not mention the measure it uses for crops. By default it is 8 up and down, but it is not specified if it is 8%, 8px, or other measure. I think it is % because I realized that the crops happen proportionally even if the image is not a perfect square. If you stretch a game to 8:7, everything gets perfect, squares, circles, etc, then if you cut 8 up and down the image gets 4:3, which is the way people played in old TVs (I think is the best configuration), so, by default, 8:7 actually results in 4:3. The main problem is not even it, it is the fact that it's not possible to to use the whole screen to display a game, specially in a non 16:9 monitor.

![2017-09-25 1](https://user-images.githubusercontent.com/30609937/30846523-620ee0fa-a26e-11e7-89cb-2f87f947722c.png)
![2017-09-25 2](https://user-images.githubusercontent.com/30609937/30846524-6210c5d2-a26e-11e7-963a-b264060daeb4.png)

Thank you anyway.

**Comment by SourMesen** [comment]
This is by design, since I doubt most people would want the aspect ratio of the screen to vary whenever the overscan settings change - without this, the NTSC/PAL aspect ratios would only work correctly when no overscan is defined.

The overscan values aren't in percent, they are in pixels, based on the NES' 256x240 resolution.

I'll see about adding an option to ignore overscan when applying the aspect ratio, which should fix your issue.

**Comment by PinkLouie** [comment]
Yes, most people probably play in 4:3 or 8:7, not 16:9. I supposed the 16:9 was added for full screen purpose. But as not all monitor is 16:9, isn't it better to replace the option 16:9 for a new "Full Screen" option? It would fit different formats. I do not see a reason for someone use 16:9 aspect ratio in a non 16:9 monitor after all.

**Comment by cyrilleCh** [comment]
But 16:9 format for NES it's absurd, no good reason for option like that i think (or to avoid burn-in with some display?) .

**Comment by PinkLouie** [comment]
You are right cyrilleCh,  but if you watch gamesplays you can see people like to play stretching to the whole display.  Most old people like to use the whole display,  my mother for example. Maybe children too.

**Comment by cyrilleCh** [comment]
Yes but wrong use isn't a argument to implement an option. It's a argument for not to implement and force good use :-)

**Comment by SourMesen** [comment]
This is actually already possible by using the "Custom Aspect Ratio" feature, which lets you select any aspect ratio you want, allowing you to fill up the screen no matter the overscan settings you are using.
Since playing NES games in 16:9 is fairly unlikely and it's already possible to get this to work with a little effort, I prefer not to add an option for this (for the sake of code & UI simplicity)
