### ISSUE TITLE
Music pops when Enable Reverb is on.

### ISSUE THREAD

**Issue by Cibomatto2002** [SourMesen/Mesen#263]
The higher you turn it the more it pops.

Here is a video of it.

https://www.youtube.com/watch?v=PRBhF4UBwIk&feature=youtu.be

**Comment by SourMesen** [comment]
This is more or less normal, especially if you have the master volume set to a high value (e.g 100%) - you should keep it at a lower level (the default is 25% iirc) and increase your speaker's volume instead, if you need higher volume, this will reduce the chance of audio filters causing pops.

**Comment by SourMesen** [comment]
Closing since this is normal - I can't really do anything to prevent this considering the number of audio settings in Mesen that can be used to increase the sound output beyond the valid ranges (equalizer, reverb, stereo settings, etc).
I'll add a note in the documentation to mention it's preferable to increase the computer's volume rather than setting the master volume to 100%.
