### ISSUE TITLE
load roms error, When .nes filename contained Chinese characters ,and it stored in .zip file

### ISSUE THREAD

**Issue by gartour2** [SourMesen/Mesen#270]
Interestingly,  
zip files with Chinese characters filename works good.
rom files(without zip format, such as .nes) with Chinese characters filename  works good else.
.7z works good

**Comment by SourMesen** [comment]
Thanks for the report.  This should be the same as #252, it should now be possible to load the files (although the file names might look corrupted, mostly due to limitations of the zip format).

This dev build from a little while ago already contains the fix: https://www.mesen.ca/MesenDebuggerFixes6.zip
