### ISSUE TITLE
AV Detection/Batch Commands

### ISSUE THREAD

**Issue by SlavkoPavlovic** [SourMesen/Mesen#271]
Bitdefender blocked part of this program thinking that it is a virus.
Can't get batch commands to work, only fullscreen worked (I read the instructions).

**Comment by SourMesen** [comment]
All I can say is that either BitDefender is wrong, or the version of Mesen you downloaded contains a virus (e.g if you downloaded it from another website).  BitDefender doesn't list version 0.9.3 as a virus according to this:
https://www.virustotal.com/#/file/d518ace54cc3f04ce36b9eeba47807436fe17a412576adef4f4b74599f17d911/detection

As for the command line options, an example of a command line that you tried to use and that didn't work would be helpful. (e.g `Mesen /option1=100 /option2=false`)

**Comment by SlavkoPavlovic** [comment]
K, Idk what was up with that detection, I downloaded Mesen from the official site (https://www.mesen.ca/#Downloads). I couldn't get /VideoScale and /aspectratio to work in batch files, any setting/value I set it to, Mesen just uses the default settings.

**Comment by SourMesen** [comment]
I have done a fair amount of testing with command line switches and was not able to reproduce this (the switches work as expected).  If you still get the same issue in 0.9.4, since you mentioned a batch file, please attach the batch file that you are trying to use which causes the problem, to see if it helps me reproduce the issue.
