### ISSUE TITLE
Timer issue / enhancement

### ISSUE THREAD

**Issue by Jenny794** [SourMesen/Mesen#272]
Move timer a little up, because it overlaying number "1" slightly. Also my suggestion to add option to move timer, like input display (Top Left / Top Right / Bottom Left / Bottom Right)

![mesen](https://user-images.githubusercontent.com/33526209/32622738-8a447daa-c58c-11e7-9905-de31c4978447.jpg)

**Comment by cyrilleCh** [comment]
On the right there isn't only timer. There are fps counter and frame counter and lag counter... but you can move input display to the Left or Bottom, that's the solution i think.

**Comment by SourMesen** [comment]
The alignment of the text compared to the controllers behind it depends on the window's scale (because the controller's size scales with the window, but the text does not), so even if I move the timer's position, the issue would not be fixed. There isn't really anything I can do except suggest that you display the controllers elsewhere on the screen if that is an issue for you.

Having options to select the location of everything on the screen would require too many settings, and they would not be useful for the vast majority of users (and would just make the configuration more complex for very little added value).
