### ISSUE TITLE
Mesen 0.9.4 - Files with a dash in their name don't load from file explorer or command line

### ISSUE THREAD

**Issue by jaw9170** [SourMesen/Mesen#287]
Hello.  Using Mesen 0.9.4, games containing parenthesis or brackets no play automatically.  You need to click on the menu and load the game from the menu first.  Other games load fine.

Example game name:  American Dream (J) [T].nes
Game does not load

Example game name:  Altered Beast.nes
Game loads and auto plays fine

This does not happen using 0.9.3 as games with parenthesis or brackets auto play fine

**Comment by SourMesen** [comment]
Thanks for the report.
I can't seem to reproduce this, though.  I tried renaming a file to "American Dream (J) [T].nes" and it seems to load as it usually would, no matter how I try to load the game.

Maybe you turned on a specific setting in Mesen that could cause this?  I'm not too sure what you mean by "auto play", though.

**Comment by jaw9170** [comment]
I apologize for the false alarm.  Seems to be an issue with the frontend I am using.  Mesen 0.9.4 is fine.

Jason

**Comment by SourMesen** [comment]
Thank you! I was able to reproduce the issue, and it is in fact a new bug 0.9.4.
You were close, it's not the brackets or parenthesis that cause the problem - it's the dash in the filename. :)

Thankfully, there shouldn't be too many rom files with dashes in their name (relatively speaking) and it only affects file associations & running from the command line, so it shouldn't be too much of an immediate problem.
I'll get it fixed later today (but probably won't be releasing a new version for a few weeks unless something major is reported)

**Comment by jaw9170** [comment]
Very good!  Glad I could help!  :)

**Comment by SigmaVirus** [comment]
Thanks man!
I was just about to report this too since I use a Batch File CLI launcher and none of the games with dashes worked for me, like Rockman 2 - Dr. Wily no Nazo (Japan) etc.

Could we get a test/WIP version to try out if you fix the issue?
I really really want to switch to Mesen permanently!

**Comment by SourMesen** [comment]
A lot of people seem to be getting the same problem, so I went ahead and updated the 0.9.4 release itself.  It won't trigger an update prompt, however (since it's the same version number).  You will need to manually download Mesen 0.9.4 from GitHub or mesen.ca to get the fix.
If you try it out, please let me know if it fixes the issue on your end as well.

**Comment by jaw9170** [comment]
Okay, I manually downloaded 0.9.4 and tested a few games containing dashes.  Those games that previous would not work now work.  I tested a few others and they seem to work as well.

Thank you for addressing this so quickly.  Long live Mesen!

**Comment by SourMesen** [comment]
Great - thanks for reporting this and testing the fix!

**Comment by SigmaVirus** [comment]
It works perfectly now, thanks to you both @SourMesen and @jaw9170 !!!
Mesen is AWESOME and super duper accurate, I LOVE IT!

**Comment by SigmaVirus** [comment]
This should probably be closed now since it works great!

**Comment by SourMesen** [comment]
Yep - thanks again for the reports.
Let me know if you find anything else!
