### ISSUE TITLE
Option to choose "None" for 2nd player in Famicom console type

### ISSUE THREAD

**Issue by redstubbs** [SourMesen/Mesen#289]
Maybe i'm miss something? Mesen automatically enabling P2 , and if you choose NES console type you can select "None".

Summary:

Famicom console type - cannot choose "None" for P2 instead of "Standart Controller"
NES console type - can choose "None" for P2 instead of "Standart Controller"

**Comment by SourMesen** [comment]
This is by design - the original famicom cannot unplug the P1 & P2 controllers, they are hardwired to the console.
To remove this restriction, you can enable the "Use NES/HVC-101 (Top-loader / AV Famicom) behavior" option in Emulation->Advanced. This will make Mesen emulate the AV Famicom's behavior instead, which has detachable controllers, like the NES.

**Comment by SigmaVirus** [comment]
@SourMesen 
That's really ingenious, you have really thought of everything and that's why this is now my Famicom/Famicom Disk System emulator of choice!
