### ISSUE TITLE
Windows Defender does not like Mesen 0.9.4

### ISSUE THREAD

**Issue by RealRexen** [SourMesen/Mesen#291]
I just downloaded this version onto windows, unzip the exe and got this:
![screenshot 13](https://user-images.githubusercontent.com/18408903/34454516-1670f9cc-ed3b-11e7-9cd8-4ca49f1b0dc7.png)
By the way this is a freshly clean install of Windows 10 so I don't think its an issue on my end, might be a false flag

**Comment by SourMesen** [comment]
It's a false positive - a similar report was made on reddit earlier:
https://www.reddit.com/r/emulation/comments/7mzfuy/mesen_v094_released/dry2i4o/

I redownloaded the file myself from mesen.ca & github.com to ensure it is still the original file I uploaded, and the SHA1 hashes match.
See [the scan result on VirusTotal](https://www.virustotal.com/#/file/fa159a5430525989f55dfa70386409fe134560a6ebef0405e6c652c51115dc6b/detection) - all of the scans they ran do not detect any virus.

Strangely enough, I'm also running a clean install of Windows 10 (3-4 weeks old) and Windows Defender doesn't say anything about a virus, even when I explicitly ask it to scan the file.  All Windows Updates are done, and Windows Defender's virus definition file is dated December 29.  So I really don't know why on some computers it claims that Mesen is a virus, and not on others.

**Comment by anewuser** [comment]
I've had no problem on my old Windows 10 install either. You can report this at https://www.microsoft.com/wdsi/filesubmission

**Comment by RealRexen** [comment]
Okay I reported it to Microsoft

**Comment by SourMesen** [comment]
Yea, it looks like a fair number of people seem to be getting issues due to AV software.
I'm honestly not sure why - there is nothing that has changed in 0.9.4 compared to 0.9.3 that would make it more likely to trigger AV warnings.
Hopefully the problem resolves itself once the files have circulated a while and AV software heuristics decide that the file is safe to use.
I'm unsure how long Microsoft takes to react to these, but assuming it takes a while, the next release might occur before they even take a look at 0.9.4, so it might not be that helpful :\ Thanks for taking the time to do so nonetheless, though!
