### ISSUE TITLE
Default Family Basic Keyboard Mapping

### ISSUE THREAD

**Issue by tpwrules** [SourMesen/Mesen#293]
The DEL key on the Family Basic keyboard is, by default, mapped to the DEL key on the computer keyboard. The [NESDEV wiki](https://wiki.nesdev.com/w/index.php/Family_BASIC_Keyboard#Keyboard_map) notes that it should instead be mapped to Backspace. A homebrew I'm working on expects that. I'm not sure what official released games expect the key to do (Family BASIC itself seems to treat it as a RETURN) but Backspace seems like a more logical choice as the key is otherwise missing.

**Comment by SourMesen** [comment]
It's mostly a matter of either respecting the key names on the Family Basic Keyboard, or their function.
The key at the usual position for "Backspace" on the family basic keyboard is called "STOP" - it can be used, for example, to stop the execution of the currently running BASIC program.
On the other hand, "DEL" does act like "Backspace" does (at least, in Family Basic this is the case), but it is located on the right-side of the keyboard, next to Insert/Home, like the Delete key on modern keyboards.

So really neither solution is great really - you either mismatch the key names or their functionality. (e.g if I switch this to backspace, and at some point the program refers to the "DEL" key, then the user has to press backspace instead of delete, even though the program is talking about the DEL key). 

I agree that mapping DEL to Backspace makes it easier to type text, though, so maybe it would make more sense to switch the 2 keys based on that alone.

**Comment by SourMesen** [comment]
I've inverted the default keybindings so the backspace key maps to the "Delete" key, which makes it a lot easier to type with the keyboard (dbfd45a99be7864cdee286a2de06038ef35dab73)
