### ISSUE TITLE
Debugger Instruction Alignment

### ISSUE THREAD

**Issue by tpwrules** [SourMesen/Mesen#294]
When using the debugger, it understandably sometimes confuses code and data and begins disassembling instructions at an incorrect address. The trouble is that there seems to be no way to force it to begin at the correct address. Loading debugging symbols, changing the disassembly mode (this happens even in Verified Code Only), changing the PC, single stepping, etc will not fix it. 

A screenshot of a homebrew ROM demonstrating the behavior is attached. The debugger has broken just after the ROM is loaded. The reset vector in ROM is at $(3E)E3A8, the v_reset label is at $E3A8, the PC is at $E3A8, and the debugger has matched the source to the 
instructions at $E3A9 onwards. Yet, it's convinced there's an instruction at $E3A7 (it's actually graphics data) and I can't figure out how to make it restart disassembly at $E3A8 and ignore the bogus instructions.

![screenshot from 2018-01-01 11-43-33](https://user-images.githubusercontent.com/208010/34469630-35b96666-eee9-11e7-88ab-aab6b3bd3b50.png)

**Comment by SourMesen** [comment]
Assuming this is for a rom that you are altering/recompiling, this is probably caused by the CDL data from previous debugger sessions.  Can you try resetting the CDL data in Tools->Code/Data Logger->Reset?
Other than this specific case (where the ROM itself is changed), the disassembler should never incorrectly disassemble code in "Verified code only" mode (unless there is an actual bug)

**Comment by tpwrules** [comment]
Ah okay, that was what I was doing and your solution fixed it. I don't believe there's any further issue with the feature then.
