### ISSUE TITLE
Crashing on startup on linux

### ISSUE THREAD

**Issue by gauauu** [SourMesen/Mesen#299]
I've been using Mesen daily without significant issue, then all of a sudden today it starting crashing on startup, with the error dialog that you can see on the attachment
![mesencrash](https://user-images.githubusercontent.com/1113009/34630376-77a78742-f231-11e7-8853-7867f7f8b3dd.png)
 .  Now that it started doing this, it does it 100% of the time until I delete my settings directory (which fixes it).  I've saved the old (possibly corrupted?) settings directory if I need to upload other files to help debug this.

I'm currently using 0.9.4 although I had seen this issue with a previous earlier version (but never bothered to report it).

OS is Linux Mint 18 Cinnamon 64-bit.

Thanks!

**Comment by SourMesen** [comment]
Thanks - if you could just send me your settings.xml file, it should help me reproduce it (or at least figure out what might be causing the issue).

Does Mesen fail to load after that dialog box? Or does it just pop the dialog and then continue loading normally?

**Comment by gauauu** [comment]
It fails to load after that dialog.  settings.xml attached (renamed to .txt because github yelled at me for trying to upload xml) Thanks!
[settings.xml.txt](https://github.com/SourMesen/Mesen/files/1608132/settings.xml.txt)

**Comment by SourMesen** [comment]
Turns out I wasn't able to reproduce it on my end, but either way, it should be impossible to get that particular crash with the changes I've made (af65e8aba728fc39c10461a698099be9df527f17).  It might have been caused by a 2nd instance of Mesen in memory (e.g that didn't close properly) or by file associations, not too sure.  Let me know if you get this crash again.

And unrelated, if you happen to be building Mesen yourself, I made some changes to the debugger's code window early last month to add syntax highlighting and improve readability for unknown/data segments/etc.  If you have any feedback on the changes, let me know (it should only improve vs what it was before, but maybe I missed something along the way).
