### ISSUE TITLE
Got a critical error (UnableToStartMissingDependencies)

### ISSUE THREAD

**Issue by jinstrider2000** [SourMesen/Mesen#323]
Hi, I'm running Mesen on a Windows 10 insider build (17074) and I got this error.  What dependencies is it looking for exactly? As far as I know, I haven't purposefully uninstalled any C++ Redistributables (or the like) and Mesen was working before. Thanks.

**Comment by SourMesen** [comment]
Beyond .NET 4.5+ and DirectX11, Mesen has no external dependencies.
That message means Mesen was unable to load the emulation core's DLL (the file exists, but couldn't be loaded for some reason).  It's also odd that it says Critical Error + UnableToStartMissingDependencies, rather than displaying the actual message that "UnableToStartMissingDependencies" refers to - this technically implies that it was unable to load the resource file (despite the fact that it should have crashed with another error message if that was the case)

I would suggest taking a look at Mesen's data folder (e.g: C:\Users\<user>\Documents\Mesen by default, but can also be in the same folder as Mesen.exe depending on your settings) and checking if a MesenCore.dll file exists and its size (if it's 0 bytes or very small, something is wrong).

You could try renaming the folder to something else entirely to force Mesen to "reinstall" itself and see if that changes anything.

**Comment by jinstrider2000** [comment]
Thanks for the reply.  I tried "reinstalling" as you suggested, and when I choose to place the application data under my user profile, the program threw a missing dependencies error again, but when I tried again and chose to put app data with the .exe, it worked.  Maybe it's just my computer, but that fixed it for me.

**Comment by SourMesen** [comment]
That's a bit odd - sounds like Mesen was having issues writing or reading files from your profile's folder.
It could be caused by a few different things, like:
-No disk space left on that drive
-Permission issues that are preventing file reading or writing
-Maybe an anti-virus or another similar software is interfering and preventing Mesen from extracting files to that folder?
-Weird characters in the path (this shouldn't cause issues with Mesen normally, I'm only mentioning it in case)
-Path is too long (this is unlikely too, but Windows historically does have some limitations to the maximum length of a file's path)

**Comment by jinstrider2000** [comment]
Thanks for the help, I'll close this now.
