### ISSUE TITLE
Libretro gcc compilation problem

### ISSUE THREAD

**Issue by Tatsuya79** [SourMesen/Mesen#332]
I'm trying to build with mingw64 on win7 x64 with gcc 6.3 (that worked before, got a core compiled on January the 13th).
This is what I get:

```
$ make -j4
mkdir -p SevenZip/obj.x64 && cd SevenZip/obj.x64 && clang -fPIC -Wall -O3  -m64 -c  ../Delta.c
mkdir -p SevenZip/obj.x64 && cd SevenZip/obj.x64 && clang -fPIC -Wall -O3  -m64 -c  ../Bcj2.c
mkdir -p SevenZip/obj.x64 && cd SevenZip/obj.x64 && clang -fPIC -Wall -O3  -m64 -c  ../7zCrcOpt.c
mkdir -p SevenZip/obj.x64 && cd SevenZip/obj.x64 && clang -fPIC -Wall -O3  -m64 -c  ../CpuArch.c
/bin/sh: clang: command not found
make: *** [makefile:96: SevenZip/obj.x64/Delta.o] Error 127
make: *** Waiting for unfinished jobs....
/bin/sh: clang: command not found
make: *** [makefile:96: SevenZip/obj.x64/Bcj2.o] Error 127
/bin/sh: clang: command not found
make: *** [makefile:96: SevenZip/obj.x64/7zCrcOpt.o] Error 127
/bin/sh: clang: command not found
make: *** [makefile:96: SevenZip/obj.x64/CpuArch.o] Error 127
```

**Comment by SourMesen** [comment]
Are you trying to use the old makefile in the root folder, or are you using the one in the Libretro folder?

**Comment by SourMesen** [comment]
The makefile in the libretro folder hasn't changed since early january, though... If you were able to build it on mingw on Windows at that time, then something must have changed in your environment?

I did not actually make the makefile in the libretro folder, radius/bparker did - they would probably be more help than me for this.  As far as I can tell, it selects the compiler based on the platform, with GCC being set when none of the previous platform checks match.  In your case it's trying to build with "cc", which is weird. Some of the platforms in the makefile don't appear to set "CC" at all, though - maybe your setup ends up using one of those and the default value for "CC" is "cc"?

**Comment by Tatsuya79** [comment]
I'm not sure what's going on, I'm not really good with that stuff!
I tried to revert to the commit I was on and got the same error.

So, you're probably right and something happened here with msys2 I have to find I guess.
Sorry to have bothered you.

**Comment by Tatsuya79** [comment]
...and

I killed some files that were in msys2/tmp folder and now it's working. :persevere:
