### ISSUE TITLE
Mapper15: Graphics corruption in Urban Champion

### ISSUE THREAD

**Issue by retro-wertz** [SourMesen/Mesen#348]
In relation to this PR:
https://github.com/SourMesen/Mesen/pull/347/commits/244326092fa19b810eaad2af10537d442802c2d2

When switching to Urban Champion from playing Contra, graphics corruption can occur.

How to replicate:
-Run Contra. i think any variation would do.
-press Reset
-switch to Urban Champion. graphics should look similar to this:
![100-in-1 contra function 16 p1 nes-180401-200455](https://user-images.githubusercontent.com/23315382/38172986-d8aa79aa-35e8-11e8-94ee-ee817918789f.png)

But starting to play Urban Champion without playing Contra, the game works fine. 
Im unfamiliar with mesen' atm so im missing some remapping probably or reg reset somewhere else.

I can only test under LIBRETRO since atm, mono package (5.10.x ) is broken again in Arch.

Also noticed, Urban Champion's title screen behaves differently depending on RAM init state. that game probably wants a clear ram always? filling 0's seems to work well but glitch when switching still there.

**Comment by SourMesen** [comment]
Based on this, I'd say the cartridge itself is bugged.  Any software that has different behavior based on the RAM init state is unreliable, even on hardware.  It looks like the cartridge doesn't initialize the memory properly, and Urban Champion seems to expect the RAM to be zeroed out when it starts.  So playing Contra probably sets some bytes in memory that causes the scroll glitch to appear on Urban Champion (because the game select menu's code doesn't reset/initialize the NES' RAM)

FCEUX seems to have the same behavior as this, too.

**Comment by retro-wertz** [comment]
this is a cart issue then, since its the only game that seems to want a hard-reset. in any case, after running Contra, running Bros. then running Urban Champ seems to clear the ram.

im closing this for now.
