### ISSUE TITLE
Support for the U-Force controller

### ISSUE THREAD

**Issue by kurayami6** [SourMesen/Mesen#359]
I can't get past the title screen in U-Force power games proto because the controller is not supported.

![capture](https://user-images.githubusercontent.com/31968468/38404649-03cfc6f2-39af-11e8-874d-289f79841d10.PNG)

https://en.wikipedia.org/wiki/U-Force

**Comment by retro-wertz** [comment]
The U-Force was ranked the eighth worst video game controller by IGN
<https://en.wikipedia.org/wiki/IGN> editor Craig Harris.[3]
<https://en.wikipedia.org/wiki/U-Force#cite_note-3> MSN
<https://en.wikipedia.org/wiki/MSN> listed it as one of the top 10 worst
game peripherals, writing "Second only to the Sega Activator
<https://en.wikipedia.org/wiki/Sega_Activator> in terms of all-out
crappiness, the U-Force also used infrared sensors to create a truly
nightmarish controller...'Don’t Touch' said the adverts for the device, in
a rare example of an advertising campaign that got it spot on."[4]
<https://en.wikipedia.org/wiki/U-Force#cite_note-4>

I dont know why you even want that emulated...

**Comment by SourMesen** [comment]
A number of input devices (beyond this one) are also unsupported (which is why adding support for more is still part of the roadmap).  The remaining ones are relatively unknown/unused in games, overall, though, so they are not very high priority.

Either case, I've opened #361 to keep track of these in a single item.
