### ISSUE TITLE
Lua access for hotkeys (and special hotkeys for script)

### ISSUE THREAD

**Issue by spiiin** [SourMesen/Mesen#362]
Now there are several ways to interact user with lua script:
- read joypads input, that can be mapped to any key by user.
- read keyboard with input.
But there is no way to check, what keys user want to use as script controls (hardcode selected keys in script may intersected with user game buttons)

Possible solution is adding enum like emu.hotkeys.SCRIPT_KEY1-SCRIPT_KEY10, than can me mapped to any key in GUI (globals to any lua scripts). And, also, possible, 1 or to 2 keys must be mapped by default to some keyboard keys (so, developer can just say to non-skilled user: "Run my script and press F to enabled/disable it").

Maybe, other hotkeys also need to be accessible in script, but  I have no ideas about it now.

**Comment by spiiin** [comment]
Additional, event like onKeyPressed needed, because of no chance to script author to make logic like "run a function on keyPress only once", I think that's no good, that such simple thing needs to be coded with additional logic in scripts.

You may see this problem with this script
https://github.com/spiiin/CadEditor/blob/master/Stuff/nes_lua/mesen_modifyScreen.lua
Input reads many times per second, so callbacks run several times.
(I know that it's possible to make a workaround for checking previous states of keys, but this is no task, that script maker want to do).

**Comment by SourMesen** [comment]
Some thoughts:

-Having "custom" keys for Lua scripts seems ok in theory, but maybe bad in practice.  I would assign some random keys to them by default - but whatever I choose may not make any sense for any specific script.  This makes it hard for a script to use controls that are intuitive (using the default keybindings)...  I'm not sure this would be better than just accepting the (relatively low) chance of overlap between script & controller keybindings?  Forcing the user to edit their shortcut key preferences from one script to another to get keybindings that makes sense for a particular script isn't very ideal, either..  I understand the issue, but can't really come up with any decent solution for it.

-emu.isKeyPressed actually returns the current physical state for that key, it does not have any relation to the inputPolled event (which is an emulation core event), and doesn't need to be called in inputPolled, either.
I can't easily add "onKeyPressed" events, because no such logic exists in the emulation core at the moment - it's not impossible to add, but would involve a fair amount of work.
