### ISSUE TITLE
Mappers and unif boards

### ISSUE THREAD

**Issue by neoantwon** [SourMesen/Mesen#366]
Hi mesen, when we will have more unif-boards and mappers, is there any expectations so we can wait?

**Comment by SourMesen** [comment]
Like it says in the readme, adding support for more boards is still on the roadmap. However, at this point all licensed games, and the vast majority of unlicensed games are supported.  The majority of remaining mappers tend to have 1-2 titles each (and most of the time, these are multicarts that contain games that can be played standalone).  So it's a lot of effort, and does not really benefit anyone all that much - because of this, adding support for more boards is usually a low priority.
