### ISSUE TITLE
Rewind and fast forward cause desyncs in movies.

### ISSUE THREAD

**Issue by chexo3** [SourMesen/Mesen#376]
They don't rewind and fast forward inputs, causing desyncs when played back.

**Comment by SourMesen** [comment]
Rewinding while recording isn't supported (it was meant to be disabled, but I guess this restriction may have been removed by mistake at some point.)  Fast forward shouldn't be causing any issues, as far as I am aware, though.

The ability to rewind while recording (and re-recording) will be added eventually, whenever I get around to building proper TAS tools.

**Comment by chexo3** [comment]
I assume that comes at some point after Mesen passes all the test roms, right? Make sure to preserve that simple playback system. It's nice to be able to casually playback movies without having to go through a more detailed menu. Maybe a simple/advanced tab.

**Comment by SourMesen** [comment]
Mesen passes more or less all of the existing test roms (though that doesn't mean the emulation is perfect - it's not) - it's mostly just a matter of priorities, there's still a number of other things to do besides TAS tools (support for more mappers/input devices, debugger features, etc.).

I disabled rewinding while movies are recording (3725f442b9e831de2acf26624207c178366a0965) like it was meant to be in the first place since it corrupts the movies at the moment. I'm closing this item since there's already another item requesting re-recording and adding TAS tools is in the roadmap in the readme, too.

Thanks for the feedback w/ regards to keeping a simple playback system - I'll keep it in mind when I start adding more TAS-related features.
