### ISSUE TITLE
Error when dragging archived roms over Mesen window

### ISSUE THREAD

**Issue by MaizeWhale** [SourMesen/Mesen#380]
Mesen 0.9.5 Pretty self explanatory.
![screenshot from 2018-05-09 14-30-03](https://user-images.githubusercontent.com/30946259/39812620-0fbbe788-5396-11e8-8c4c-be81a5779179.png)

**Comment by SourMesen** [comment]
Thanks - the crash is fixed by fe8125e58db83f2365fafc14c13a911f1f48a692.  Assuming you were drag and dropping a rom from inside a compressed archive to Mesen's window, this still won't work, though. Mono appears to just not support this scenario (since it outright sets the "data" for the drop event to null, which is what caused the crash).

This also doesn't work on Windows (will say "Unsupported operation." if you try to do this) - Linux should behave the same now, too.
