### ISSUE TITLE
Full Screen Mode Cutting off bottom of image - Surface book 2 15"

### ISSUE THREAD

**Issue by U3erDuper** [SourMesen/Mesen#382]

**Comment by SourMesen** [comment]
Thanks for the report!  Looking at the specs for the Surface Book 2, it seems to have a high definition screen (not quite 4k but close), so it's very likely that this is the same issue as #312 & #295.  I'm hoping to get this fixed soon(ish), but since I haven't managed to reproduce this on my end, finding the exact cause is a bit tricky.

**Comment by SourMesen** [comment]
FYI, this should be fixed now.  I posted a link to a dev build with the fix here: https://github.com/SourMesen/Mesen/issues/312#issuecomment-394177202
This build should hopefully solve the issue on your Surface Book, too.
