### ISSUE TITLE
Mesen hangs when using GameStream

### ISSUE THREAD

**Issue by PMaryniak** [SourMesen/Mesen#387]
@SourMesen Hello there, I've been using Mesen 0.9.5 for awhile and it was working fine but now every time I launch it would crash. It would hang when I tried changing the controls and when loading different ROM files. I've tried reinstalling, restarting and searching for a solution with no luck. I, unfortunately, could not get a dump as it doesn't appear under my crash dumps in my user file. If there is any way you could help it would be greatly appreciated. Thank you for your time.

**Comment by SourMesen** [comment]
Hey, 
Have you tried renaming your settings.xml file to something else and forcing Mesen to reset all of its settings?  The settings.xml file is in Mesen's folder (you can open it from Options->Preferences->Open Mesen Folder).  Alternatively, you can also try renaming the folder itself (e.g rename Mesen to Mesen.old or something akin) to force Mesen to recreate it (and everything else) from scratch to ensure it's in its default state.
If this doesn't help, I'm not really sure what could be causing the issue - maybe a Windows update or graphic card drivers update caused the problem?
If renaming the settings.xml file works, please attach the original file here, I might be able to reproduce the issue on my end and fix it.

**Comment by PMaryniak** [comment]
@SourMesen I tried renaming the settings.xml but it was unsuccessful, however, I was able to replicate the bug. So I use Moonlight to stream my games to my tablet and Vita and I remembered that the hangup started when i tried to use it with Mesen. When I attempted to stream it the emulator would hang and I would be forced to close it on my computer. Usually when I launch it from desktop after closing Moonlight it would be fine but in this case it seemed to still exhibit the same behavior as when I was streaming

**Comment by SourMesen** [comment]
Thanks for taking the time to test this. I managed to get GameStream working on my end and tried to use it with Mesen, and it freezes on my end too.

This looks like it might be a bug in GameStream itself, it's hard to say.  GameStream appears to be overriding the XInput library, presumably to hook the gamepad to the client's gamepad (e.g the Vita's buttons in your case).  Whenever Mesen's code calls the XInputGetState function of the XInput API, which normally returns the controller's state, it freezes (because XInputGetState ends up running code in NVidia's library (rxgamepadinput.dll), which never finishes executing).

It's very possible something about the way Mesen works is causing this freeze, but I don't really have any specific idea as to why that would happen.  It's fairly unlikely to be a Moonlight bug, though, but it could potentially be - the only way to know for sure would be to use an NVidia Shield instead of Moonlight and seeing if the bug occurs in that case.

As it is though, I can't really find any specific information about this, so I'm not sure how I could fix the freeze.

**Comment by SourMesen** [comment]
Tested this again with the latest nvidia drivers installed and gamestream on my PC + moonlight on another PC and it seems to be working fine now.  I'm assuming something was changed in the way gamestream works (or potentially I changed something, but unsure)
