### ISSUE TITLE
MultiTap for Translated Games?

### ISSUE THREAD

**Issue by newoski** [SourMesen/Mesen#389]
I've got Multitap working fine, with native Famicom games, however, it doesn't work for the English patched translations -- soft and hard patched. I'm fairly certain it's due to the CRC not matching the list FCEUMM uses to "enable" MultiTap.

If I provide the CRCs, would it be possible to add CRCs for the 8 or so translated games that use MultiTap?

**Comment by newoski** [comment]
Or an enable/disable option?

**Comment by newoski** [comment]
To be clear, I see the Four Player Adapter under P5, but I don't see any way to designate the system to Famicom...

**Comment by SourMesen** [comment]
You didn't mention you were using libretro, so my original reply was meant for the standalone build.
Setting P5 to Four Player Adapter and then configuring P3 & P4 as standard controllers (instead of auto) should work for the libretro port (assuming the rom hacks expect the Famicon version of the 4-player adapter)

**Comment by SourMesen** [comment]
Let me know if you still can't get this to work, for now, I'll assume it's working as expected.
