### ISSUE TITLE
Audio issues after the latest Windows 10 update? 

### ISSUE THREAD

**Issue by SpecsPL** [SourMesen/Mesen#390]
I've been using Mesen as my go-to NES emulator for a few months and it worked perfectly fine up until a few days ago when audio started popping and crackling for seemingly no reason. I've tried pretty much every obvious solution I could think of (re-installing sound drivers, fiddling around with Mesen's audio latency, changing sample rate, muting ultrasonic frequencies on the triangle channel) and nothing worked. I've been having those issues ever since I updated my OS a few days ago, no clue if it's related.

**Comment by SourMesen** [comment]
The audio code in Mesen is probably not the most robust thing on the planet, unfortunately.
Since you said you recently updated, are you running Windows 10 build 1803 (aka the "April 2018 Update")?  You can check by running "winver".
I'm still running the previous version (1709) on my end and haven't noticed any issues, but I know some people appear to experience sound issues on some setups.

Windows 10 also has a number of options like game mode, or the power options which may have an impact on this (e.g using the "balanced" or "power saver" power plans might have an impact, vs using "High performance", etc.)

**Comment by SpecsPL** [comment]
Just checked, I'm running build 1803. Changing Windows' power plan to "balanced" doesn't fix the issue, unfortunately. Also, it doesn't seem like I can run Mesen under the game mode.

**Comment by SourMesen** [comment]
Searching a bit around on the web, I did find this: https://www.reddit.com/r/Windows10/comments/89opoz/does_spring_update_1803_fix_any_of_the_audio/dwsdnfc/
So it definitely seems plausible that 1803 caused the problem to appear.

I also saw someone on Twitter that described the similar symptoms you gave (sound suddenly not working properly).  They said they had tried older versions and they all did the same thing, despite all of them working previously.  So it's possible that this was caused by a Windows update on their PC, too.

If I have the time, I might try to force my PC to upgrade to 1803 (doesn't do it on its own even if I check for updates, at the moment) over the weekend and see if I can reproduce the issue on my end.

**Comment by SpecsPL** [comment]
It's OK, take your time. For all it's worth, the Mesen core in RetroArch works perfectly fine.

**Comment by SourMesen** [comment]
Any chance I could get you to try [this build](https://www.mesen.ca/MesenSoundTest.zip) out?
I still haven't upgraded my system, but I do still get slight distortion in the music at times even now.  This build changes a number of things (mostly the sum of a bunch of different things I tried), but at the very least it appears to solve the static sounds I could hear on my end.

You'll want to raise the value you're using for the audio latency setting - this build changes the meaning for the latency field.  Before the latency was pretty much "minimum of [latency setting] ms + whatever time it takes the sound card to actually start playback", whereas now it's the actual latency between what's playing right now and what's still available in the buffer.  In my case, before it didn't give me too much issues with something as low as 20-25 ms, whereas now I have to set the field to 55+.  The real latency in both cases should be just about the same, though.

This build also spams the log window with debug information.  Normally it should stick to saying "Normal speed", but it will probably also sometimes write "Going too slow, speeding up" or "Going too fast, slowing down" when the emulation is deviating too much from the latency target (it tries to stay within +/- 10% of it).  If you're always seeing "going too slow" or "going too fast", something isn't working right.

**Comment by SpecsPL** [comment]
I've tried the build you posted and audio sounds completely distorted, even more so than in the official builds. The log window usually says that the sound is either too fast or too slow, depending on what latency I'm using.

**Comment by SourMesen** [comment]
Thanks for testing - I guess the issue must be somewhere else.

Just to be sure, could you try running this utility while Mesen is running?
https://docs.microsoft.com/en-us/sysinternals/downloads/clockres

You'll need to run it from a command prompt to see the output.
It should look something like this:
```
Clockres v2.1 - Clock resolution display utility
Copyright (C) 2016 Mark Russinovich
Sysinternals

Maximum timer interval: 15.625 ms
Minimum timer interval: 0.500 ms
Current timer interval: 0.500 ms
```

If you could tell me the values it gives on your computer, it might help in figuring out what the cause is (or at least, it will let me exclude this particular setting as being the source of the problem).
If the "current timer interval" is high (e.g 5-10+ ms), it's pretty likely to cause issues.

**Comment by SourMesen** [comment]
Could you give this build a try and see if it changes anything compared to 0.9.5?
https://www.mesen.ca/MesenTimerResolution.zip

Basically, it forces the timer interval (what I was talking about in the previous comment) to be at least as low as 1.0 ms while a game is running in Mesen - this could potentially help the audio issues on your end.

**Comment by SpecsPL** [comment]
Actually, that may be it! I'm testing it right now, and so far it works perfectly fine. If something happend, I'll let you know ASAP.

**Comment by SourMesen** [comment]
Glad to hear that seems to have fixed it!
Also, since I do want to change the sound code a bit to add the improvements I had done in the first build I sent you, could you try this build out to see if the audio still works properly on your end with it?
https://www.mesen.ca/MesenDebugInfo.zip

This build changes the meaning of the latency field like that previous build, so you'll probably need to set the latency to 55+ms for it to work properly.

It adds a new shortcut key in Options->Preferences->Shortcut Keys called "Toggle Debug Information".  Assign a key binding to it and press it to display some information about the sound/video output.
In the on-screen debug information, the latency should be near what you set it in the audio config (+/- 2 ms or so) and the "Underruns" value should be 0 (or very near 0).

The latency might start off a bit higher than normal when you load a game, but it should slowly get closer to the latency value you set over a few seconds.  If "Underruns" keeps increasing, you can probably hear static sounds each time it does - if this is the case, try increasing the latency setting a bit more to see if it solves the problem.

If you're able to keep underruns at pretty much 0 at a decently low latency, it should be working fine.

**Comment by SpecsPL** [comment]
I've tested the build you posted, it works fine for me. I've managed to keep the underruns value at 0 by setting the latency at around ~60 ms. I can still hear some very minor popping sometimes, but at this point I'm pretty sure it was always there and I just didn't notice it.

**Comment by SourMesen** [comment]
Popping can sometimes be caused by the game itself (since the NES outputs audio at a ~1.8mhz sample rate, which needs to be resampled down to 48khz, some games do things that end up sounding like static or popping due to the resampling).
I'll consider this one fixed then - thanks again for testing!
