### ISSUE TITLE
Duplicate key bindings when Steam is running

### ISSUE THREAD

**Issue by ImJezze** [SourMesen/Mesen#392]
I have a really strange behaviour when the Steam client is running in the background/system tray.

When I configuring the controller and press a button or axis on my controller, two keys are set. One of my controller and one of my keyboard.
e.g.
When I press axis-up on my controller, **Joy1 Y+** and **Arrow Up** will be set
When I press button A on my controller, **Joy1 But1** and **Enter** will be set

There seems to be a conflict between Mesen and Steam. I checked Mesen versions back to 0.5.1 and I think the conflict is very old. In older version before 0.9.3, the issue was not quite obvious because either **Joy1 Y+** or **Arrow Up** was displayed as button label, but since 0.9.3 both keys are displayed.

When I close the Steam client everything is fine.

**Comment by SourMesen** [comment]
Can you show me a screenshot of the issue in Mesen? It shouldn't even be possible to have 2 different keys shown in the same mapping button in the UI.

I have the Steam client running in the background as well and don't have any issue - I can only imagine that your Steam configuration (or some plugin/etc that you have enabled) is remapping your controller buttons to be keyboard buttons presses?  I'm not familiar enough with Steam to know what could be causing this in particular, though.

**Comment by ImJezze** [comment]
I also think that some Steam key bindings cause this conflict, because I can control the client with keyboard and gamepad. But it must be something I haven't actively configured, at least not that I know of.

![key_binding_issue](https://user-images.githubusercontent.com/11963815/40577627-0c5316b8-6109-11e8-86a8-143b7759f4e6.png)

The issue is not always reproducible, sometimes only one key is displayed.

**Comment by ImJezze** [comment]
I found the setting in Steam that causes this issue.

**Big Picture Mode** > **Settings** > **Controller Settings** > **Generic Gamepad Configuration Support** was activated.

I also checked the controller configuration of other applications and some (not all) of them have this issue too.

**Comment by SourMesen** [comment]
Thanks!  I managed to reproduce this on my end too (with the Xbox controller option, since this is what I have).  When this option is turned on, Steam appears to send both keyboard & gamepad buttons at the same time when a gamepad button is pressed.  I'm not sure why Steam does this across the entire OS, rather than just Steam itself (and software launched by Steam's interface).. It's not too surprising that other programs have issues with it, too.

I've mitigated the issue by making it so that you can't have mixed Keyboard+Gamepad mappings (8fc489a08df8db5f3895de782042d0404c34716e).  If both keyboard & gamepad keys are pressed at the same time, only the gamepad key will be used.  This solves the UI issue (and solves issues when trying to bind keys in Preferences->Shortcut Keys), but it's not perfect.  In the background, whenever you press Up on the gamepad, Steam will continue sending the "Up Arrow" keyboard key, for example.  So if you have another binding setup for the "Up Arrow" key, both bindings will be triggered at the same time.  There isn't really anything that I can do about that part, though.

**Comment by ImJezze** [comment]
Thank you for your further investigation. Your solution is absolutely sufficient and the real problem is clearly on Steam's side.
