### ISSUE TITLE
Jerky Animation

### ISSUE THREAD

**Issue by bwroga** [SourMesen/Mesen#397]
I am experiencing intermittent jerky/stuttering scrolling/animation when playing Super Mario Bros. and Super Mario Bros. 3. I have not tested any other ROMS. The problem occurs on both Ubuntu 16.04 and Windows 7, but seems to be worse on Windows 7.

My computer has a 8 core 2.8 ghz processor, a GeForce GTX 950 graphics card and 6 gb of RAM. On Ubuntu, I am using the proprietary drivers.

**Comment by SourMesen** [comment]
What specific CPU model is it? Is this a laptop?  I'm not aware of any desktop CPUs that have 8 cores and are clocked at 2.8ghz (unless you are talking about an older i7 CPU that has 4 cores + hyperthreading)

Did you try turning on/off vertical sync to see if it makes any difference?

**Comment by bwroga** [comment]
Yes, sorry, that's what I meant...4 cores with hyperthreading. It is an Intel i7 930 
![screenshot from 2018-06-05 13-30-12](https://user-images.githubusercontent.com/871094/40992363-9904a17c-68c4-11e8-889c-edf1eb67ca4f.png)
in a desktop computer.

I tried turning on vsync, but it didn't seem to make a difference.

**Comment by SourMesen** [comment]
It seems surprising that both OSes have similar issues.  I used to run a similar CPU until just a few months ago and never had these kind of issues, with both AMD & nVidia cards (or maybe I just never noticed it?)

I'm not overly familiar with Linux, so I have no idea if there's an equivalent to this, but at the very least, could you check the clock resolution settings you have on Windows?  You can use this tool to check: https://docs.microsoft.com/en-us/sysinternals/downloads/clockres

Also, you didn't say anything about the audio - is it running smoothly on both OSes despite the video output not being great?

**Comment by bwroga** [comment]
There are no problems with the audio.

I'm almost wondering if it looked like this on my original NES, but since it was on an old TV, it was blurry enough that it wasn't noticeable? The games are definitely playable, it's just a little distracting.

![capture](https://user-images.githubusercontent.com/871094/41118662-96ab5ab0-6a5e-11e8-9150-cef8f357675b.PNG)

**Comment by bwroga** [comment]
I hadn't tried enabling vsync on Windows. I just did and that seemed to fix the problem.

**Comment by SourMesen** [comment]
Thanks for testing!  It sounds like the timer interval might definitely be part of the problem here.
Could I ask you to try this build of Mesen? https://www.mesen.ca/MesenTimerResolution.zip
(this build will only work on Windows - the Linux binaries aren't included in it)

This build will automatically request a 1.0 ms timer interval whenever a game is running, which should hopefully improve the video's smoothness compared to the 15.6 ms timer your computer seems to be using by default.  If you could try it both with & without vsync to see if it helps, that'd be great.

This is actually something I meant to add to the code ages ago, but never got around to it.

**Comment by bwroga** [comment]
The new build behaved the same. When vsync was off, there was intermittent stuttering, when it was on the game was smooth.

**Comment by SourMesen** [comment]
Alright - thanks for testing!
I guess it might just be a matter of needing vertical sync for it to work properly on your system.

Speaking of which, while looking into some other timing-related stuff, I noticed that I never implemented vertical sync in the Linux build - the option currently has no effect.  This should be fixed by 683ed7e42bd4dd7d1694971590f3ea9c4f7d7aa0, though - so you should be able to use vertical sync on on Linux in the next release.

**Comment by bwroga** [comment]
Awesome! Thank you.
