### ISSUE TITLE
screenshot functions is not good

### ISSUE THREAD

**Issue by zkdpower** [SourMesen/Mesen#400]
**# when i take a screenshot under xBRz or other filters,the effect are always not good,it seems like thick scanline over the picture.**

**Comment by SourMesen** [comment]
I'm not sure if I'm understanding the problem correctly - saving screenshots with any filter appears to be working properly.  I did find a minor issue when using the "scanlines" option with those filters which would cause the pixels in the PNG screenshot to be fully transparent, which might be what you were describing? If so, this is fixed by 6d4afaac995b604716f04d74fb57db5dbe21ce2a
