### ISSUE TITLE
Suggestion : RGB / Hex codes for Color Picker

### ISSUE THREAD

**Issue by raousoft** [SourMesen/Mesen#415]
Hi , Thank you for this amazing emulator.

I would like to see an RGB / Hex codes for Color Picker in PPU Viewer > CHR Viewer

it helps me copy the ( last known palette ) colors to other graphic modifiers like CrystalTile2 / YY-CHR...

I attached an image describing (somehow ) the thing under Color Picker .
![mesen_suggestion_hexrgb](https://user-images.githubusercontent.com/37517008/41813659-34328116-7732-11e8-944b-874418c9a1af.PNG)

Unless I am unaware that it exists somehow.Then there will be no need for this Issue.

**Comment by SourMesen** [comment]
You want to see the hex/RGB codes for the currently selected color in the color picker?
It's easy to add if you just want this as read-only information, but since these values depend on the palette selected in Mesen's video settings, it's not really useful information in a lot of scenarios.

I feel like it might make more sense to add a "Copy Hex Color Code" option in a right-click menu on the color picker (and the same thing in the Palette Viewer, too) - would that be good enough?

**Comment by SourMesen** [comment]
I've added right-click options on all palette views in the PPU Viewer to copy to hex/RGB (and the right-click menu itself also shows the code).  The rgb/hex codes are also displayed on the palette tab when you put your mouse over a color (and can be copied with right-click like the other palette views in the other 3 tabs).  The next Appveyor build (e.g in a few minutes) will include these changes.

Hope that helps!
