### ISSUE TITLE
Text Hooker with tile address

### ISSUE THREAD

**Issue by raousoft** [SourMesen/Mesen#416]
the dev build ( MesenDevWin-0.9.5.126 ) have text hooker now , which works like a charm I liked it so much. I can't believe that it saves the mapping , so when I open the rom again , the mapping is the same I used for.

I'd like to point to some of the things about it :

- In some games , they use same ( drawing not tile ) to draw the letter O and to draw the number 0 , in first time I taught that the game uses the same tile to draw both of them ( and I really don't know why they didn't ) , but they use different tiles ( pictures below )

![mesen1](https://user-images.githubusercontent.com/37517008/41820551-688ef2a2-77cb-11e8-9522-2f81f3d99894.png)

![mesen 2](https://user-images.githubusercontent.com/37517008/41820535-36dcd120-77cb-11e8-82ef-82d39352a3f3.png)
![mesen 3](https://user-images.githubusercontent.com/37517008/41820536-370015d6-77cb-11e8-8bfd-74dd6cd26247.png)
![mesen 4](https://user-images.githubusercontent.com/37517008/41820537-37211dee-77cb-11e8-8f7b-e3cc4c7248cf.png)
![mesen 5](https://user-images.githubusercontent.com/37517008/41820539-3741074e-77cb-11e8-8c19-46a6fb317845.png)

I think that the Text hooker is using some kind of OCR to recognize characters right ? I think that can be solved with implementing tile address.

**Comment by SourMesen** [comment]
Thanks for testing it! It's not completely finished yet, but it should work fairly well as-is.

This isn't actually OCR - the mappings are shared across all games, based on the shape of each tile (independently of the color & color indexes).  I went through some games and mapped a lot of characters (both roman alphabet & japanese hiragana/katakana/kanji), which is why it works out-of-the-box for some games.  The mappings that are built into Mesen are stored here: https://github.com/SourMesen/Mesen/blob/master/GUI.NET/Dependencies/CharacterMappings.txt
Any mappings you change in the UI on your end are stored in your settings.xml file.

That being said, the "zero" vs "letter O" confusion can't really be fixed, it's a trade-off being simplicity (for the end user) and perfect accuracy.  As is, you only have to map specific letter shape a single time, and it will work in all games that shared the same font for that letter - this wouldn't be possible if the mappings were based on the tile's index.  Also, if the "zero" and "O" are identical, some games could easily share the same tile index for both characters (which would be impossible to solve, no matter how its implemented)

**Comment by raousoft** [comment]
Hummm .. I don't understand the part of the tile address ( I apologize for my little knowledge )

For example if 0 is in address 01B0 and the letter O in 00F0

then for example another TextBox under the mapping to enter address

like this I can map 0 to the tile 01B0 and map O to 00F0

Even in the condition of having them both using the same tile , then the same address for both.

**Comment by raousoft** [comment]
I think you made the point , thanks for the explanation :D
