### ISSUE TITLE
Android optimization

### ISSUE THREAD

**Issue by Lululalu** [SourMesen/Mesen#418]
I tried to run mesen on my Android Device trough RetroArch, and it was not a very nice experience. It was slow, unplayable. Other NES emulators ran fine, at full speed. My device is a Samsung Galaxy A5 2017. It's not a slow entry level device. Is it normal? Does it needs to be optimized yet?

Thank you for the attention.

**Comment by SourMesen** [comment]
Mesen is far slower than the other NES cores (FCEUmm/Nestopia both run 2-3x faster than Mesen, depending on their settings). I get ~30fps on my Nexus 5 phone, so this is more or less "normal".

It's possible that the android build is abnormally slow for some reason (e.g because it's not running on a x64 CPU), but I don't really have the time or tools to try to investigate this at the moment.

The accuracy & features (hd packs, etc.) of Mesen do come at a price in terms of performance. I'm sure it would be possible to optimize the code further, but I'm unsure if it is possible to make any major gains without an excessive amount of effort.

At the moment I'm considering the Android build to be a bonus - if it works & runs on your device (some devices can run it properly), great, but I won't be trying to optimize it specifically.

**Comment by zerojay** [comment]
Just a note here for anyone that comes here in the future: I can't even get 60fps on my Nvidia Shield 2017.
