### ISSUE TITLE
Problems with internal resolution.

### ISSUE THREAD

**Issue by EmuMonkey** [SourMesen/Mesen#419]
Hi kind developer of Mesen.

I'm having a problem with getting the internal resolution to stretch to fullscreen on my 17:3 inch notebook screen.

My screen is a high dpi resolution screen (3840x2160), But when setting the aspect ratio to 16:9 the right side of the screen is just black and the resolution dosn't stretch to fill it.

I've been trying all aspect ratio settings and no matter how i try to scale the screen it just stays like that, I've also tried to check the box override dpi settings on Mesen's exe file under compabillity.

It's annoying cause it's such a great emulator, Hope you can help me.

**Comment by SourMesen** [comment]
Somehow you're the 3rd person to report this in the last week or so! :)
It's a bug that was fixed a few weeks ago (see #312) - you can use the build I posted there or use the latest Appveyor dev build to fix the issue on your end.

**Comment by EmuMonkey** [comment]
Hi again.

Your fullscreen fix worked perfectly but now i'm getting some error reports from Mesen when i close it.

Attached the error report, Sorry if i'm bothering you.
![capture](https://user-images.githubusercontent.com/40574423/41873055-1c27d52e-78c4-11e8-947b-ed605d235857.PNG)

Regards.

**Comment by SourMesen** [comment]
Thanks - looks like this was a specific bug when exiting Mesen while exclusive fullscreen mode is active.
It should be fixed by cda0a0bdcb5525480784f4b8c71de6fc7273b570
The next appveyor build should show up here in a few minutes and contain the fix: https://ci.appveyor.com/project/Sour/mesen/build/artifacts

Let me know if you find anything else!
