### ISSUE TITLE
Dragon Quest IV (CHS)(waixing) crash

### ISSUE THREAD

**Issue by ckmop** [SourMesen/Mesen#42]
Dragon Quest IV (CHS)(waixing) crash

rom: http://pan.baidu.com/s/1o8ctNRk

![dq4chs crash](https://cloud.githubusercontent.com/assets/4145768/18621306/bbaad906-7e53-11e6-9592-bcd17bf2d2ed.JPG)

**Comment by SourMesen** [comment]
Thanks for the bug report!  I'll try and fix this when I get back from vacation in a couple of weeks.

**Comment by dragon2snow** [comment]
this rom is encrypted.only working symnes.

**Comment by SourMesen** [comment]
That is what I was about to say, as well.  I'm not sure if there is any way to detect the encrypted roms? No emulator seems to do it.

I did find a couple of bugs with the code for mapper 245 with the unencrypted rom, though.  I'll close this bug after I commit my fixes for mapper 245.

**Comment by SourMesen** [comment]
Mapper 245 issues have been fixed by 7cf5696, which solves crashes with some games.

The specific rom in this report is an encrypted rom meant to only work with a specific emulator (smynes) - no other emulator supports these roms, as far as I can tell.  I do not plan on adding support for these encrypted roms in Mesen.

**Comment by ckmop** [comment]
I see, thanks anyway 👍
