### ISSUE TITLE
DevWin-0.9.5.135 crashes on exit

### ISSUE THREAD

**Issue by Cibomatto2002** [SourMesen/Mesen#421]
In full screen or window it will crash.

Windows 10 Version 1703

**Comment by SourMesen** [comment]
I can't reproduce this.  It might be caused by an option you have enabled/disabled?
Do you get a popup with a crash message, or is it just windows saying that the application has crashed?

Can you try older appveyor builds (https://ci.appveyor.com/project/Sour/mesen/history) to try and see when the crash started?

**Comment by Cibomatto2002** [comment]
I went back to DevWin-0.9.5.101 and it's still doing it I even deleted the Mesen folder in Documents i'm going to guess that it has something to do with setting up my gamepad Mesen 0.95 did not have this bug. here is a video on it.  Here is my settings file.
[settings.zip](https://github.com/SourMesen/Mesen/files/2143187/settings.zip)


https://www.youtube.com/watch?v=Vjkd7tyUPdI&feature=youtu.be

**Comment by SourMesen** [comment]
Looks like it ends up in an infinite loop which freezes the application.

Could I ask you to try some of these older builds to see if they have the same problem?
https://www.mesen.ca/MesenJun9.zip
https://www.mesen.ca/MesenJune5.zip
https://www.mesen.ca/MesenMay31.zip
https://www.mesen.ca/MesenMay26.zip

**Comment by Cibomatto2002** [comment]
All of those crashed for me.

**Comment by SourMesen** [comment]
Uhm.. starting to run out of ideas about what commit might cause this :\

What about these even older builds?
https://www.mesen.ca/MesenApr15.zip
https://www.mesen.ca/MesenApr09.zip
The build from april 9th is only 12-13 commits after 0.9.5.

Also, do you need to configure your controller like in the video for the crash to happen?

**Comment by Cibomatto2002** [comment]
MesenApr09 brings up this. I thought it had something to do with the controller but it don't.
![capture6-27-2018-7 10 14 pm](https://user-images.githubusercontent.com/21169038/42006163-e8ab7c52-7a3d-11e8-8f34-74ebb7b7936d.jpg)

**Comment by SourMesen** [comment]
Ok, I think I have an idea what might be causing it (although it's odd that I can't reproduce it). I'll let you know once I have a potential solution - thanks for taking the time to test this!

**Comment by SourMesen** [comment]
Could you test if this build still causes the crash/freeze on your end?
https://www.mesen.ca/MesenPotentialFix.zip

**Comment by Cibomatto2002** [comment]
Still crashes.

**Comment by SourMesen** [comment]
Starting to run out of ideas as to what might be causing this :\

When it says "(Not Responding)" in the title bar, can you open up task manager, right-click on Mesen and do "Create Dump"?  I should be able to see what's causing it to freeze if you send me that dump file (you might need to email it or host it somewhere because of size restrictions, though)

**Comment by Cibomatto2002** [comment]
here is a link I hope it will help you if not I will make another DMP File sometimes there bigger than other times. https://mega.nz/fm/uuBWGACC

**Comment by SourMesen** [comment]
I can't seem to download that file - clicking on it doesn't lead to any download link.  Maybe there's something you need to do to get a shareable link?

What are you doing to cause the freeze then if it's not clicking on the red X?

**Comment by Cibomatto2002** [comment]
The red X is the only way I can exit Mesen. Try this link.

https://mega.nz/#!oHxl3AAZ!0s0dSc-juU4Z3KRWm_OTTExwUy3dhmV8ljuUOYsEFvM

**Comment by SourMesen** [comment]
Thanks! The dump was very helpful.  The changes I did yesterday were a good start, I was just missing one tiny line of code.

I'm fairly confident that this build should fix it: https://www.mesen.ca/MesenPotentialFix2.zip
If it doesn't, please take another dump with this build and send it my way.

**Comment by Cibomatto2002** [comment]
Thanks a lot it's working now. Can you tell me what happen?

**Comment by SourMesen** [comment]
Awesome - thanks for the confirmation.

Essentially, it was a deadlock. The UI was telling the emulation core to shutdown, which caused the emulation core to warn the UI that it was shutting down, which caused the UI to do some cleanup.  But since the UI thread was already waiting for the core to shutdown, it can't do that cleanup.  So the core is waiting on the UI, and the UI is waiting on the core - and there's no way to get out of it.

The cleanup part was *supposed* to get skipped in this scenario, but I half-broke this in a commit (on april 10th, while trying to fix another deadlock situation that I created on april 9th), making so it was random (based on the timing) whether or not it would get skipped or not.  On my computer, apparently, it always got properly skipped (and so it never locked up) whereas on your computer it apparently never got skipped, so the code always locked up.

With the new code, it's guaranteed to always be properly skipped, avoiding the deadlock (while also avoiding the original deadlock issue I had in the first place)

**Comment by SourMesen** [comment]
Fixed by 9bcde891885c7be99e4dbed37a914394fa688470
