### ISSUE TITLE
Name Table ScanLine & view tile in CHR , Issue

### ISSUE THREAD

**Issue by raousoft** [SourMesen/Mesen#425]
Hi dear Sour,

We talked about the Name table in this issue

https://github.com/SourMesen/Mesen/issues/414

and you suggested that I have to change scan line , and it really helped me thank you a lot.

but I am stuck with another issue , when I change scan line , and try to use View Tile in CHR , it doesn't work ( literally it displays the wrong tile ).And even for scan line , when I pause the game , I change to CHR tab then back again to Name Table and the picture is corrupt again until I un-pause the game.

Here is a video that show somehow the issue :
https://youtu.be/H1mQyGOu5_w

Like this I am never able to get the right tile , even for the tile address it's not correct ,

What I hope at least is , a solution that can be done , cuz I am affraid that logically there is no fix for that ? or I prefer to say that I really don't know how to fix it !

**Comment by raousoft** [comment]
When I go to CHR Viewer ( window ) and choose a tile , then switch to Name Table ( window) , nothing happens , sadly I think it's a logical problem that can't maybe be called a problem.

**Comment by SourMesen** [comment]
I've (mostly) fixed your original issue in b3ef52fcd4e577d6ff98ab40d31d9565d04292a8 and 69bc8a0087e3c9cae8837809353d7798945ee247.
Make sure you turn off "View->Refresh on pause/break" and it should behave as you would expect, for the most part.
If you change the CHR viewer's settings, it will need to reload the chr data from the core, which might change the data shown (there is no way around this). If you really need this, you will need to break the execution at the correct scanline/cycle using the debugger, instead of using the emulator's pause button.
