### ISSUE TITLE
Problem about playing NSF file

### ISSUE THREAD

**Issue by smc031** [SourMesen/Mesen#43]
Cannot play some nsf files used sound chip.

no sound : [Sangokushi 2 - Haou no Tairiku.nsf](http://www.zophar.net/fileuploads/3/24191ipdnx/Sangokushi%202%20-%20Haou%20no%20Tairiku.nsf)
out of sync :  [robokabuto_-_yoshimune_soko_ni_aru_kamo_shire_nai.nsf](http://famitracker.com/forum/attachments/32325/robokabuto__yoshimune_soko_ni_aru_kamo_shire_nai.nsf)

**Comment by SourMesen** [comment]
Thanks for the bug report, I'll investigate this once I get back home from vacation.

**Comment by Cibomatto2002** [comment]
This one will not play. Maybe it's got the same problem 
[Gumshoe (1986)(Nintendo R&D1)(Nintendo).zip](https://github.com/SourMesen/Mesen/files/499719/Gumshoe.1986.Nintendo.R.D1.Nintendo.zip)

**Comment by dragon2snow** [comment]
Sangokushi 2 - Haou no Tairiku.nsf is bad! paly address is D8D4!

**Comment by dragon2snow** [comment]
![qq 20161011205229](https://cloud.githubusercontent.com/assets/4350811/19406790/8a32b6ec-92c0-11e6-8fc9-5d7719e747d4.png)

**Comment by SourMesen** [comment]
I took a look at this a few weeks ago (for the Robokabuto file), and it looked like it may be an issue with the MMC5 sound chip's code.  It does look like a bug, so I'll try to fix eventually.

The Sangokushi file seems to be incorrect, like dragon2snow said, so there's nothing I can do about that part.

**Comment by SourMesen** [comment]
I finally took some time to try and figure this one out.
Turns out the robokabuto song was not out of sync - it only sounded that way because the MMC5's square channels' volume was way too high.  I've adjusted the volume to be similar to the NES' square channels (which is what it should be according to the NesDev wiki), and it removes the impression that the sound is out-of-sync in the NSF track. (51be9b825d5669bf2496dcfd71b437a066b026aa)
