### ISSUE TITLE
Suggestions and weird crash

### ISSUE THREAD

**Issue by Moodie92** [SourMesen/Mesen#431]
i am a noobie , have no experience in  any form but i have three suggestion for the ui
1- adding library view like mgba or citra or dolphin emulator beside the current view or make it optional
![screenshot 1](https://user-images.githubusercontent.com/40892036/42380936-d2844e56-812f-11e8-982a-6bc2f5e3cdc9.png)
![screenshot 2](https://user-images.githubusercontent.com/40892036/42380943-d8cda7bc-812f-11e8-8120-9342b2f3f46c.png)

2- if you dont the idea of the library view , what about adding option to delete the previous opened game by clicking right click , currently right click just like the left click opened the game or at leasts add close button to remove the game 
![grrgrg](https://user-images.githubusercontent.com/40892036/42380427-2ce2ed28-812e-11e8-82db-03ef8b0ac1ef.jpg)
![qwfwqfqwfq](https://user-images.githubusercontent.com/40892036/42380852-927af3d2-812f-11e8-97fe-0c0ad6b630c4.jpg)

3- to have the choice to star or pin  to bookmark the game as favourite will be a nice addition
![dsadad](https://user-images.githubusercontent.com/40892036/42381004-0405aa06-8130-11e8-8447-167529786a89.jpg)
![fqwfqwfqwf](https://user-images.githubusercontent.com/40892036/42381005-05b5ca84-8130-11e8-84be-628353bb6774.jpg)

beside that emulator is a thing of beauty <3

**Comment by Moodie92** [comment]
i think its not important issue , its just for easy access  to favorite games

**Comment by Moodie92** [comment]
last thing and sorry for any annoyance mr sour :) , i watched cinemassacre played nes game and uses game genie , then when i play  ninja gaiden i though mesen implement this feature and  after a  little search i was wrong i found game genie cartridge on the web , if this cartridge is not copyrighted , why it is not implemented a mode in mesen like changing sides in fds game , and if its copyrighted material . how to use the game genie with mesen ?? 
![fqwqwfqwf](https://user-images.githubusercontent.com/40892036/42736161-a8405174-8861-11e8-84ef-001002b222aa.jpg)

once again sorry for bothering

**Comment by SourMesen** [comment]
Thanks for the suggestions/bug report - I'll take a look at the mario/duck hunt issue when I have a chance.
For game genie, Mesen doesn't support using the original game genie ROM, but it supports adding game genie code through the cheats window (Tools -> Cheats).  It also contains a fairly large database of cheats that you can import using the Import button.

**Comment by SourMesen** [comment]
The crash when resetting the SMB+Duck Hunt+Track Meet game is fixed by 626107bc7239fb3ea1460e8b852c668c9f706f59 - thanks for reporting that!

As for the bookmark/favorite idea, the current recent game screen isn't really appropriate for this - if you were to bookmark/favorite multiple games, you'd still only see one of them (and then how would it show the most recently played game?).  The layout would need to be changed to show multiple games (e.g at least 6+), but this is hard to do while also keeping a small minimum window size (which is why it currently only shows one).

A folder list view sounds nice in theory, but in practice, some people dump the entire NES library (thousands of roms) in a single folder because the roms are tiny, so it's a bit hard to manage, too.  Either way, I'll keep note of it as a possible improvement, but will probably not have the time to improve this anytime soon.
