### ISSUE TITLE
Game Genie Request

### ISSUE THREAD

**Issue by Cibomatto2002** [SourMesen/Mesen#436]
Could you make it so we can add more than one code in the Game Genie Code box? Maybe make it something like this GZUYEZEP+GZKNSZEP This code is for the game Bubble Bobble 2 (USA).

**Comment by cyrilleCh** [comment]
you can create and combine as many codes as you want

**Comment by Cibomatto2002** [comment]
You can only add one Game Genie code at a time. See how this code is Bubbles Hit Anywhere it takes to codes to make it work it was be nice if you could just add more Game Genie code boxes so I could just put both codes on the same line.

**Comment by SourMesen** [comment]
I can't really think of any simple way of fixing this that doesn't involve a more complex UI.  If I were to add 3 boxes for the game genie in the cheat window, I would also need 3 boxes for the other 2 ways of adding cheat codes (since any method could equally benefit from this).  But there's also no real limit to the number of codes a GG code could be made of (you could come up with some effect/cheat that requires 6 of them, for example).

Considering it's a relatively infrequent use case, I think I would rather keep the UI and the code as simple as possible, rather than complexify both just to keep the codes together in the cheat list.

Also, I am eventually planning to add automatic conversions of the codes (e.g type in a game genie code and it will fill in the "custom code"/PAR fields to match the code (whenever possible)) - so adding multiple GG code fields would get in the way of that feature.

**Comment by Cibomatto2002** [comment]
Oh ok I was thinking it would be a easy thing to do it was something I did not really need anyways. Keep up the good work. :)
