### ISSUE TITLE
Using NTSC Bisqwit filters overrides selected palette

### ISSUE THREAD

**Issue by 84L7H13R** [SourMesen/Mesen#463]
Title says it all.  I noticed this while playing with the video settings.  Using the default built-in NTSC filter with a custom palette or even the built-in palettes works as expected.  But the bisqwit filters always output the same colors regardless of which palette is selected.  Those filters also stretch the video to the right a little bit and so the right edge of the screen gets a little cut off.

**Comment by SourMesen** [comment]
The palette not being applied to the Bisqwit filter is the expected behavior.  Unfortunately, the code for it doesn't support applying a palette, and I wouldn't really know how to add palette support to it at the moment (I would need to properly understand both Bisqwit's code & NTSC signal generation in detail, which I don't).

I did fix the cutoff pixels on the right, though, and also fixed the black bar on the left (93427583c769801d7fba32ebac0b078a4a1cd042).
