### ISSUE TITLE
Custom MesenDB Entries

### ISSUE THREAD

**Issue by torridgristle** [SourMesen/Mesen#465]
Spent a few hours trying to figure out why Family BASIC v1.0 wouldn't work with even the smallest and most minor of edits possible, only to discover that the original only worked because it had explicit settings in the MesenDB. After duplicating the entry and changing the hash to match the edited ROM it ran fine, though MesenDB had to be made read-only.

An additional DB file for user-supplied settings would be nice, though honestly probably largely unused.

**Comment by SourMesen** [comment]
Adding DB entries should technically never be necessary so long as a valid NES 2.0 header is used.
The main problem here is that your rom is most likely a headerless ROM.  Headerless .nes roms are nonsense (it's impossible to load a rom without a database if the rom has no header) and shouldn't be used in general, but people keep making headerless rom sets, so Mesen supports them (in hindsight, adding support for them may have been a mistake).  The database's information is used to figure out what the header is supposed to be, which is why it's able to load the original rom.

The best solution is to use the header editor to create a new rom file with the proper header.  In this particular case, these settings should work:
![image](https://user-images.githubusercontent.com/21093973/44061910-45fe2706-9f28-11e8-8e75-f308c1c94219.png)

I just found and fixed an issue with the header editor (e72f8377cd1ede874e30e79ae66a368189019bac) when working with headerless ROMs (the exported .nes file was invalid because of this bug), so should use the latest appveyor build before trying this on your end.

**Comment by torridgristle** [comment]
Thank you, this works perfectly. Absolutely bogus that this needs to be done, but at least it was simple once the problem was discovered.

Does the header editor automatically load the settings from the DB?

**Comment by SourMesen** [comment]
> Does the header editor automatically load the settings from the DB?

For headerless ROMs, it does (but it currently won't set the options 100% correctly if the ROM requires some NES 2.0 header features).  For everything else, though, it will load the header from the original .nes file, instead.
