### ISSUE TITLE
Mesen lacks support for multiple layout keyboards

### ISSUE THREAD

**Issue by Lululalu** [SourMesen/Mesen#469]
I was configuring the controller/keyboard and I noticed that the keys I typed don't match the ones shown. For example, I typed "ç" but Mesen says it is a ";". I believe that if this is fixed Mesen will better support multiple languages/regions. 

Ps: My keyboard is ABNT.

Thank you!

![capturar](https://user-images.githubusercontent.com/32398857/44309747-c1b92a80-a3a1-11e8-884a-5ec8e04044a3.PNG)

**Comment by SourMesen** [comment]
Thanks for the report.  This is only a display issue, though - even if it says ";" instead of "ç", pressing the "ç" key should work properly while playing.

With the way this currently works in the code, I would have to manually add all possible keyboard mappings (there are most likely 50+ of these) in the code to fix the labels - it's not really worth the amount of time it would require.
