### ISSUE TITLE
Some sprites not showing up in Akumajou Special - Boku Dracula-Kun English Translation

### ISSUE THREAD

**Issue by kevzor** [SourMesen/Mesen#47]
Some platforms are not showing up in the translated rom of Akumajou Special - Boku Dracula-Kun. I've attached some screenshots. The first one is with an untranslated ROM in Mesen, where the platforms show up fine.
![akumajou special - boku dracula-kun japan _000](https://cloud.githubusercontent.com/assets/22550990/19005781/9578443e-8719-11e6-8173-fac07b299540.png)

The second is with a translated ROM in Mesen. No platforms for some reason.
![akumajou special - boku dracula-kun japan en by vice v1 04 i m kid dracula _000](https://cloud.githubusercontent.com/assets/22550990/19005823/da9f4b7a-8719-11e6-8cc8-acaeb7e3f25d.png)

The third and final screenshot is with the translated ROM in FCEUX. The platforms show up just fine.
![akumajou special - boku dracula-kun japan en by vice v1 04 i m kid dracula -1](https://cloud.githubusercontent.com/assets/22550990/19005850/0124e99e-871a-11e6-84c6-c4af7e2d3b4a.png)

I've tried downloading different pre-patched ROMs and patching the ROM myself, but I cannot get it working in Mesen.

**Comment by SourMesen** [comment]
Thanks for the report.  FCEUX is not very accurate in general (especially when using the old ppu, which is the default setting).  It is likely the translation would also not work correctly on a real NES.  I can't test this at the moment because I'm away on vacation, but I suspect you would get the same problem with other emulators such as puNES, nestopia or nintendulator.

**Comment by dragon2snow** [comment]
this rom working real fc

**Comment by SourMesen** [comment]
After investigating a bit, this looks like it is normal, and just the result of the iNES format being imprecise.
Both roms are set to mapper 23, but the original game is actually a VRC4 game - Mesen knows this because it contains a database of known games.
However, the patched ROM isn't part of the database, so it runs based on guesses and ends up using VRC2 behavior, which causes incorrect mirroring to be used in this case (and produces the missing platform bug)

The best solution would be to modify the rom file to be a NES 2.0 file with the proper headers to tell Mesen that the rom is a VRC4 game, despite not being in the game database.

I'll keep this bug opened for the moment, in case I can think of a more general solution to fix this.

**Comment by dragon2snow** [comment]
this rom,i write org cart,is working fine!

**Comment by SourMesen** [comment]
Changed the VRC2/4 logic for mirroring to hopefully make it compatible with more games when the emulator has to guess which board the game uses.  This particular ROM should now run properly in Mesen.
