### ISSUE TITLE
Emulate Famicom controllers

### ISSUE THREAD

**Issue by rzumer** [SourMesen/Mesen#472]
[allpads-nes](https://github.com/pinobatch/allpads-nes) relies on different behavior between NES and Famicom controllers in order to detect the correct input device. Currently it seems to always detect NES controllers, so it is not possible to test the Famicom microphone. There is no option to set the emulated console model at least in the libretro core, and there is only one "standard controller" option for input devices. If this functionality is present in the standalone emulator, then it should also be available as an option in the libretro core. Otherwise, this would be a useful enhancement.

**Comment by SourMesen** [comment]
This is available in the standalone emulator, but not something I plan on adding as an option in the libretro core.  I prefer to limit the libretro core to options that are truly useful to play games, rather than adding every single option the core supports - otherwise the option list will become unmanageable and confuse users more than anything.

**Comment by rzumer** [comment]
Since it only affects the usability of test ROMs I will close this, but as an additional controller type in the controls menu it should not introduce much complexity as opposed to extra core options.
