### ISSUE TITLE
Memory Tools: Label QoL features

### ISSUE THREAD

**Issue by torridgristle** [SourMesen/Mesen#488]
When adding a label and you're in the name entry box you should be able to press Enter as a shortcut for clicking Okay. Currently it only plays an error or notification sound from Windows if that's supposed to already be a feature.

Labels are currently limited to one byte. I've got a few situations with 2-byte words used for gold and positions, and that's not uncommon from what I've seen in NES games, so being able to have both bytes marked with the label would help with visual organization.

A pop-out window or box in the Memory Tools window that lists the labels, their locations, and their values, with tooltips for descriptions and locations and such, and an option to hide locations from the list and keep them in the tooltips in case you don't need to know the address every time, would help with navigating the memory without having the entire debugger open. Currently I have to go through my notes to find an address I've already labelled. I expected labels to work a bit more like a bookmark rather than just a name that shows up when an address is mentioned.

Tool tips, like for 2002's label, are clipped within the Memory Tools window. This label specifically has a very large description and in order to see it all the Memory Tools window needs to be much larger than the size you'd need for 16 columns of hex and text. It should float above and the Memory Tools window without clipping to the window edges.

**Comment by SourMesen** [comment]
Pressing enter is fixed - it will act as if the ok button was clicked (except when the comment box has focus).
The rest I will take a look at when I have more time.

**Comment by SourMesen** [comment]
-Multi-byte labels are supported as of 1a84ef8c4fe25c272db49db87fdc8fa7c10aabb2
-The "Go To All" feature first added in ce893167c6bafee6ad3be51b80ec2e7575966f95 can serve as a way to search existing labels and is available from the hex editor window, so that should take care of the request for a pop-out window that lists labels
-Labels with large descriptions will no longer clip (they will wrap instead as of d966fd50c1b6b7fafb4e886708f14e4d7de8404d).  Unfortunately, I can't easily make the tooltips float over the window (they used to!) without making them unusable under Linux, so the current behavior is a compromise.

So I think this takes care of everything that was listed in here :)
