### ISSUE TITLE
Crash Dump, not sure what happened

### ISSUE THREAD

**Issue by torridgristle** [SourMesen/Mesen#495]
https://cdn.discordapp.com/attachments/475089535563464727/485913827804839937/Mesen.exe.21888-CrashDump.zip

I changed a byte in the PRG ROM while it was paused, pressed Ctrl+R, then either I unpaused and Mesen went unresponsive or Mesen went unresponsive immediately, and then Windows faded the windows and gave the option to quit Mesen.

Sorry about not attaching it locally, GitHub file attachments aren't working for me.

**Comment by SourMesen** [comment]
Unsure if I fixed the real issue here, but following those steps I was able to get a crash a number of times.  Fixed the crash in e995c669276fc202df78a217a00876738fab923e, so hopefully the problem is fixed.

I don't have the PDB files for the appveyor dev builds, so I can't get much information from the crash dumps from them, at the moment, unfortunately.
