### ISSUE TITLE
Invisible UI

### ISSUE THREAD

**Issue by realnc** [SourMesen/Mesen#542]
I've built 0.9.7 on Linux (Gentoo 64-bit). I am unable to use the program because the UI is pretty much invisible. I'm using Mono 5.16.0.220 and Clang 7.0.0.

![image](https://user-images.githubusercontent.com/1665903/49871584-4f23fd00-fe1f-11e8-9b6b-92f8647f352d.png)

![image](https://user-images.githubusercontent.com/1665903/49871580-49c6b280-fe1f-11e8-81b0-a51fdc1466c2.png)

**Comment by SourMesen** [comment]
Thanks for the report - I believe I've seen other people talk about this recently, too.

Apparently Mono has issues with dark themes. I'm unsure how easily I can fix this - I might be able to force the color of labels to black (instead of allowing Mono to select the text color based on the current theme), which should fix the problem (at least, from what I can see in your screenshot - might be other scenarios that require further tweaking to look decent)

**Comment by SourMesen** [comment]
This should be fixed as of 1e580651549d58adc6bb97cc8d56b183061ea187.
This involved manually forcing colors that work when a dark theme is detected, since Mono itself does a pretty bad job at it at the moment.

It's not perfect (especially the debugger tools), but should be much more usable than before:
![image](https://user-images.githubusercontent.com/21093973/51797568-f2fd1880-21d3-11e9-8022-1026f8c9b428.png)
