### ISSUE TITLE
Read2004 <--> VBL Timing

### ISSUE THREAD

**Issue by alyosha-tas** [SourMesen/Mesen#547]
In the PPU, VBL begins on cycle 0 of the scanline. However, sprite evaluation seems to start on cycle 1 (so that cycles 1-64 return FF.)

According to the timing diagram on nesdev (http://wiki.nesdev.com/w/index.php/File:Ntsc_timing.png) this means the VBL is being triggered one cycle too early, relative to where sprite evaluation is happening.

Motivation:
I am finding it impossible to reconcile behaviour between NESHawk giving the same results in Read2004 (by varying startup timing) while also giving consistent playback in timing sensitive games. All other tests are passing between the two, so I'm thinking this is the only option.

**Comment by SourMesen** [comment]
Those timings are a bit messy at the moment - vertical blank flag is set on cycle 0, but cleared on cycle 1 of the prerender scanline.  Changing it to cycle 1 (to match the timing diagram) makes one of the PPU timing tests fail, iirc, and I never managed to find any other way to get it to work.  I've been meaning (for literally over a year) to compare with NESHawk's code to try and find a proper answer to this, but always end up working on other things instead :\

**Comment by alyosha-tas** [comment]
Ah, ok thanks, at least I know I'm not going crazy and am looking in the right place.

NESHawk just uses a 'VBLactivepending' flag that gets set one tick before the actual VBL flag. Then $2002 reads can clear either the pending flag or the actual flag.  Clearing the pending flag will stop the flag from getting set.

**Comment by alyosha-tas** [comment]
Well I naively tried moving the VBL flag set forward a tick, but that didn't change the value of read2004 for some reason? Maybe the NMI still happens at the same point so it cancels it out. I still had to have NMI flag set at cycle 0 though. Then all the other tests also still pass, so whatever, maybe it was pointless.

BUT

I finally found the difference between NESHawk and Mesen! Turns out Mesen starts with the 'this is an even frame' flag set to true while BizHawk had it at false. HA!

With this change, I can now use read2004 to match power up timing between the emulators, and now I am getting perfect sync to NESHawk movies, Finally!

I'm not sure I'll ultimately keep these changes in NESHawk, but at least I know after many frustrating hours how to make it all work for future testing.

**Comment by SourMesen** [comment]
Funny, I was just tinkering with this myself and ended up with the exact same "solution" (setting vblank on cycle 1, but triggering NMI on cycle 0) - pretty much anything else I try results in a fairly large number of tests failing.

Really cool that you managed to find that difference!  For what it's worth, it looks like the first frame after reset/power on is supposed to be an "even" frame (according to the wiki anyway).
What timings did you use to make Mesen match up to Bizhawk?  Did it make that one battletoads movie sync up in Mesen, too?

**Comment by alyosha-tas** [comment]
If you set the initial number of cycles Mesen offsets at power on (originally 28) to 45, and set _framecount to 0 instead of 1 in the ppu, then both streemerz movies made in Bizhawk will sync in Mesen. (you can find them here: http://tasvideos.org/forum/viewtopic.php?t=18797)

This is a bit strange, since I only needed to change NESHawk's timing by 5 ppu cycles (not 17) to match Mesen. 

I haven't tried battletoads yet.

**Comment by SourMesen** [comment]
@alyosha-tas
I just pushed some relatively major changes to Mesen's timings.  I've rewritten dmc/sprite dma, fixed the timings of some stuff in the PPU (including the VBL flag, it's set on cycle 1 now) and implemented the glitched scrolling for 2006 writes.

On top of this, Mesen now kind of supports different CPU/PPU alignments.  There's a new option in emulation->advanced to randomize the divider's counters for the CPU/PPU vs the master clock.  e.g the dividers are 12 and 4 on NTSC, so their initial values are randomized from 0-11 and 0-3, which slightly alters the timing of some stuff from one power cycle to another (a lot of tests that are known to "sometimes" fail on hardware fail in Mesen on some power cycles with this)

I haven't tested a whole lot of games since, though, so I could potentially have broken some of the trickier games.

Just letting you know in case - figured these changes could potentially have some impact on the movies between bizhawk and mesen syncing, and might fix/break some runs that work on real hardware, too.
