### ISSUE TITLE
Small inaccuracies on MMC1

### ISSUE THREAD

**Issue by bferguson3** [SourMesen/Mesen#553]
Hi,

I've been testing homebrew on hardware and noticed my console doing these two things that Mesen doesn't (and was causing me some confusion):

- all "empty" data is in fact initialized at $FF, not $00 (specifically, this is for $200-$2ff as I was seeing oam corruption on hardware - it was setting all the empty values which I assumed would be 0, as mesen does, as $ff)

- (edit:) For multi bank games, if the mapper is not reset with a store of $80 to $8000 (ie high bit set) then the state of the banks is unknown. without doing this it appears that it does -not- fix the last bank to $c000 therefore can't find the reset vectors and won't boot the rom. (Unfortunately I'm not sure what the state is on powerup... possible it is retained from last reset but I assume that would have allowed my game to boot, which it didn't.)

Thanks!

**Comment by bferguson3** [comment]
I'm using a real original NTSC NES. Thanks for the option for randomizing,
but with tests I could see it's explicitly 0xff (the oam attribute bytes
behaves exactly as if it were & 11111111 on every fresh power up). An
option to set it all to FF would be more accurate for my experience.

Apologies for confusion, I use 'reset' here synonymously with the reset
vector code (which for me is just my power up code).

Adding the vectors to every single bank did indeed work for hardware, but
this is clunky and imo bad practice, especially since you can't tell which
bank it will look at initially. The only way I got multibank code
*properly* booting at all was as I said to force the mmc1 control to reset.
I can't speak to any other forms than Infinite NES Lives SKROM board but if
you think the emulator is close enough to hardware then obviously you don't
have to change it, just thought you'd like this feedback.

I made numerous changes to my code and organization but Mesen didn't care
at all, whereas I was getting pretty varied results on HW.

Thanks for your response. 🙂

2018年12月24日(月) 12:22、SourMesen さん（notifications@github.com）のメッセージ:

**Comment by SourMesen** [comment]
There is no memory pattern that matches every single NES unit at power on - all of them will have different power on states.  That being said, the same option lets you select $00, $FF or random values already.
The code comment in the Wiki article you linked isn't talking about state of RAM at power on, it's saying that programmers will usually want to initialize the OAM mirror stored in the NES' RAM to $FF instead of $00, otherwise sprites will be shown on the screen.  The OAM mirror is just a frequently used concept, but has no set location in RAM (e.g you could use $700-$7FF for this purpose instead of $200-$2FF) - the $200-$2FF range is not special vs the rest of the NES' RAM.

The problem with the boot up state of the MMC1 is that it ever so slightly changes from one revision of the chip to another.  Especially, the board you're listing is a reproduction, so there is no guarantee it's is 100% identical to any of the original MMC1 chip revisions.  Adding the vectors to all banks is a relatively common practice - it's pretty much required for all mappers which don't have a 100% fixed bank at $FFFA-$FFFF, since the majority of mappers tend to boot up in a random state (aside for fixed banks)

**Comment by bferguson3** [comment]
Good info- Thanks! Also did not know about the extra option, that will be
helpful.

2018年12月25日(火) 8:12、SourMesen さん（notifications@github.com）のメッセージ:
