### ISSUE TITLE
SNES Mouse should only have 3 sensitivity settings, not 4.

### ISSUE THREAD

**Issue by bbbradsmith** [SourMesen/Mesen#559]
SNES Mouse sensitivity should only have 3 states (0,1,2). The fourth possible value (3) is invalid. Setting 0 should follow setting 2.

https://github.com/SourMesen/Mesen/blob/master/Core/SnesMouse.h#L53

**Comment by bbbradsmith** [comment]
Can test this with thwaite: https://pineight.com/nes/#thwaite

Right click while on the menu screen. There will be an icon of lines next to a mouse (if connected). Right click cycles sensitivity setting, and note the icon will be an invalid white and grey "XX" when value 3 occurs.

**Comment by SourMesen** [comment]
Thanks - this is fixed in a78b14e1ab4e82f4a8f73381a1e8220ffb24b6a0.
I had tested this in tepples' allpads test before, but that test doesn't actually complain if you set sensitivity to 4.  Looking at it now, it's obviously meant to only show 3 states, but it shows a 4th one that looks like it might actually be valid when you don't know better.
