### ISSUE TITLE
Libretro: "Automatically insert disks" disabled option not honored

### ISSUE THREAD

**Issue by nfp0** [SourMesen/Mesen#563]
Awesome work on this emulator! But I have a small issue:

I have the "FDS: Automatically insert disks" option disabled in Retroarch but the option does not seem to be honored.
When I start a FDS game the FDS BIOS shows for a few seconds but the disk loading starts immediately afterwards without any button input. Shouldn't I need to insert the disk manually with the corresponding key press?

**Comment by SourMesen** [comment]
The option name might be a little lacking in terms of description, but what this option does is that it automatically switches the disk for you when a game asks for another disk (e.g when a "Switch to side B" screen shows up, it'll auto-insert side B without you doing anything).

There is currently no way to start the emulator in FDS mode without having a disk inserted (in the libretro port, that is)

**Comment by nfp0** [comment]
Ah I see what it means now! Thanks for the clarification.
So, from what I understand, there is no way for me to explore the FDS menu on Mesen in Libretro? Any workaround?

I'll close this issue.

**Comment by SourMesen** [comment]
You're correct, there's no way to see the FDS menu on libretro at the moment.  But as far as I know, there isn't anything there beyond a bit of music/animation until a disk is inserted?  The standalone version has a "Automatically insert disk 1 side A on power on" option, but it's not available on libretro, mostly because I try to keep the libretro list of options down to what's really useful in general (the list would be gigantic and unusable if I tried to include everything Mesen itself supports)

**Comment by nfp0** [comment]
Yeah, that's perfectly understandable.
Thank you for the help and for this awesome emulator!
