### ISSUE TITLE
Problems with multicarts

### ISSUE THREAD

**Issue by Arcus87** [SourMesen/Mesen#58]
Many of roms doesn't launching or writing errors (often problem - Game has crashed - Invalid OP code cpu crashed) Maybe the problem in roms, not in Mesen? The problem is that there 457 roms , in **Multicarts Collection.7z** from **GoodNES**

A big thanks will be if you check and fix games.

**Comment by SourMesen** [comment]
Support for some new mappers has been added since you created this issue (mostly UNIF mappers), which probably fixes some of the multicarts.
There are still about ~30 UNIF boards I need to add support for, so it's possible some multicarts still do not work properly.
I just created #128 to keep track of all issues with unlicensed games.  If you have any specific multicarts that don't work properly and use a mapper that Mesen supports, please post a comment in #128.
Thanks!
