### ISSUE TITLE
Black screen on every game (beta)

### ISSUE THREAD

**Issue by BillyWM** [SourMesen/Mesen#596]
Platform: 64-bit Windows 10

Set to Release, x64. Built solution. Start Without Debugging (Ctrl+F5). No luck on x86 either.

All games have a black screen. Seem to emulate fine - can play game blind if I press buttons, sound works, etc.

Haven't had any problems with official release from website in the past. Did `git checkout 0.9.7` and was able to compile and run fine, screen works. Not a blocker for my purposes, but just a heads up.

**edit**: Just noticed you have pre-compiled dev binaries. I confirmed this with `MesenDevWin-0.9.7.97` from Appveyor. 

In both cases I ensured I made a new config in the current directory

**Comment by SourMesen** [comment]
Thanks for the report!
Someone else had recently reported a similar issue here: https://github.com/SourMesen/Mesen/issues/319#issuecomment-471219068

After spending some time typing a reply and checking recent changes, I'm pretty sure I've found and fixed the issue with cf40b967f438684cc5784d0cf41df11580df201b.  The problem only occurred if you had never tried changing the palette in the video options (so deleting the config file actually causes this problem to appear). If you could try the next appveyor build after it finishes building (in a few minutes) and check if the problem is fixed on your end, that'd be great.

**Comment by BillyWM** [comment]
I did see that one, but filed separately as not to confuse the conversation over there because in my instance there wasn't a solution; hard power cycling or closing+reopening mesen didn't fix it.

But in any case I tried the new build and it is fixed with your change.
