### ISSUE TITLE
Cycle counter rolls over

### ISSUE THREAD

**Issue by BillyWM** [SourMesen/Mesen#598]
Since the cycle counter is an int32 it rolls over into the negative after just 20 minutes of game play. This screws up anything like Lua or trace log parsing doing math on these values. The emulator sometimes does math on these values too, and it seems like it could introduce bugs if you happen to be running the emulator when it crosses the boundary and you're doing something like `runToCycle`

Seems like this should be an int64 (there's only [a small chance](https://www.youtube.com/watch?v=DPfMATdVN-w) someone might run the game for millions of minutes....)

**Comment by SourMesen** [comment]
Thanks, I'm aware of this, and most of the math done on the cycle counter should already be padded to take care of the wrap around.

I have not changed it until now because doing so would invalidate all save states, but since I've already had to invalidate save states between 0.9.7 and now, it might be fairly easy to change (though it would require validating every piece of code that checks/uses the counter, which may be rather frequent).

**Comment by SourMesen** [comment]
This is fixed by 5b80d2fe2153cea4bc3aebd82cc432479d255b2c
