### ISSUE TITLE
Conflation of the MMC3 and MMC6 mappers as iNES mapper 4

### ISSUE THREAD

**Issue by Apocalypse612** [SourMesen/Mesen#610]
There's an issue with using hacked roms with this emulator. I was trying to play Startropics, and I came across this issue below. The original author of the patch is a lot more familiar with this bug than I am, I'm just posting this in hopes for a fix or configuration option to allow support.

"Some emulators, do not support modifications to the StarTropics ROM due to a conflation of the MMC3 and MMC6 mappers as iNES mapper 4. If the emulator has to use a CRC check to select MMC6, it may have problems running the patched ROM (e.g. audio will be silent, and name registration will fail)."

This is exactly what happened to me, the ROM becomes silent, etc. 

Any way to work around this? I'm going to have to use a different emulator that I know that works for now, but trust me when I say I'd like to 100% use Mesen.

Thanks!

**Comment by Apocalypse612** [comment]
Oh, and incase you want a reference point:

https://www.romhacking.net/hacks/2229/

**Comment by SourMesen** [comment]
Yes, you can edit the NES header to set it to NES 2.0 mode and use submapper 1 to indicate that the game is a MMC6 board rather than a MMC3 board.  e.g like this:
![image](https://user-images.githubusercontent.com/21093973/55907716-81fbb900-5ba5-11e9-914e-2634bbfc6293.png)

The editor is available from the debugger's Tools menu (or other standalone nes header editors that properly support NES 2.0 files should work fine too)

Ideally, the romhack could be updated to patch the original .nes file to use these headers, which would allow the hack to work properly on more emulators.

**Comment by Apocalypse612** [comment]
Cool, I'll give this a try shortly. Thanks for the quick response (and the excellent emulator)!

**Comment by Apocalypse612** [comment]
Didn't work unfortunatley. Save problems.

**Comment by SourMesen** [comment]
Whoops, you'll also need to set the "Save RAM" value to 1kb to match the star tropics board

**Comment by Apocalypse612** [comment]
Works perfectly now. You are the man!

**Comment by SourMesen** [comment]
No problem!
