### ISSUE TITLE
.NET Core 3 support

### ISSUE THREAD

**Issue by rogersachan** [SourMesen/Mesen#624]
As .NET Core gets closer to GA I think support for it should be explored since it provides cross platform support and performance boosts. Not to mention that migration will be necessary when .NET 5 is released.

In moving I found these resources useful:
- https://github.com/hvanbakel/CsprojToVs2017
- https://devblogs.microsoft.com/dotnet/how-to-port-desktop-applications-to-net-core-3-0/
- https://docs.microsoft.com/en-us/dotnet/core/porting/winforms

**Comment by SourMesen** [comment]
I'm not sure what this is asking for?

As far as I can tell, .NET Core 3 is due this fall, and .NET 5 won't even be out until November 2020.
In either scenario, though, upgrading to either of them isn't really useful - it either forces users to upgrade their .NET installation (which may sometime not be supported for older OSes) or forces me to distribute the entire .NET Core assemblies along with the program (which would greatly increase the size).

I'm fairly certain it will run as-is in any version of .NET.  And .NET Core 3 will presumably work because of its support for winforms, but I do not plan on changing the target from 4.5 until there is a need to do so.

**Comment by rogersachan** [comment]
Would a pull request to support targeting of .NET Core 3 alongside Framework 4.5 be accepted?

**Comment by spektor56** [comment]
Isn't just the UI of this emulator done in .net?  I don't see the point in changing to .net core 3 when winforms/WPF are still a windows only UI frameworks.  

Changing to .net core only makes sense if the UI framework also gets swapped out.  QML.Net is an interesting project, lets you make QT frontends for .net core projects so it is fully cross platform, Mac, Linux, and Windows.  Of course the dev experience isn't as nice as just using something like winforms.

**Comment by SourMesen** [comment]
Yes, the only part in C# is the UI - switching to .NET Core would not improve performance.  It might ever so slightly improve the refresh performance of some debugger tools, but for the most part, their bottleneck is GDI+ moreso than .NET.

Rewriting the UI to another toolkit is not going to happen - it would probably take months to rewrite every piece of the UI to any other toolkit.  And like you said, the dev experience for WinForms is great (and I have yet to find something that's better), so I'm not too keen on switching to anything else :p

**Comment by SourMesen** [comment]
Closing this for now as I have no immediate plans to support .NET Core 3.  If at some point Mesen being built on .NET 4.5 becomes a problem for users, I will look into migrating to something more recent.
