### ISSUE TITLE
The way FDS games load is very strange.

### ISSUE THREAD

**Issue by ddubs13** [SourMesen/Mesen#632]
I tried to play Cleopatra no Mahou on the FDS with the translation patch. At first, I just loaded the game to make sure it wasn't a bad dump. So then I applied the patch, and suddenly the game crashed on bootup. Ok, I figured maybe I just needed a header or something (it was actually an entirely different issue but w/e). So then I replace the disk image with a fresh copy, and...it wouldn't load. Redownloaded the emulator, it wouldn't load. The base game, without the patch would no longer load. I was very confused. By sheer stroke of luck, I found out that changing the filename got it to work again. That made no sense, but I was trying to get something done so I just rolled with it. So I applied the patch, and once again it failed to load, and replacing the image caused it to crash on bootup again, even with the filename change. Changing the filename even further managed to fix it.

After a lot of back-and-forth between people who used Mesen who had no clue what it could be, I realized Mesen makes IPS "saves" of every FDS game you load into the emulator. These are not savestates; I don't know what the hell they are. And if that IPS doesn't match the rom image (for whatever reason) the game won't run. Deleting the file makes it run fine. Not only can I not find any info about this in the documentation, but I don't know any other FDS emulator out there that does this.

Why is this a thing? Can I turn this "feature" off? I don't anything about the technical side of this emulation crap, but I still don't see the point of this.

**Comment by jackwilsdon** [comment]
The IPS files are patches for the game. You can disable them being loaded under [Misc. Settings](https://www.mesen.ca/docs/configuration/preferences.html#misc-settings).

**Comment by SourMesen** [comment]
This is actually normal behavior, in a sense.  The IPS files created are save data.  FDS games modify their own data on the disk to save data, and this is saved as an IPS file in Mesen.  As far as I know, most NES emulators do something similar for FDS save data.

The problem is most likely that you used the IPS patch with the wrong FDS file at first, and while running that IPS patch, the game wrote data to the disk in such a way that created an IPS file (for the save data) and loading the IPS file corrupted the game data when used on the headered version of the ROM.

**Comment by SourMesen** [comment]
So, there was actually a bug that caused all FDS games to create an IPS file, even those that did not modify the disk's data.  This has been fixed, which should hopefully help prevent similar issues in the future.
