### ISSUE TITLE
libretro no stretch aspect ratio problem?

### ISSUE THREAD

**Issue by softtwo** [SourMesen/Mesen#635]
My settings are:
Vertical Overscan = None
Horizontal Overscan = None
Aspect Ratio = No Stretching

After taking a Retroarch screenshot, it says 240x240 (1.0). It should be 256x240 (1.06666).

I think the problem is here:
https://github.com/SourMesen/Mesen/blob/master/Libretro/LibretroRenderer.h#L61

Currently it says: 1.0 * 256 / 240 / 256 * 240 = 1.0

But I think this is the intended display aspect ratio:
```
ratio = (float)_console->GetSettings()->GetOverscanDimensions().GetScreenWidth() / _console->GetSettings()->GetOverscanDimensions().GetScreenHeight();
```

Screenshot then reports okay dimensions with any h/v overscan. Curiously though, it also works if ratio is kept at 0.0f. I guess frontend takes care of math in that case.

**Comment by SourMesen** [comment]
Thanks for the report - I'm pretty amazed nobody ever noticed this for over a year!

That particular line seems correct - it's meant to keep the aspect ratio consistent when the user turns on the overscan options (e.g the "no stretching" aspect ratio isn't 1.066 if the picture is rendered at 256x224 instead of 256x240).

The problem was that I was setting the "base" aspect ratio to 1.0 instead of 1.066 like it should have been when using the no stretching option. So the formula should have been:
`1.066 * 256 / 240 / 256 * 240 = 1.066`

It should be fixed as of the latest commit - I've taken some screenshots in a few different scenarios and compared to the standalone version and everything seems to match.
