### ISSUE TITLE
Simple fix for us that is stuck with xbuild

### ISSUE THREAD

**Issue by frakswe** [SourMesen/Mesen#644]
search for /property:DefineConstants="HIDETESTMENU;DISABLEAUTOUPDATE"
in the makefile and split them up like so: 

/property:DefineConstants="HIDETESTMENU" /property:DefineConstants="DISABLEAUTOUPDATE"

and Bob's your uncle.

i'm on Debian and for whatever reason msbuild isn't in the repo's and building it fails aswell with it complaining about the lack of libssl so i was shit out of luck.

**Comment by SourMesen** [comment]
I changed the makefile to use msbuild instead of xbuild not too long ago, because xbuild had this message saying it was deprecated and to use msbuild instead. But so far, it seems to be mostly causing people trouble more than anything, so I think it might be time to just revert the makefile to using xbuild until xbuild actually causes a problem or is no longer available..

**Comment by frakswe** [comment]
sorry for the grief you get for supporting linux :(

it'll probably work with both msbuild and xbuild with the fix though if you wanna support 'em both.

i'll just go ahead and close this then.

**Comment by SourMesen** [comment]
Thanks - I'll add it to my list and try and take a look when I get a chance!
