### ISSUE TITLE
Mesen 0.9.8 - Kid Dracula (Akumajō Special: Boku Dracula-kun) graphical glitches

### ISSUE THREAD

**Issue by TopHatHipster** [SourMesen/Mesen#659]
I've noticed some glitchy effects in the GUI while testing out the game. Other, more inaccurate, emulators like RetroArch's QuickNES displays it properly without flickering. This including flickering between the black lines of the GUI bar, and later on playing the first level strange white artifacts appear at the bottom (usually where the overscan is).

The footage I captured with OBS is linked below (couldn't attach it as it's over 10MB, GitHub's file limit). Do mind that there are audio-glitches (along with performance drops during it) which are NOT part of the emulation glitches I experience during normal gameplay. They are artifacts happening during recording, not during actual gameplay.
https://streamable.com/p22q8

**Comment by MrMinderbinder** [comment]
It looks like those effects are correct. This speedrun played on real hardware has those same effects: https://www.youtube.com/watch?v=LbPo5x3xOI8

**Comment by SourMesen** [comment]
Thanks for the report and videos!
This does look like it's probably normal - these kinds of glitches do occur in some NES games.  QuickNES most likely renders an entire line at a time, rather than 1 pixel at a time, which hides the imperfections (ironically being inaccurate ends up making the game "better" in this case.)
