### ISSUE TITLE
Castlevania II retranslation patch weird issue

### ISSUE THREAD

**Issue by laahel** [SourMesen/Mesen#660]
Hi. I tried the patch from here : https://bisqwit.iki.fi/cv2fin/
(Castlevania II retranslation with map and save games functionality)
I applied the patch on iNes 1.0 no-intro ROM and iNes 2.0 no-intro ROM.
iNes 1.0 : all is smooth and patch works as expected
iNes 2.0 : patch applied and working except for the save game function. It plays an error sound and the save / load screen cannot be displayed. Debbugger seems to trigger an error with invalid opcode.
Others emulators (puNes and FCEUX) have no problem with the iNes 2.0 patched rom.

Are there differences in the headers that make mesen behave differently in each case ??

**Comment by laahel** [comment]
Ok, i've played with the headers.  The patch automaticaly adds SRAM flag in the header (iNES 1.0 compatible). I manually add 8k PRG RAM battery backed flag, and now, the game shows the save / load screen as expected (thus, I still have invalid opcode on exit, but the game keeps going on).
I suppose then that mesen relies strictly on header information to allow certains things as other emulators don't really mind.
Maybe could cause problems with others SRAM patches that don't modify header V2.0

**Comment by SourMesen** [comment]
Hey, sorry for the long delay.

When a NES 2.0 header is used, Mesen ignores most of its heuristics and leaves pretty much everything up to the header.  If the header is incorrect (e.g wrong amount of RAM specified, etc.) then there may be issues, which is kind of the point. 

Being strict means that people who use NES 2.0 headers are forced to give all the correct information in the header, otherwise we just end up having to guess the information like iNES 1.0 forces us to do for a lot of stuff.
