### ISSUE TITLE
Feature request: map one physical controller into more than one controller in the emulator

### ISSUE THREAD

**Issue by laggarcia** [SourMesen/Mesen#661]
It would be nice if, with only one physical controller, we could map more than one controller in the emulator.

Many NES games, when you have 2 players, only one of them plays at once. Hence you should be able to share the same controller with two players in this situation.

It would be nice if there was a checkbox to activate such feature.

**Comment by SourMesen** [comment]
Thanks for the request (and sorry for the delay)
This is already possible - you can map multiple NES controllers to the same buttons/keys on your gamepad or keyboard, allowing you to press the same buttons on both controllers with a single button press.
The UI will most likely display a warning saying you have conflicting keybindings, but you can ignore that warning since this is actually what you want in this case.
