### ISSUE TITLE
Running Mesen requires Mono development libraries

### ISSUE THREAD

**Issue by jstolarek** [SourMesen/Mesen#667]
I'm trying to run Mesen on Debian Buster (10.0) with `mono Mesen.exe`. However, having `mono-runtime` installed does not suffice:

```
$ mono Mesen.exe

Unhandled Exception:
System.IO.FileNotFoundException: Could not load file or assembly 'System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' or one of its dependencies.
File name: 'System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'
[ERROR] FATAL UNHANDLED EXCEPTION: System.IO.FileNotFoundException: Could not load file or assembly 'System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' or one of its dependencies.
File name: 'System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'
```
I am only able to run the application after installing Mono development libraries (`mono-devel`), which, as an end user, I should not be required to do.

**Comment by SourMesen** [comment]
mono-runtime is not sufficient as far as I am aware, because it does not include some libraries (like WinForms which the error message refers to.)  The readme specifies that mono-complete needs to be installed (which contains WinForms, among other things), but does not include mono-devel, as far as I am aware.
