### ISSUE TITLE
Feature request: Fast Rewind (with the same speed as Fast Forward)

### ISSUE THREAD

**Issue by vrubleg** [SourMesen/Mesen#678]
It would be nice to have an ability to set a key for Fast Rewind which should be a pair for the Fast Forward feature. For example, if `Tab` is Fast Forward, `Shift+Tab` could be Fast Rewind.

**Comment by SourMesen** [comment]
You can already configure the speed at which rewinds occurs in Options -> Emulation.

Also, if you hold both the rewind & fast forward keys together, you will rewind at the speed of the fast forward.  e.g with the default bindings, Tab is FF, Backspace is rewind, Tab+Backspace is fast forward speed rewind (so 300% by default, instead of the 100% speed the rewind has by default)
