### ISSUE TITLE
Feature Request: Websocket support in Lua, or some other way of sending/receiving messages quickly

### ISSUE THREAD

**Issue by kmck** [SourMesen/Mesen#679]
Hey there!

I think it could be useful if there were a graceful way to do external communication from a Lua script in cases where the messages are small or very frequent. For example, suppose someone wanted to send the values of a few specific locations in RAM to some service in realtime.

Having LuaSocket to facilitate HTTP requests is better than nothing, but if the script needs to make a lot of requests quickly, the overhead adds up. There doesn't seem to be a way to make the requests behave in a fire-and-forget kind of manner, so overwhelming an HTTP server can stall the emulator while it waits for the responses. Total bummer!

I think being able to connect to a Websocket from a Lua script would help in this case, but I haven't personally had any luck getting any Lua Websocket libraries to build in Windows, let along work in Mesen's Lua environment. I suppose that Mesen itself could offer some kind of persistent connection on its own. What do you think?

**Comment by SourMesen** [comment]
Websockets would probably require a ton of code, I would rather not bloat Mesen's codebase just for this (especially since it's not something that the vast majority of users would ever use.)

Ideally, the best solution would be to use an external library for this (either as a compiled library or just Lua code that implements websockets?) Though, #583 might get in the way of this until that gets fixed, unfortunately.
