### ISSUE TITLE
Music pops in Jackal, Castlevania 2 Simon's quest

### ISSUE THREAD

**Issue by Cibomatto2002** [SourMesen/Mesen#69]
I was trying Nestopia today and notice the music in these to games sound better in Nestopia than any other emulator out there. here is a video I mad to show you.It would be nice if there was a filter or something like that to quit down the popping sounds.

https://www.youtube.com/watch?v=D2qUZUuRaPk&feature=youtu.be

**Comment by Nicholas-Steel** [comment]
Try Ninja Gaiden 3 music and tell me if you hear similar popping sounds. The "popping" is intentional but I agree it would be nice to have a filter to filter it out as I too dislike it (I know NotsoFatso filters it out by default).

When I say it is intentional, I mean the music developer is intentionally creating the popping sound to simulate a drum effect without needing to use a audio sample, which to some people just sounds awful :)

**Comment by Cibomatto2002** [comment]
If you could lower the volume on on all channels that would help.
![capture12-4-2016-10 26 45 pm](https://cloud.githubusercontent.com/assets/21169038/20873785/ea869040-ba70-11e6-8946-2bd9152863ce.jpg)

**Comment by SourMesen** [comment]
Thanks for the report!
This is actually caused by the DMC channel, not the noise channel.
I've added an option in the advanced audio settings to reduce the popping sounds on the DMC channel - it seems to work well for both games mentioned.  (e562ab744b36e5f752f84c9fc33c728f131ddb3f)

I'm not sure what you mean about the sound volume?  Mesen already lets you set the volume of each channel from the "Volume" tab in the audio options.

**Comment by Cibomatto2002** [comment]
I see that now SourMesen sorry about that.

**Comment by Cibomatto2002** [comment]
I see that Volume controll now sorry I need to pay more attention.
 

    On Sunday, December 4, 2016 10:36 PM, SourMesen <notifications@github.com> wrote:
 

 Closed #69.—

**Comment by Nicholas-Steel** [comment]
I can confirm this is resolved for at least Ninja Gaiden 3 and Castlevania 2. Dunno about the Jackal game the Op is talking about.

**Comment by Cibomatto2002** [comment]
Jackal sounds good to me.
