### ISSUE TITLE
Option to disable hotplugging

### ISSUE THREAD

**Issue by ansstuff** [SourMesen/Mesen#692]
When running Mesen on Windows my mouse keeps freezing for about 1 second every 5 seconds, which is extremely annoying. It keeps happening even when Mesen window is on background.

Before writing the bug report I've looked at source code and found the cause: directInput->EnumDevices() causes some faulty mouse driver to malfunction every time. In Windows Device Manager I was able to locate and remove the faulty HID device, and the issue was gone, but after rebooting the OS adds the device back. So every time I use Mesen I first have to go to Device Manager and delete the driver. Apparently these issues sometimes happen to people with different hardware:

https://stackoverflow.com/questions/10967795/directinput8-enumdevices-sometimes-painfully-slow

I ended up disabling DirectInputManager::UpdateDeviceList() in local build of Mesen. But I imagine other users would likely drop the emulator, failing to understand the cause of annoyance, because at first glance it looks like performance issue (constant hiccups).

So, there should be option "Enable gamepads hotplugging", ticked by default. Its description in docs could be: "disable this if you experience periodic freezes of a device".

**Comment by SourMesen** [comment]
Thanks for the detailed report!

I understand the freeze issue, but it's weird that this causes a freeze.  The call to UpdateDeviceList occurs in a separate thread so I wouldn't expect it to lock up the rest of the emulator - I guess there might be a lock inside DirectInput's code that causes the other threads to stop while the enum operation is on-going.

Adding an option seems like a good compromise, though I'm tempted to make hotplugging disabled by default (with an option to enable it) now that I know it can cause issues on some PCs (like you said, most users would probably not realize that the freezes are caused by this and then disable the option)

**Comment by ansstuff** [comment]
Wait, I called it freeze only for brewity. Actually, emulated game keeps playing without a hitch, and keyboard/gamepad work well, only mouse cursor isn't responding to physical movements for about 1 second.

I agree it's safer do disable hotplugging by default and only enum devices at startup, or maybe at "main window focus gain" event. It's just that so far only Mesen introduced me to the problem. Here I've tried another software with hotplugging (Cuphead, Unity game uses Rewired plugin) and there's no issues with my mouse, not sure what are they doing differently.

**Comment by SourMesen** [comment]
I've disabled the periodic check for directinput devices completely.  It will still check for new directinput devices when loading/resetting a game, or opening up the input configuration window, which should be enough to catch a lot of scenarios.

Hotplugging for XInput devices is still enabled, because that part presumably does not cause any issues.
