### ISSUE TITLE
Debugger - shaded labels after unnamed lables

### ISSUE THREAD

**Issue by andre-paris** [SourMesen/Mesen#698]
In the debugger screen with Source Code View enabled, all unnamed labels from a ca65 code disables the mouse hover over the labels in same line. Also, the line becomes unindented.

![mesen-bug1](https://user-images.githubusercontent.com/4292242/68946071-d0eb7b80-0790-11ea-8cc4-edfc76813a2b.png)

**Comment by SourMesen** [comment]
I've slightly improved the highlighting/indenting logic to support this scenario better.
The mouse overs worked fine already, though.  The problem you're having is most likely due to the fact you've selected a font that is not monospaced.  The disassembly *requires* a monospaced font to work properly, and the UI warns you if you try to select a font that is not monospaced.

If you switch to a monospace font like Consolas, the tooltips should appear correctly.
