### ISSUE TITLE
Open debugger on start

### ISSUE THREAD

**Issue by zvalentine22** [SourMesen/Mesen#713]
If this is an option somewhere it might benefit from being more clearly labeled/documented. If not, a setting or a command line switch would be a great addition :)

**Comment by SourMesen** [comment]
There's no way to do this at the moment, but I imagine that could definitely be useful for homebrew development/etc. I'll see about adding a command line switch for it.

**Comment by SourMesen** [comment]
Thanks for the request - this is available as of 314ba6858be1d0d93b9f13fbfd121e83c1a2df2c.  Just use the /debugger (or --debugger) command line switch to open up the debugger when Mesen is opened (you'll have to also provide the path to a rom for this to work since the debugger cannot be opened when no rom is loaded)
