### ISSUE TITLE
Letterbox 

### ISSUE THREAD

**Issue by Cibomatto2002** [SourMesen/Mesen#72]
Could we see Letterbox as a option? Something like this.
![capture12-4-2016-11 11 58 pm](https://cloud.githubusercontent.com/assets/21169038/20874464/ce6923da-ba77-11e6-9f57-cab6edc60a0c.jpg)

**Comment by SourMesen** [comment]
I thought this was already possible with the overscan settings + setting the aspect ratio to 16:9, but it looks like the aspect ratio setting doesn't interact with the overscan options very well.

I'll see what I can do to fix this.

**Comment by Cibomatto2002** [comment]
Overscan just cuts the picture down all I want is the black bars on top and bottom. kinda like this.

https://www.youtube.com/watch?v=2_IJybirrNQ

**Comment by SourMesen** [comment]
This should be fixed by cad8995696ce03ef714fda4e9a6f59d0d3ee29c7.
It's not quite a "letterbox" option, but in your specific case, it will make the 16:9 aspect ratio you are using automatically letterboxed in fullscreen mode if you set a top/bottom value in the overscan settings. (or in windowed mode you can stretch the window vertically to see black bars on the top and bottom of the screen)
Before this fix, the fullscreen mode wasn't actually using a 16:9 aspect ratio if the overscan settings were not all set to 0, and never showed a black bar.
