### ISSUE TITLE
Mesen does not support FDS NSFs loading from bank 0 to $6000-$7FFF 

### ISSUE THREAD

**Issue by karmic64** [SourMesen/Mesen#727]
Currently, when bankswitching FDS NSFs, Mesen will intentionally not write to $5FF6 or $5FF7 in its NSF driver if the initial bank numbers there are 0, resulting in that particular region of memory holding the "Work RAM" instead of the NSF data. This causes problems when attempting to play a NSF that expects to read data from bank 0 from $6000-$7FFF.

The fix is about as simple as removing the branches that skip the writes from the driver, but I would guess that this is some hack to make some buggy NSFs work. So if this is the case, I'd like to see some examples of said NSFs, just out of curiosity and to find the best middle-ground solution possible.

**Comment by SourMesen** [comment]
The assembly code Mesen uses to play NSF files is taken from Nintendulator's code.
I'm not quite sure why this particular condition is there.  

As is, just altering the assembly code will likely break other NSFs since any NSF that has bank 0 at either $E000 or $F000 will end up with PRG ROM at $6000/$7000 instead of work ram. Would also need to change the C++ side of things to prevent writes to $5FF6/7 from having an effect unless FDS is selected in the NSF header.

I have no idea whether this was done this way to fix issues in NSF files, or if it's possibly an oversight in Nintendulator's NSF code.

**Comment by SourMesen** [comment]
Looks like Nintendulator does have the same problem (but NintendulatorNRS fixes this.)
For now, I've removed the conditions - $5FF6/$5FF7 will always be written to when loading a NSF file that uses the FDS, regardless of whether or not the bank value is 0.
This should fix the problem you were having - let me know if you notice the change breaks any other FDS NSF files.
