### ISSUE TITLE
doesnt build with recent mono on linux

### ISSUE THREAD

**Issue by MichaelDavid53** [SourMesen/Mesen#728]
i had to check an earlier issue here to find out that after much failure my problem might be the version of mono I had was causing errors when running make. 
I finally found out how to downgrade my version to mono 5.18.1 and the build succeeded. But for a Linux beginner that's hard. I wonder if the documentation could be updated to make it clearer which version of mono is necessary, along with a few lines on how to obtain it, and how to force the version necessary. otherwise it would be great to somehow have the build work with the most recent versions of mono.

**Comment by SourMesen** [comment]
What doesn't work with the more recent version of mono? Having the errors would be helpful in finding a solution.  There's no reason it shouldn't work, but I haven't tested with anything over 5.2ish.

**Comment by MichaelDavid53** [comment]
after trying make in the mesen folder:

mkdir -p bin/x64/Release/Dependencies
rm -fr bin/x64/Release/Dependencies/*
cd UpdateHelper && msbuild /property:Configuration="Release" /property:Platform="AnyCPU"
/bin/sh: 1: msbuild: not found
makefile:89: recipe for target 'ui' failed
make: *** [ui] Error 127

**Comment by SourMesen** [comment]
Thanks - I'm assuming you're building 0.9.8 rather than the latest dev builds.
Mono vs xbuild/msbuild is a bit messy at the moment.  Compiling used to use xbuild, then xbuild was deprecated in favor of msbuild, but then they apparently stopped shipping msbuild with newer versions of Mono (as far as I can tell.)
I think Mono still ships with xbuild included even in the more recent builds, though, which is what the makefile currently uses if you try to build the latest commit.

**Comment by SourMesen** [comment]
You mentioned in your other issue that it's building properly when you try to build the latest commit instead of the 0.9.8 tag, so I'm assuming xbuild is available on your PC and seems to be working properly.
