### ISSUE TITLE
request libretro: smash tv - rotate controllers

### ISSUE THREAD

**Issue by newsie-oss** [SourMesen/Mesen#730]
This explains the problem here. Although it can be done with 2P also (4 controllers).
https://protipoftheday.com/node/403.html

It'd be nice if there's an easy way to toggle this feature without having to remap the controllers in the frontend. Thanks again!

**Comment by SourMesen** [comment]
Thanks for the request.
Since this is very specific to a single game, I don't think it's worth the extra code/UI complexity.
Also, you can already have game-specific configurations in RetroArch, as far as I know, so you should be able to have a config file specific for that one game. (which means you won't have to remap the controllers manually each time you play it)
