### ISSUE TITLE
You should check this - RPI4

### ISSUE THREAD

**Issue by Askmewho** [SourMesen/Mesen#758]
Hi!! well, Ive recentrly compiled master (I had to make several approaches because you made heavy changes this last days!)

Ive used gcc-9, added some rpi4 flags, lto, and overclocked the rpi4 to 2.0 ghz, it could go a bit further, but I wont to push her so hard.
Ive note mini stutterings even without this heavy hd pack. even when running almost 60 fps all the time (it can go higher without vsync) it does micro stutterings, dont know why or how to debug that, or if there is any speed hack or performance hack, etc.  

VIDEO:
https://www.youtube.com/watch?v=WeZI6tsfnhU&feature=youtu.be

I think with some workaround it could run better! Thanks!!!

**Comment by SourMesen** [comment]
Neat!  I didn't even realize you could run Mono on a RPI4, for some reason :p
I don't actually own one at the moment, so my ability to optimize for it is a bit limited, unfortunately (although I've been tempted to grab one and see how much performance I can get out of mesen & mesen-s)

One thing I can suggest would be to try compiling with clang instead of GCC, in my experience clang produces much faster code compared to GCC (20-30+% faster) for Mesen's code.

**Comment by Askmewho** [comment]
At your command sir. Yeah, I have tons of mono games running on my pi, even bastion or dust an elysian tale. Ive use the latest stable version they offer.. 6.something. there is an official mono link than provide the binaries.

**Comment by Askmewho** [comment]
I have this error with clang (8.0.1-4):

```
/usr/bin/ld: /tmp/lto-llvm-b71e4d.o: in function `os_tmpname':
ld-temp.o:(.text.os_tmpname+0x14): warning: the use of `tmpnam' is dangerous, better use `mkstemp'
clang: error: unable to execute command: Segmentation fault
clang: error: linker command failed due to signal (use -v to see invocation)
make: *** [makefile:146: InteropDLL/obj.x86/libMesenCore.x86.dll] Error 254
```

I will retry it on manjaro bc being so heavy on cpu may take great benefits on 64 bit build.

**Comment by Askmewho** [comment]
Ok, so it compiles and runs great on my rk3399(64 bit os). Ive use clang-9 and lto. So, I will compile the binaries for rpi4 from here.

**Comment by SourMesen** [comment]
Sorry for the late reply - I'm not overly familiar with Linux in general, unfortunately, so I can't really help much.  Maybe that overclocking is making it slightly unstable and that might be enough to cause clang to crash? It's especially odd since all versions of clang crash (I've never had issues with clang on my Ubuntu VMs over the years)

As far as 64 vs 32-bits, at least on Windows, the 32-bit version typically runs about 10-15% slower, I think, so you might get a decent speed boost from 64-bits, too.

**Comment by Askmewho** [comment]
Yeah, here its on rk3399 with clang. Take not than the rk3399 cpu its not that powerful compared to rpi4 https://youtu.be/-OOpByLfaLU

**Comment by Askmewho** [comment]
After testing mesen on rpi4 on 64 bit os, ive conclude it works better on rk3399. Maybe the extra cores or the big little approach gives some benefits on mesen. Mesen on rk3399 runs extremely smoth at 720p. Tested with metroid and castlevania with his latest hd packs. Ive tried so hard to understand why rpi4 was so not great than I conclude I dont know. Even on 64 bit and clang its more stable but slower than on raspbian 32 bit

**Comment by SourMesen** [comment]
Thanks for the test results - definitely interesting to know.
If/when I get around to getting a rpi4, I'll try and see if/how the code can be optimized a bit for it.  I'll let you know if I manage to make some decent progress.

**Comment by Askmewho** [comment]
Thanks @SourMesen , here its my last test on rk3399. I've had to change the sample rate bc it was making me nuts on the recording! heavy stuttering's on the sound, it was difficult to diagnose haha
https://www.youtube.com/watch?v=jPL1EUoCxIQ&feature=youtu.be
