### ISSUE TITLE
Requests: Update color palette while emulation is paused; allow main window to be in focus while Mesen options windows are open

### ISSUE THREAD

**Issue by Bohman-Timothy** [SourMesen/Mesen#760]
**Feature request (or bug?):** If you change the color palette while Mesen is paused, either by editing a color or by loading a different palette, Mesen does not show the changed palette in the paused image. This means you cannot compare the appearance of "before" and "after" the change in a moment of a game that isn't basically at rest already, especially since you can't pause and unpause the emulation (with a keyboard shortcut) while the color palette window (Video Options) is open. FCEUX and VirtuaNES both update the colors of the paused emulation; I'd like Mesen to do the same.

**Request:** If you could also allow pausing and unpausing the emulation with a keyboard shortcut (e.g. the Pause key) and player input via the keyboard in the game while the color palette window is open, that would be great too. I think this would best be accomplished by allowing the color palette window to move to the background, i.e. let the main Mesen window be selectable and move to the foreground while the color palette window is open. I suspect this may require changing that "overriding" quality that all the pop-up Mesen options/etc. windows have (that is, preventing the main window from being in focus). This would be convenient for several of those windows, I think.

**Comment by SourMesen** [comment]
Thanks for the request.

This is actually a lot more complex to fix than it might appear at first glance.
Allowing more than 1 configuration window at once would require a lot of extra logic to handle the "ok/cancel" operations properly, and might introduce a number of other issues.

As for the changing the screen as soon as the palette is changed, it's also rather a bit complex due to a number of things (for example avi recording would have to ignore this extra "frame", etc.)  The same kind of issues also exist when changing overscan values while paused, etc.

Unfortunately, all of this means it's a lot of effort to fix, for a relatively rare use scenario.  While I realize this is not possible for all games, my suggestion would be to use the game's pause feature when you want to change the palette
