### ISSUE TITLE
[General] Audio Equalizer clipping at high levels

### ISSUE THREAD

**Issue by eugene-s-nesdev** [SourMesen/Mesen#770]
Audio Equalizer clipping at high levels
See video:
[clipping.zip](https://github.com/SourMesen/Mesen/files/4184439/clipping.zip)

**Comment by SourMesen** [comment]
Thanks for the report.

I've fixed the equalizer so that it *does* cause clipping, rather than wrapping the value like what was happening in your clip.  This will still distort the sound to some extent when it happens, but it won't sound completely broken like it did right now.

Also, keep in mind some of the other effects will still be able to cause wrapping if you use them in combination to the equalizer (but the equalizer on its own should no longer cause any problem.)  The main solution here is to not set the master volume above 25% (e.g the default value), which will reduce the odds of wrapping/clipping ever happening in the first place.
