### ISSUE TITLE
Different default settings for mesen and libretro core

### ISSUE THREAD

**Issue by obunden** [SourMesen/Mesen#772]
I tried the regular app and some settings are disabled and/or "not recommended", but in retroarch they are enabled by default.

**Here is a list of settings that I think are handled differently**
"Enable HD packs"
"Remove sprite limit"
"Reduce popping on Triangle channel"
"Reduce popping on DMC channel"

Also noticed that the default sample rate is 96000 in retroarch and 48000 in mesen.

**Comment by obunden** [comment]
I think i was a bit too quick on the enter key. I found the "Use HDNes HD packs" option and I think that is equal to "Enable HD packs", so just ignore the first entry in the list. Let's hope that the rest are accurate at least.

**Comment by SourMesen** [comment]
Some of the defaults might be different, yes.  I didn't really pay attention to them all that much when I made the libretro core.  For the libretro core I think I mostly just went with the options that made the games look/sound the best, regardless whether that's 100% accurate to the original NES' behavior.

None of these are "not recommended" options, though, since they have no impact on the actual emulation and no have no downsides beyond a bit less sprite flickering & better sound.

**Comment by obunden** [comment]
@SourMesen I'm sorry it seems I dropped the ball once again. I mistook "Disable sprites (not recommended) for "Remove sprite limit (reduces flashing). I'd prefer it if the defaults was kept more "vanilla" tho. Both for coherence sake between the two client options, and so that quirks and personality of the system is represented correctly. Thanks for your time spent developing the emulator and excuse me for the previous oversight on my part.

**Comment by SourMesen** [comment]
I've changed the default for "remove sprite limit" to disabled to match mesen.

For the rest:
-HD packs being on has no effect unless the user installs a HD pack.  Turning it off by default would just make it harder for users to get HD packs working
-The sound options, while technically "inaccurate", actually just hide artifacts that appear due to emulation because of the sound resampling that occurs.  A PC's sample rate is typically ~44-48khz, the NES technically has a sample rate of 1.78mhz, which is about 40 times higher, so some sound artifacts are audible during emulation due to this - these options only serve to mitigate them.
