### ISSUE TITLE
the hd pack generator of messen not adding transparency, and not separete the sprites by color 

### ISSUE THREAD

**Issue by roney33** [SourMesen/Mesen#778]
the messen hd pack generator does not add transparency and does not separate sprites by color in some old games like ultima 3, even disabling the sort pages by ussage frequency option

**Comment by mkwong98** [comment]
Fixing this might be a problem with scale filters as they usually don't handle transparency.

**Comment by KitsuneZeta** [comment]
The transparency issue seems to be an (unintended) side effect of changing the Screenshot saving method to only write 24-bit BGR PNGs instead of 32-bit ABGR PNGs. The HD Pack Builder uses the exact same method for writing the PNGs, and because that method now strips out the alpha channel entirely, it fails to save transparency.

Commit f5bc7b48aef1255309ea8441d34e07dfa58dc38b was where the method was changed. Reversing that change does fix the transparency issue, but also makes screenshots have an unnecessary alpha channel (which I think was the point of the change in the first place)

**Comment by SourMesen** [comment]
@KitsuneZeta  Thank you for looking into this!  Now I regret not just closing the issue that asked for 24-bit PNGs in the first place instead of changing the code :p

It should be fixed as of the latest commit. (and as far as I could tell, the tiles appear to be correctly separated by their palette when unchecking the sort by frequency option)
