### ISSUE TITLE
[Feature Request] NTSC overscan borders

### ISSUE THREAD

**Issue by Famulator** [SourMesen/Mesen#782]
its an odd, entirely aesthetic-related request, but ive always been somewhat intrigued by the colored borders that appear in recordings of nes games. a genesis emulator (blastem) emulates a similar effect and i dont think many nes emus tackle the idea. i think it could look good with the ntsc filters.
side note, pal nes and dendy also includes borders, but they are always black-colored

**Comment by SourMesen** [comment]
Thanks for the request.  Unfortunately, I don't plan on adding this, mostly because it would increase complexity for a number of things that's just not worth the limited benefits (e.g overscan settings, aspect ratio calculations, etc.)

If you want to see the borders, this is already possible in the "Event Viewer" debug tool, which has a "Show NTSC borders" option.  This is obviously not ideal for gameplay, but it does at least allow you to view them.
