### ISSUE TITLE
Copy Tile (HD Pack Format) under Nametable Viewer does not pick up the background color

### ISSUE THREAD

**Issue by mkwong98** [SourMesen/Mesen#788]
I used this function in the title screen of Super Mario Bros and was given a palette as 0F36170F. However it didn't work when I put this into hires.txt and I had to change it to 2236170F, where 22 was the color for the blue sky.

**Comment by raousoft** [comment]
You took colors not from the sky, because 0F as black is transparent color ( and that blue of the sky is under it).
If you choose (Show attribute colors only) you will take a hint about it.

This is the title screen's name (super mario bros)
![image](https://user-images.githubusercontent.com/37517008/77322205-a64b9980-6d13-11ea-9aaa-9e0c44be1d3a.png)

As you can see above you are taking maybe from the same spot (which is black aka transparent color for the title name)

This is the attribute colors and how they are distributed on the screen:
![image](https://user-images.githubusercontent.com/37517008/77322330-deeb7300-6d13-11ea-8d1e-81718e2c41cc.png)

If we are about to cancel black color as a transparent color it will be like this just to demonstrate:

![image](https://user-images.githubusercontent.com/37517008/77322403-f591ca00-6d13-11ea-9ffd-f448995f4309.png)

Studying the game how it works will be better at first.

**Comment by mkwong98** [comment]
I know all that. The point is that the HD pack builder generates 2236170F in the hires.txt and the HD pack engine expects 2236170F in the hires.txt so why would a function called "Copy Tile (**_HD Pack Format_**)" give me 0F36170F?

**Comment by SourMesen** [comment]
Thanks for the report!
This was because the $04/$08/$12 index colors were being used, instead of using index $00 for all 4 palettes for the background color.  This is fixed in the latest commit.
