### ISSUE TITLE
No audio devices recognized in Ubuntu 19.10

### ISSUE THREAD

**Issue by ianbjohn** [SourMesen/Mesen#790]
When I go to audio settings, there are no available options under "Device", and no audio gets played. I was able to compile with 0 warnings or errors, but I haven't been able to test yet to see if it would be an SDL install-related issue or something on my end yet.

The audio devices I have installed on my machine are:
Device-1: Intel 200 Series PCH HD Audio driver: snd_hda_intel 
Device-2: NVIDIA driver: snd_hda_intel
Sound Server: ALSA v: k5.3.0-42-generic

**Comment by SourMesen** [comment]
My ability to help here is probably rather limited - the dropdown displays what SDL gives, and sometimes SDL returns nothing (iirc).  Another user had this a long time ago and it caused no sound to be outputted because the code was trying to specify an "empty" device.  The code at the moment should just let SDL use its default sound device when it can't find any to list.  Maybe the sound is somehow being sent to the wrong output device, line out or headphone jack, etc?

**Comment by ianbjohn** [comment]
Ok, looks like it was just an issue with my build of SDL, or perhaps having multiple installed in different places. Rebuilding SDL and then Mesen seemed to finally fix it.

Thanks.
