### ISSUE TITLE
Crash without any error dialog

### ISSUE THREAD

**Issue by binarycow** [SourMesen/Mesen#791]
Steps to replicate:

- Open Mesen 0.9.9, Build date 2020-02-01, on Windows 10 version 1909 (Build 18363.657)

- Load nestest-automated.nes
- Open the debugger
- Open the trace logger
- In the debugger, power cycle the NES
- Click "Clear Log" in the trace logger
- In the trace logger, click "Start Logging" and select a file
- In the debugger, click the "Continue" button
- MESEN crashes

nestest-automated.nes is the normal nestest.nes file, with 0xC000 manually entered in the reset vector: [nestest-automated.nes.zip](https://github.com/SourMesen/Mesen/files/4381254/nestest-automated.nes.zip)

Here are my Mesen settings: [settings.zip](https://github.com/SourMesen/Mesen/files/4381277/settings.zip)

And here's the debugger files.  Note that in the trace log, it seemed to crash in the middle of an RTS instruction.
[nestest-automated.Workspace.zip](https://github.com/SourMesen/Mesen/files/4381290/nestest-automated.Workspace.zip)

Additionally, note that when running this rom in Mesen (without the debugger attached) it states "Game has crashed (Invalid OP code - CPU crashed.)"

- the rom works perfectly fine *without* my manual reset vector change (but is interactive, not automated)
- Even if an invalid opcode causes the emulated CPU to crash, this should not crash the application.

**Comment by SourMesen** [comment]
Thanks for the report.

I haven't investigated in depth yet, but it looks like the crash may be due to the ROM attempting to execute code from unmapped memory (e.g open bus) at $5xxx, which is causing issues with some of the debugger logic (and crashes in the debugger's code.)

It does not appear to be related to invalid opcodes - these are treated as any other op code, the only difference is that a message is shown when a "halt" opcode is hit to inform the user the game has crashed.

**Comment by SourMesen** [comment]
The crashes should be fixed as of the latest commit - thanks again for the report!
