### ISSUE TITLE
Integrate this NES 2.0 Header database into the emulator.

### ISSUE THREAD

**Issue by Yersho** [SourMesen/Mesen#808]
https://forums.nesdev.com/viewtopic.php?f=3&t=19940 (Database in question).
This should definitely add more compatibility with headerless NES ROMs and let people who don't know how to make a header or people who can't find specific info (PRG ROM size, CHR ROM size, Save RAM size, etc.) have more user friendly compatiblity.

**Comment by SourMesen** [comment]
Thanks for the request. This is already done as of this commit a few days ago: 77e04a679e713fdcf78d517d4efda987a236412f

**Comment by Yersho** [comment]
Oh, my bad. Now that there is a near complete NES 2.0 header database integrated into Mesen do you think it would be possible for you to maintain a updated header database from now on? (Sorry for asking a question in a closed issue I just feel I shouldn't waste your time with a brand new issue asking this.)

**Comment by SourMesen** [comment]
No, I don't plan on maintaining the DB myself.  As far as I can tell, NewRisingSun is planning on keeping it up-to-date since it's relatively easy for him to generate it from a set of ROMs he has.
I will be re-updating the embedded DB in Mesen when NRS updates his database as time goes on, but won't be maintaining it as a separate thing (I simply don't have the time to do this on top of everything else)

**Comment by Yersho** [comment]
Oh ok, I understand. As long as the database is properly maintained somewhere I'm fine with it.
