### ISSUE TITLE
dynamic recompiler support

### ISSUE THREAD

**Issue by Cibomatto2002** [SourMesen/Mesen#810]
If Mesen had dynamic recompiler support would it help Mesen run faster on the pie?

**Comment by SourMesen** [comment]
Dynamic recompilers kind of do not make much sense for platforms like the NES and SNES - the timing of all the chips in the system must be followed perfectly to prevent games from breaking, because a lot of games depend on these precise timings - dynamic recompilation does not really allow this.  While it's technically possible to some extent to dynamically recompile NES code, you would lose a ton of accuracy in the process, so at that point you're better off just using a less accurate & faster emulator in the first place.

**Comment by Cibomatto2002** [comment]
Thanks for explaining it to me.
