### ISSUE TITLE
mesen solution for visual studio doesn't compile into an executable

### ISSUE THREAD

**Issue by properchopsticks** [SourMesen/Mesen#827]
hi,

i tried downloading the mesen repository in visual studio 2019 using the github extension and i tried compiling the solution and it did complete successfully but it didn't result in the mesen exe file but instead into multiple .lib .dll and some .exe's but not the mesen one. i made a screenshot [here](https://cdn.discordapp.com/attachments/457543353131597855/708783375258878053/Capture.PNG) of the files that result when building as release for x64.

i'm using visual studio 2019 community edition on windows 10. i wasn't sure if this is a bug or not but i couldn't find any other support channels. let me know if there are other places for support related issues.

**Comment by SourMesen** [comment]
It should build fine with as Release + x64 using VS2019, since that is what I use.  The only thing I can offer is that you may not have C# support installed in VS2019, or are lacking some support packages to target the .NET Framework, which has most likely caused the .NET projects in the solution to not load. Check the solution explorer - GUI.NET (and another project) is most likely marked as "unloaded".  You'll have to install whatever requirements are missing to get the project to load and build properly.

**Comment by properchopsticks** [comment]
hey thanks a lot, i finally got it to work. a couple of notes i'd like to add: initially it said that it couldn't load the projects because the targeted net framework wasn't installed. on my system net framework 4.6.1 was installed by default and i couldn't install 4.5 but i was able to install the targeted framework from the net framework category in the visual studio launcher.
also when building as release it's recommended to select the GUI.NET as the default startup project otherwise it'll give a runtime critical error when running mesen.exe for the first time.

**Comment by properchopsticks** [comment]
i made a pull request for the updated compiling.md file, i think we can close the issue if everything looks good.
