### ISSUE TITLE
strange corruption with ppu viewer with toki

### ISSUE THREAD

**Issue by lyonhrt** [SourMesen/Mesen#836]
Odd ppu viewer bug. Not sure if it affects other games, but with toki when selecting ppu viewer under debug menu produces corrupted results majority of the times. However selecting ppu viewer through tools under debugging has no issues.
This is still doing this in current windows dev build 0.9.9.55 as well as 0.9.9 (no other version tested)

**Comment by SourMesen** [comment]
Both "open ppu viewer" buttons do the same thing, so that's unlikely to be the cause.
As far as I can tell, this is normal - Toki switches CHR banks (e.g the graphics), midway through the screen, so the contents of the nametable viewer, for example, will depend on when you have set it to refresh (at the bottom of the window, you can select a specific scanline - try setting it to e.g 100 instead of the default 241, and you'll probably see the graphics switch to their "correct" version)

This is fairly common in NES games - Super Mario Bros 3 does the same thing, which causes the status bar to look incorrect, or the stage to look into, depending on the scanline you pick for the refresh.

If I'm misinterpreting this, please post a screenshot of what you mean by corruption, thanks!

**Comment by lyonhrt** [comment]
yeah that was it, and realised it worked better with debugger selected as it paused things properly!
bit of a face palm moment!
