### ISSUE TITLE
More AVI codecs selection

### ISSUE THREAD

**Issue by Yave-Yu** [SourMesen/Mesen#837]
In current version, we can only use 3 codecs, but I want more.
CSCD is a lossless codec, but I think TSCC is better than that, it generates more small AVI size but lossless graphic.
If you implement AVI codec selection like other emulators, it would be wonferful!
![20200526192302](https://user-images.githubusercontent.com/54294476/82895206-6ceb1080-9f86-11ea-8129-d67ad87970c8.png)

**Comment by SourMesen** [comment]
Thanks for the request.  Unfortunately, displaying that dialog you are referring to requires Windows-specific code, which I have purposefully avoided for the AVI export feature, because I need to support Linux as well.

Adding more codecs manually is time consuming, requires a lot of testing and does not really add anything to the program, so I would prefer to use my time on more unique/useful features.  I would recommend using ffmpeg to convert the AVI files Mesen creates into whatever format you need.

**Comment by Yave-Yu** [comment]
> because I need to support Linux as well.
I get it.
