### ISSUE TITLE
Broken on Valkyrie no Bouken - Toki no Kagi Densetsu (DvD Translations)

### ISSUE THREAD

**Issue by litaniast** [SourMesen/Mesen#838]
After I input the player information, the screen glitches. after I walk a while, it hangs. 
Played in libretro (Windows x64)

Untranslated original version is working well.
Translation patch is: http://www.romhacking.net/translations/1378/

![Valkyrie no Bouken-200527-104542](https://user-images.githubusercontent.com/4857928/82968160-a0ba4a80-a007-11ea-9d88-d621b63ce4cc.png)

**Comment by SourMesen** [comment]
Generally speaking, I can't really spend my time investigating translations and rom hacks, otherwise it's all I will do.  That being said, I checked this one, and as far as I can tell, it's the patch's fault - it does not properly initialize the MMC3's registers, so it crashes. I would except a lot of the older translations/romhacks to not work properly because a lot of them were never tested on actual hardware, and only tested on the emulators that were available back then (which were not as accurate, etc.)

**Comment by litaniast** [comment]
Ah, it's just failure of patch that we didn't know in inaccurate emulators. I see. Okay
