### ISSUE TITLE
Windows Key detected as keybind

### ISSUE THREAD

**Issue by baboomerang** [SourMesen/Mesen#844]
hi, 

When the "Windows" Key is pressed on the Arch-Linux Mesen build, it's detected as a random key-bind. Sometimes it repeats the last key-bind pressed, (like open file, namespace viewer, step 1 CPU cycle) or does something different on its own.

I have reinstalled arch linux from scratch multiple times, tried building on gentoo and arch and this problem is still there.

Pressing the windows key should do nothing when it was never bound to any command.

My system is:
` $ uname -a
5.6.15-arch1-1 #1 SMP PREEMPT Wed, 27 May 2020 23:42:26 +0000 x86_64 GNU/Linux`

How to reproduce:
install linux,
run and build mesen
press the windows key with a rom open and playing.

**Comment by SSBMTonberry** [comment]
I was just about to post this problem myself!
I'm using Arch Linux and i3wm, where I use the <Windows>/<Super> for a lot of stuff, and it's kinda annoying with Mesen, which otherwise is the best emulator for Linux, especially if you need those neat debug tools.
I have noticed that what I get when pressing the <windows> key, is that Debug->PPU Viewer -> Compact -> Nametable Viewer shows up. I checked the config file for hotkeys on that part, and it was set to "None". I tried to assign something there, though, just to see the result, and then "CHR Viewer" showed up when pressing <windows> instead. So first impression is that it somehow triggers the first unassigned tool under Debug -> PPU Viewer.

**Comment by SourMesen** [comment]
Thanks for the report!
Looks like this is essentially a Mono bug, but easy enough to work around.  This should be fixed as of d738b2b9bfc96f1cb139c766337ef06cde428e76 (the same bug was fixed on Mesen-S as well)
