### ISSUE TITLE
macOS 10.15 Support (with GTK# Frontend)

### ISSUE THREAD

**Issue by mcser** [SourMesen/Mesen#847]
Hey,

first off, I know that this emulator only officially supports Linux and Windows. However, I was tinkering around a little and managed to get the program to compile on the latest version of macOS 10.15 (I had to remove Gamepad support from the code temporarily as evdev is not available on macOS, everything else loaded with some workarounds though). However, upon trying to actually run the program using the provided make run goal, mono crashed halfway through launching because their implementation of Windows.Forms on macOS relies on the deprecated Apple Carbon API, which has been removed as of macOS 10.15, so the UI immediately implodes.

My question is now (As I can't really judge this because I lack experience in this field): Would it be realtively easily possible to port the app to a GTK# Frontend? This would potentially enable at least the more tech-savy users to use the emulator on macOS (without Gamepad support). Or should I wait until mono provides a more stable implementation of Windows.Forms for Mac?

Thanks in advance. If this is too time-intensive or something, feel free to close the issue right away.

**Comment by SourMesen** [comment]
Unfortunately, rewriting the UI to use GTK# would likely take months (there is a ton of UI in Mesen, due to the debug tools - and then I would have to do the same thing again for Mesen-S)  Winforms was chosen because it is easily the most convenient/quickest UI toolkit to develop with that I know of, so I'm also not too keen on changing to something else, either :p

Windows.Forms on macOS, even before 10.15, was pretty broken compared to the Linux implementation, too, so even older macOS versions couldn't really run Mesen properly (I did make a macOS build as a test at some point a couple of years ago, but the UI had a lot of issues)

The only way forward, from my point of view, is for mono to support winforms on macos properly - but as far as I know, the Mono project is no longer working on its WinForms implementation at all, and pretty much leaves it in the hands of the community to fix/update it as needed, at this point.  So unfortunately, support for winforms in mono on macOS might never be added again.

See also: #841, #806, #638, #521, #367, #123
