### ISSUE TITLE
About translation (Ar)

### ISSUE THREAD

**Issue by raousoft** [SourMesen/Mesen#849]
Hi dear Sour,

After this two years since we talked about Arabic translation, I want to get back to the OSD font situation (https://github.com/SourMesen/Mesen/issues/427#issuecomment-401557999).
Since I no longer am able to see the translation results (to carefully put the %1 variable in the right place).

![image](https://user-images.githubusercontent.com/37517008/84391907-811f4680-abf1-11ea-9d0d-e8c1eef32b8d.png)

Is there a chance that you can guide me on that (displaying the font u used) in VS2019.
Also, I noticed that Debugging tools are not gonna be possible to be able to translate ? I really wish that since I am more interested in translating the debugging stuffs more than the basic GUI elements themselves.

Beside the emulator, if there is a chance I wanna translate the website + the documentation ( I already tested everything since I deal with web development, I fully RTL-ized the website and the documentation (Hugo stuff ).
![FireShot Capture 017 - Home __ Mesen Documentation - ](https://user-images.githubusercontent.com/37517008/84393545-a0b76e80-abf3-11ea-9939-4429c9a2052f.png)
 
Thank you :)

**Comment by SourMesen** [comment]
The debugging tools are not translated into any language, no.  Unfortunately, this will have to remain this way - it would be far too much of a time investment to allow them to be translated, check that the layout works with the various languages, etc. To be honest, just the regular UI already requires a fairly noticeable time investment (esp. since I'm maintaining 3 of the languages myself), and this is why Mesen-S is English-only.

As for the documentation, thanks for the offer, but like the debugger tools, I would rather stick to English-only for various reasons.  Having documentation in multiple languages implies that some languages will be "behind" on others and lacking important information about new options, or changes to things like the HD pack or Lua API specifications, etc.  I would rather stick to a single copy of it - multiple languages would be a nightmare to maintain in the long run (and maintaining that documentation already takes a decent amount of time each version)

As for translating the UI in Arabic, it does imply even more testing on my end in terms of layout, etc. any time I change something relatively large. Between Mesen and Mesen-S, I'm already barely managing to keep up with bug reports and feature requests, as it is. At the very least, I will probably not have time to look into this soon, sorry!

**Comment by raousoft** [comment]
There in nothing to be sorry about , I appreciate your time and I value that, which is important than translating or anything else, Feel free to inform me about future changes if they will be :)
