### ISSUE TITLE
0.6.1 warning on start when use non-portable version

### ISSUE THREAD

**Issue by eugene-s-nesdev** [SourMesen/Mesen#87]
Some users found a bug. I can confirm on Win10x64:
Since 0.6.1 there is bug on start.
Solve: rename "Mesen.exe" to "Mesen_P.exe"

![default](https://cloud.githubusercontent.com/assets/13199529/21514822/9daf690a-ccda-11e6-936b-c27f743075e6.png)

**Comment by SourMesen** [comment]
Thanks - I'm not sure why the portable version would change this, but it's a good hint.
It's probably related to the changes I had to do for the Linux port.
I'll give it a try on my Windows 10 VM tomorrow and see if I can reproduce it here.

**Comment by SourMesen** [comment]
Thanks for the report (and the workaround - that helped me figure out the problem quickly)
This should be fixed by 083c2d20839819832cb9516733898d0222ccbc6d
It only occurred when paths contained non-ascii characters (On a russian copy of windows, you probably have russian words in the path to the "Documents" folder, which caused the crash).
