### ISSUE TITLE
Open NSF

### ISSUE THREAD

**Issue by Cibomatto2002** [SourMesen/Mesen#97]
Could we see a way to open NSF files besides the way we do it now. Like File, Open NSF.

**Comment by Nicholas-Steel** [comment]
You can associate NSF files with Mesen and use Windows Explorer, cortana, etc. to open them.

**Comment by Cibomatto2002** [comment]
If I do that will I have to tell Mesen where my roms are again? Every time I play a NSF file I have to find my rom folder again.

**Comment by Nicholas-Steel** [comment]
Unsure.

**Comment by SourMesen** [comment]
If possible, I'd rather not have an "Open NSF" option because it's likely that a lot of users would never use it (and so it makes the UI a bit less user-friendly) - but maybe I'm underestimating the number of users that play NSFs with Mesen.  
I understand the issue, but I can't think of a solution that would be good for all users at the moment.

**Comment by Nicholas-Steel** [comment]
Many emulators do offer a separate menu option for opening NSF files with the File Open dialog box using a separate path to the ROM File Open dialog box.

**Comment by Cibomatto2002** [comment]
It's something we don't really need I have a stand alone player that will play them. Keep up the good work on the Emulator. In the future are you going to add more consoles like Gameboy?
